### ISSUE TITLE
read! leaks file descriptors

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#10]
Opening lots of files seems to cause `IOException: Too many open files`. We're probably not closing things properly.

**Comment by lihaoyi** [comment]
Can't repro, might be a problem in the client code

**Comment by tomjridge** [comment]
The following, with a very large number of files, seems to crash reliably with Exception in thread "main" java.io.IOException: Cannot run program "bash": error=24, Too many open files

  val ds = (%%bash("-c","(find $PWD -type d || true) 2>/dev/null")).toSeq.view
  val ds2 = ds.map( (x) => ammonite.ops.Path(x))
  val ds3 = ds2.toList
  val ds4 = ds3.filter( (x) => (ls! x).length > 100) // crash here                                                                                               

Is there a problem with this code?

**Comment by tomjridge** [comment]
My (limited) experience is that ammonite is not really ready for use when operating with "real" filesystems with lots of files, broken links, etc. For small numbers of files, it works very well.
