### ISSUE TITLE
Consolidate persistent data in a sensible way

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#101]
We currently have the `~/.amm` file, which contains the command history in a crazy ad-hoc syntax. Soon we'll be adding cached bytecode (https://github.com/lihaoyi/Ammonite/issues/95), and cached dependency resolution (https://github.com/lihaoyi/Ammonite/issues/100) and no doubt more things in the future.

We need to figure out a more structured way of doing this (make `~./amm` JSON? YAML? A folder with flat files? SQLite?) that won't become a huge mess in future.

**Comment by laci37** [comment]
I'd say make it a `~/.ammonite` folder. I would write out the full name so it is easy to see which application created the folder. Having a directory structure inside won't make a mess I think. Something like this:
```
.ammonite
  cache
    ivy
      jarfile.jar
      jarfile2.jar
    scripts
      block1.class
      block2.class
  history
  user_settings
```
We can can store caches in single files too. If we use a directory structure backwards compatibility wouldn't be hard to solve either.

**Comment by lihaoyi** [comment]
Sounds reasonable. Ivy jars I don't think we should copy; we just need to cache the path to the file since they'll all be cached in the `~/.ivy` folder anyway, maybe with a hash. If the jar disappears, or doesn't match the hash, we can ask Ivy to re-download it.

I think the other plain-text-code data can live in YAML files, because their [block notation](http://en.wikipedia.org/wiki/YAML#Newlines_preserved) would make the text both very easy to human-read (no escaping!), very easy to human/machine edit, and very easy to machine-append (so we don't need to re-write the entire history file or ivy-resolution file each time we add a new entry).

**Comment by lihaoyi** [comment]
@laci37 do you want to pick this up as well and take a first pass at it? You're going to need it as part of https://github.com/lihaoyi/Ammonite/issues/95 anyway to put your class-files somewhere

**Comment by laci37** [comment]
Okay, I'll get started.

**Comment by lihaoyi** [comment]
Thanks to @laci37 we now have a `~/.ammonite/` folder which currently contains:

- `history`
- `ivycache.json`
- `predef.scala`

And lots of room to add more stuff. Even though we don't yet have proper concurrency semantics, I'm going to call this closed
