### ISSUE TITLE
Ammonite's Interp 2.13 is not compatible with 2.13 Scala

### ISSUE THREAD

**Issue by hubertp** [lihaoyi/Ammonite#1023]
Discovered while updating some dependencies for Almond's custom kernel (the details are irrelevant for this bug).

If you compare different `CompilerCompatibility` versions for 2.12.x and 2.13.x:
https://github.com/lihaoyi/Ammonite/blob/master/amm/interp/src/main/scala-2.13/ammonite/interp/CompilerCompatibility.scala#L33
and 
https://github.com/lihaoyi/Ammonite/blob/master/amm/interp/src/main/scala-2.12/ammonite/interp/CompilerCompatibility.scala#L34
the latter contains the `AbstractReporter` (gone in 2.13.x) from `scala.tools.nsc.reporters.AbstractReporter`.

Everything good so far. 
The problem is when you are trying to use the published artifacts for `ammonite-interp` for 2.13.
By looking at the bytecode (e.g. https://mvnrepository.com/artifact/com.lihaoyi/ammonite-interp_2.13.1) you can see that the provided version has in the `initGlobal` signature `AbstractReporter`, so it was compiled with the 2.12.x version. The problem exists in all 1.8.x versions. ~1.7.4 appears to be good.~ (see comment below)
This results in a rather hard to track bug manifesting itself as `ClassNotFoundException`:
```
java.lang.ClassNotFoundException: scala.tools.nsc.reporters.AbstractReporter
  java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ammonite.interp.Compiler$.apply(Compiler.scala:141)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:98)
  ... (omitted, closed source)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:512)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:572)
  ammonite.util.Res$Success.flatMap(Res.scala:62)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:569)
  ammonite.util.Res$Success.flatMap(Res.scala:62)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:566)
  scala.Option.getOrElse(Option.scala:201)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:566)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:604)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:400)
  ammonite.util.Catching.flatMap(Res.scala:115)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:391)
  ammonite.util.Res$Success.flatMap(Res.scala:62)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:381)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:126)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:126)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:75)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:32)
  scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
  scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
  scala.collection.immutable.List.foldLeft(List.scala:79)
  ammonite.util.Res$.fold(Res.scala:30)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:63)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:128)
```

**Comment by hubertp** [comment]
I don't have much experience with mill, but pretty sure the problem is in [here](https://github.com/lihaoyi/Ammonite/blob/master/build.sc#L47). I will send a PR once I figure it out.

**Comment by hubertp** [comment]
Correction - this is broken for 1.7.4 cross compiled to 2.13 as well. Edited title to reflect that.

**Comment by lihaoyi** [comment]
Thanks for the report! I'm curious why Ammonite works at all given the binary incompatibility? Shouldn't the `amm` executable be broken as well?

**Comment by alexarchambault** [comment]
I can't find that issue in the published Ammonite artifacts:
```java
$ javap -cp "$(cs fetch --classpath ammonite:1.8.2 --scala-version 2.12.10)" ammonite.interp.CompilerCompatibility
Compiled from "CompilerCompatibility.scala"
public final class ammonite.interp.CompilerCompatibility {
  public static scala.tools.nsc.Global initGlobal(scala.tools.nsc.Settings, scala.tools.nsc.reporters.AbstractReporter, scala.tools.nsc.classpath.AggregateClassPath, java.lang.ClassLoader, scala.Function1<scala.tools.nsc.Global, scala.collection.immutable.List<scala.tools.nsc.plugins.Plugin>>);
  …
}
$ javap -cp "$(cs fetch --classpath ammonite:1.8.2 --scala-version 2.13.1)" ammonite.interp.CompilerCompatibility
Compiled from "CompilerCompatibility.scala"
public final class ammonite.interp.CompilerCompatibility {
  public static scala.tools.nsc.util.ClassPath createZipJarFactory(scala.reflect.io.FileZipArchive, scala.tools.nsc.Settings);
  …
}
```
(nor in the Ammonite launchers on GitHub).

That's possibly an issue with the way almond is installed (pulling wrong Ammonite artifacts). It relies on the coursier CLI, and I remember having fixed some scala prefix handling issues recently… @hubertp If you're not using the latest coursier launcher already, would you mind trying again with it? (See the instructions around [here](https://get-coursier.io/docs/cli-overview.html#curl) for example.)

**Comment by hubertp** [comment]
It could indeed be a coursier thing, I will give it a try.

**Comment by hubertp** [comment]
Looks like the problem is somewhere else, indeed. Thanks for verifying.
