### ISSUE TITLE
Feature Suggestion: support Twirl templates in Ammonite scripts

### ISSUE THREAD

**Issue by uosis** [lihaoyi/Ammonite#1039]
We often find ourselves using ammonite scripts to generate ad-hoc text. While it's doable using string interpolation, it would be very nice and powerful if it was possible to embed Twirl templates in a script.

Since ammonite already supports multi-stage compilation using `@` delimiter, I think this would fit into existing flow nicely - `@twirl` or something could be used to designate next block as Twirl template.

Thoughts? How difficult would be something like this to implement?

**Comment by lihaoyi** [comment]
This is probably out of scope for Ammonite, but you can probably implement this yourself using a macro string inteprolator

**Comment by sake92** [comment]
@uosis what kinds of text, HTML? Try [scalatags](https://github.com/lihaoyi/scalatags) for rendering raw HTML, or [Hepek](https://sake92.github.io/hepek/hepek/components/index.html) (grids, code highlight, Fontawesome, math, etc.) for more advanced stuff.

**Comment by uosis** [comment]
@sake92 thanks for the suggestions!

It's mostly random config files and such which don't have builders for them though, so we are stuck with text templates.
