### ISSUE TITLE
Pull down source-jars with Ivy and feed them into Pressy for in-repl docs

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#105]
This is going to be a pain in the arse due to interfacing with my two least-favorite parts of Ammonite, but it would be so awesome if it worked.

**Comment by coderabhishek** [comment]
I worked for sometime on this issue though could not fix it. 
The approach I tried was to extract the scalaDoc using `askDocComment` defined here https://github.com/scala/scala/blob/33e32179fd6dcf06554b817f54b97ac5a6e052ab/src/compiler/scala/tools/nsc/interactive/CompilerControl.scala#L176.
But askDocComment seems to be not working, for details please go through this conversation
http://scala-language.1934581.n4.nabble.com/How-to-use-askDocComment-defined-in-scala-tools-nsc-interactive-td4646329.html

Another plausible way might be experimenting with ScalaDoc source code.

**Comment by lihaoyi** [comment]
This has been superseded by the new `source` builtin
