### ISSUE TITLE
In ammonite released for Scala 2.13 macro annotations doesn't work

### ISSUE THREAD

**Issue by MateuszKubuszok** [lihaoyi/Ammonite#1080]
For cases that I tested I was unable to make macro annotations expand in Ammonite, despite enabling `-YmacroAnnotations` flag. These cases works if I compile them normally. Example:

```scala
@ interp.configureCompiler(_.settings.YmacroAnnotations.value = true)


@ import $ivy.`io.scalaland::catnip:1.0.0`, io.scalaland.catnip._, cats._, cats.implicits._, alleycats.std.all._
import $ivy.$                           , io.scalaland.catnip._, cats._, cats.implicits._, alleycats.std.all._

@ @Semi(Show) case class Test(a: String, b: Int, c: Double)
cmd2.sc:1: enable macro paradise to expand macro annotations
@Semi(Show) case class Test(a: String, b: Int, c: Double)
                       ^
Compilation Failed
```

In earlier version of Ammonite (which used 2.12) running this code with macro paradise plugin (`interp.load.plugin.ivy("org.scalamacros" % "paradise_2.12.4" % "2.1.0")`) worked.

I understand if this is low priority issue and will be a won't fix, though I would like to at least have it documented here as an issue, since I haven't found any information about it anywhere.

**Comment by alexarchambault** [comment]
That could originate from the custom analyzer that [Ammonite sets up](https://github.com/lihaoyi/Ammonite/blob/3eba4aed3a7c45d315601ab38fe5b77a61060c22/amm/interp/src/main/scala-2.13/ammonite/interp/CompilerCompatibility.scala#L50). scalac [uses a different analyzer when `-Ymacro-annotation` is passed](https://github.com/scala/scala/blob/434a3d78fa1ec160ab090bc434bccbfc684a07d0/src/compiler/scala/tools/nsc/Global.scala#L481). Ammonite should probably do the same.

**Comment by alexarchambault** [comment]
I confirm that fixes it.
