### ISSUE TITLE
object Properties is not a member of package ammonite.util

### ISSUE THREAD

**Issue by JWDobken** [lihaoyi/Ammonite#1097]
I want to check [the version of scala inside a command](https://stackoverflow.com/a/27086197) but the object Properties is not available:

```scala
@ util.Properties.versionString 
cmd0.sc:1: object Properties is not a member of package ammonite.util
val res0 = util.Properties.versionString
                ^
Compilation Failed
```

Ammonite Repl 2.1.4 (Scala 2.13.2 Java 1.8.0_242)

**Comment by alexarchambault** [comment]
@JWDobken This just a namespace clash (`scala.util` vs `ammonite.util`). You just need to add `scala.`, like
```scala
@ scala.util.Properties.versionString
res0: String = "version 2.13.2"
```

**Comment by JWDobken** [comment]
Gotcha! Thanks Alexandre.

Coming from a Python background, these tools, including the Almond kernel are a great learning experience.
