### ISSUE TITLE
Corrections to libraryDependencies incantation

### ISSUE THREAD

**Issue by mslinn** [lihaoyi/Ammonite#113]
The project I work with the most is a stuck with Scala 2.10 for the foreseeable future. 

1. I  could not find v0.3.1 for use with Scala 2.10, so I used v0.3.0 instead. The changelog led me to believe that v0.3.1 was available for Scala 2.10. Perhaps I read it wrong?
1. I don't know if this is different for Scala 2.11 projects: when adding to the `libraryDependencies` I found that two percents (`%%`) were required, instead of the single percent shown in the docs. This is what worked for me for Scala 2.10:

````
"com.lihaoyi" %% "ammonite-repl" % "0.3.0" % "test" cross CrossVersion.full
````

It would be great if Ammonite could be cross-published for Scala 2.10 and 2.11 once again.

**Comment by lihaoyi** [comment]
Ok

**Comment by lihaoyi** [comment]
I've got 2.10 working in trunk, will go out next release

**Comment by mslinn** [comment]
Do not forget to correct the docs. libraryDependencies needs "%%" instead of "%".

**Comment by lihaoyi** [comment]
Yes well that's because you're using 0.3.0 and not 0.3.2

**Comment by lihaoyi** [comment]
Hmm I might be mistaken, lemme dig a bit deeper

**Comment by lihaoyi** [comment]
Both incantation seem to work for me, with `%` or `%%`. Maybe `cross` just stomps over everything
