### ISSUE TITLE
Unable to see main method docs now with `mainargs`

### ISSUE THREAD

**Issue by ckipp01** [lihaoyi/Ammonite#1136]
Before the recent changes of adding in `mainargs` to Ammonite, one could use the `@doc` annotation to annotate their main methods. For example, given the following:

```scala
// ammonite-test.sc
@doc("This is the first doc")
@main
def one() = println("one")

@doc("This is the second doc")
@main
def two() = println("two")
```
```
❯ cs launch com.lihaoyi:ammonite_2.13.3:2.2.0 -M ammonite.Main -- ammonite-test.sc
Need to specify a subcommand to call when running ammonite-test.sc

Available subcommands:

  one
  This is the first doc

  two
  This is the second doc
```
This was quite nice. At work we have some pretty large scripts to handle various things with at times 6 different `@main`s. All of them have `@doc` since it was a built-in way to get this information to the user.

Now update the snippet with the new syntax and run it:

```scala
// ammonite-test2.sc
@arg(doc = "This is the first doc")
@main
def one() = println("one")

@arg(doc = "This is the second doc")
@main
def two() = println("two")
```

```
❯ cs launch com.lihaoyi:ammonite_2.13.3:2.3.8 -M ammonite.Main -- ammonite-test2.sc
Need to specify a sub command: one, two
```

Even using the help command now just displays the subcommands and ignores the docs:

```
❯ amm ammonite-test2.sc --help
Available subcommands:

  one

  two
```

As far as I can tell playing around, there seems to be no way to get the top level `@arg(doc = "hi")` to show like it used to? Am I maybe misunderstanding how to use it? From a UX point of view, if this is the case it's a pretty large regression for users since they can no longer rely on the feature to document their main methods.

**Comment by lihaoyi** [comment]
Probably a regression in the move to https://github.com/lihaoyi/mainargs; feel free to send a PR to that repo if you're in a hurry to get this working! The code there should be relatively simple, and I can help cut a new release and start using it in Ammonite

**Comment by ckipp01** [comment]
Actually, looking at the code of `mainargs` made me realize that instead of having:

```scala
@arg(doc = "This is the second doc")
@main
def two() = println("two")
```

You can just do:

```scala
@main(doc = "This is the first doc")
def one() = println("one")
```
And then you get the output I was expected. I actually like this better as it's more concise. I think this is a totally valid workaround. Thanks!
