### ISSUE TITLE
Repl.run: Add `postdef` argument

### ISSUE THREAD

**Issue by sirthias** [lihaoyi/Ammonite#121]
I'm using ammonite-repl in a project, which talks to a serial adapter over a native library.
Everything runs smoothly, however there is one thing I'd like to get rid of:
Having to manually clean up at the end of my session, which is tedious and easy to forget.

It'd be great if the `Repl.run(...)` had a `postdef` argument in addition to `predef`, which allowed me to automatically run a few commands upon having pressed Ctrl-D to exit the session.

**Comment by lihaoyi** [comment]
Seems reasonable. To be clear, this is to clean up when you exit the ammonite-repl, *not* when you exit the JVM right?

**Comment by lihaoyi** [comment]
Here's another question: are you calling this programmatically? If you're calling `Repl.run` programmatically then it seems you could just... add additional code after the `Repl.run` call =P 

The other case, which is to run stuff upon exiting the JVM, you can already accomplish via shutdown hooks e.g. http://stackoverflow.com/questions/2921945/useful-example-of-a-shutdown-hook-in-java

**Comment by sirthias** [comment]
I want to run commands when I exit the REPL, not the JVM.
I know I can run stuff after ammonite-repl has exited, yes. I already do this and call `sys.exit` to immediately exit the standard SBT console after the ammonite-repl session has finished.
However, in my cleanup code I need access to the definitions I create in `predef` for the ammonite-repl,
so the cleanup code needs to run in the same scope rather than in an enclosing one.

**Comment by lihaoyi** [comment]
> However, in my cleanup code I need access to the definitions I create in predef for the ammonite-repl,
so the cleanup code needs to run in the same scope rather than in an enclosing one.

Ok makes sense

**Comment by sirthias** [comment]
Great!
By the way: Thanks for some great tools!
Ammonite is not the only awesome thing that you've built!

**Comment by lihaoyi** [comment]
Closing as wishlist; if anyone wants to implement this that'd be great. Otherwise I probably won't get to it

**Comment by joprice** [comment]
I just found myself wishing I had this after starting an http client, then hitting ctrl+d, and waiting a bit until I realized it was hanging. It would be nice to have something like sbt's `cleanupCommands`.

**Comment by emanresusername** [comment]
@lihaoyi i'm willing to take a whack at this (assuming the barrier to entry isn't too high), any pointers on where to start?

**Comment by lihaoyi** [comment]
Yeah this should be one of the most straightforward issues ever to implement 😛 

Starting points:

- Look at `InterpAPI` and `ReplAPI` to see where the list of `interp.*` or `repl.*` things is *defined*

- Skim through `Interpreter` and `Repl` to see where `InterpAPI` and `ReplAPI` get *implemented*

- Start from `Main`, go down the callstack and figure out where you want to run the cleanup code in the life-cycle of an interpreter or REPL (probably somewhere in `Interpreter` and `Repl`, but starting from `Main` it'll be easier to see where the entry- and thus exit-points of Ammonite are)

- Add your `postDef` definition to `InterpAPI` or `ReplAPI`, add your implementation to `Interpreter` or `Repl`, and do the necessary plumbing to link the the two together and call it from where-ever you want it to be called

**Comment by emanresusername** [comment]
Just revisited this with fresh eyes
```scala
sys.addShutdownHook { println("this is way simpler") }
```
Not sure how i didn't get to that solution the first time around 😅  ![noidea](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/noidea-1417756770.png)

**Comment by lihaoyi** [comment]
Fixed by #581
