### ISSUE TITLE
Command to run other executable

### ISSUE THREAD

**Issue by reyman** [lihaoyi/Ammonite#13]
Hi,

I search in the doc, but i doesn't find a way to run extern command like this : 

1) Search all svg class (that it's ok :) )

 `val results = (ls! wd |? (_.ext == "svg"))`

2) Use command on each result from results list, something like this :

`(0 until results).map{ r => inkscape -z -D --file=$r --export-pdf=$r --export-latex}`

Best regards
Sr.

**Comment by lihaoyi** [comment]
Try using Scala's own

```scala
(0 until results).map{ r => "inkscape -z -D --file=$r --export-pdf=$r --export-latex".!!}
```

Or ammonite's experimental, not-documented 

```scala
(0 until results).map{ r => %inkscape("-z", "-D", "--file=$r", "--export-pdf=$r", "--export-latex") }
```
