### ISSUE TITLE
`%` should support commands containing '-'

### ISSUE THREAD

**Issue by laci37** [lihaoyi/Ammonite#137]
I can't run `apt-get`.

**Comment by lihaoyi** [comment]
A workaround would be to run 

```
%`apt-get`
```

Which should work (I haven't tried =P). This of course needs to be documented

**Comment by lihaoyi** [comment]
Fixed by https://github.com/lihaoyi/Ammonite/commit/0ff28c78212469fc411536afb895f77e3ad5f4d1
