### ISSUE TITLE
Can't fix typos?

### ISSUE THREAD

**Issue by rparree** [lihaoyi/Ammonite#139]
Hi,

This looks most likely like some environment problem, but when i made a typo:

```scala
@ class Foo {
    val v = "
  }
SyntaxError: found "\n}", expected "\"" | StringChars | Interp | LiteralSlash | Escape | NonStringEnd in
  val v = "

```

I can't go up and fix it. When i go up, the last successful command in my history shows up. I was surprised not to find an issue, so assume it is a problem on my end. I am running Ubuntu 15.04

Note: when installing using curl, i got an error saying `/home/me/.ammonite/predef.scala` did not exist. I created an empty file and that made it run. Not sure if related.

**Comment by lihaoyi** [comment]
The curl problem was me botching the release process; i just released 0.4.1
and it should work now (lol)

The inability to fix typos is different, and I kinda know what's causing
it. Want to open an issue on github? I'll bundle it with the next round of
fixes

**Comment by rparree** [comment]
Ok, just mentioned it as it might have been related.

Not sure what you mean when you wrote:

>  " Want to open an issue on github?" 

Is this #139 not an issue? Sorry if i misunderstood.

**Comment by lihaoyi** [comment]
> Is this #139 not an issue? Sorry if i misunderstood.

Oops, it was I who misunderstood. I saw it in my email and thought it was an email. This is fine =D

**Comment by rparree** [comment]
you are fast ;) Downloaded the 0.4.2 release from github and i am able to go up and edit a typo.

**Comment by lihaoyi** [comment]
=)
