### ISSUE TITLE
ammonite crashes on any input

### ISSUE THREAD

**Issue by bretthoerner** [lihaoyi/Ammonite#143]
`ammonite 0.4.2`

I did the `curl` install from the website. Regardless of what I do I get the following.

```
$ amm 
Loading Ammonite Repl...
@ 1
stty: standard input: unable to perform all requested operations
Exception in thread "main" java.lang.RuntimeException: Nonzero exit value: 1
	at scala.sys.package$.error(package.scala:27)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
	at ammonite.terminal.TTY$.stty(Utils.scala:97)
	at ammonite.terminal.TermCore$.readLine(TermCore.scala:216)
	at ammonite.repl.frontend.FrontEnd$Ammonite$.readLine(FrontEnd.scala:148)
	at ammonite.repl.frontend.FrontEnd$Ammonite$.action(FrontEnd.scala:63)
	at ammonite.repl.Repl.action(Repl.scala:44)
	at ammonite.repl.Repl.loop$1(Repl.scala:68)
	at ammonite.repl.Repl.run(Repl.scala:82)
	at ammonite.repl.Repl$.run(Repl.scala:146)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:130)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:130)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:130)
	at ammonite.repl.Repl.main(Repl.scala)
```

Thanks!

**Comment by lihaoyi** [comment]
Thanks for the report!

What operating system are you using? What terminal? What version of each? What version of Java?

**Comment by bretthoerner** [comment]
OS X 10.10.4
GNU bash, version 4.3.39(1)-release (x86_64-apple-darwin14.4.0)
java version "1.7.0_71"
Terminal.app 2.5.3 (343.7)

**Comment by lihaoyi** [comment]
Could you try running
```bash
$ bash -c "stty -g < /dev/tty"
```

And then taking the output and pasting it back in in place of the `-g`, e.g. in my case it looks like

```bash
haoyi-mbp:citools haoyi$ bash -c "stty -g < /dev/tty"
gfmt1:cflag=4b00:iflag=2b02:lflag=200005cf:oflag=3:discard=f:dsusp=ff:eof=4:eol=ff:eol2=ff:erase=7f:intr=3:kill=15:lnext=16:min=1:quit=1c:reprint=12:start=11:status=14:stop=13:susp=1a:time=0:werase=17:ispeed=38400:ospeed=38400
haoyi-mbp:citools haoyi$ bash -c "stty gfmt1:cflag=4b00:iflag=2b02:lflag=200005cf:oflag=3:discard=f:dsusp=ff:eof=4:eol=ff:eol2=ff:erase=7f:intr=3:kill=15:lnext=16:min=1:quit=1c:reprint=12:start=11:status=14:stop=13:susp=1a:time=0:werase=17:ispeed=38400:ospeed=38400 < /dev/tty"
haoyi-mbp:citools haoyi$
```

**Comment by bretthoerner** [comment]
```
moose:~$ bash -c "stty -g < /dev/tty"
6b02:3:4b00:2000058b:4:ff:ff:7f:17:15:12:ff:3:1c:1a:19:11:13:16:f:1:0:14:ff
moose:~$ bash -c "stty 6b02:3:4b00:2000058b:4:ff:ff:7f:17:15:12:ff:3:1c:1a:19:11:13:16:f:1:0:14:ff < /dev/tty"
moose:~$
```

**Comment by lihaoyi** [comment]
Odd, it looks very different from mine =/ and it's not blowing up like it should given the stack trace you posted... 

If you're willing you can clone the repo and hit `repl/run` and see if it blows up similarly, I'd want to instrument https://github.com/lihaoyi/Ammonite/blob/master/terminal/src/main/scala/ammonite/terminal/Utils.scala#L95-L98 to see what sequence of inputs is causing it to blow up.

If not, you can turn off the custom terminal implementation by putting

```scala
repl.frontEnd() = ammonite.repl.frontend.FrontEnd.JLineUnix
```

Into your `~/.ammonite/predef.scala`, and settle for a slightly degraded (no input syntax highlighting, no multiline editing) experience

**Comment by bretthoerner** [comment]
Thanks, I'll check it out! :)

**Comment by lihaoyi** [comment]
Closing for now...

**Comment by matthewpflueger** [comment]
Hmmm I am getting this same exact issue.  Running bash -c "stty -g < /dev/tty" gives me similar values as bretthoerner:

6b02:3:4b00:200005cb:4:ff:ff:7f:17:15:12:ff:3:1c:1a:19:11:13:16:f:1:0:14:ff

So I figured I was doing something questionable in my ~/.bash_profile and I was right.  This line turned out to be the culprit:

export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"

Obviously coreutils is not playing nicely with the shell...

**Comment by lihaoyi** [comment]
@matthewpflueger want to fork ammonite and see if you can fix it? =D The stack trace should tell you where to look

**Comment by matthewpflueger** [comment]
I will give it a shot...

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/Ammonite/pull/269
