### ISSUE TITLE
Support compiler plugins

### ISSUE THREAD

**Issue by non** [lihaoyi/Ammonite#145]
Would it be possible to load compiler plugins, similarly to how libraries can be loaded?

Since Ammonite already supports restarting the compiler (in the case of a crash) it might be possible to do the same thing to load a compiler plugin.

**Comment by alexarchambault** [comment]
This can definitely be done, I'm already doing it [here](https://github.com/alexarchambault/ammonite-shell/blob/master/interpreter/src/main/scala/ammonite/interpreter/Compiler.scala#L165) (illustrated with [simulacrum](https://github.com/alexarchambault/jupyter-scala/blob/master/examples/libraries/Simulacrum.ipynb)).

**Comment by non** [comment]
Interesting. Do you see yourself continuing to keep Ammonite-Shell in sync with Ammonite. Is it possible @lihaoyi would accept your changes upstream?

**Comment by alexarchambault** [comment]
I plan to update it this month. I wouldn't be against some of its features landing here, the main ones being class wrapper based repl, and cleaner class loader. @lihaoyi wasn't too interested last time I asked.

**Comment by lihaoyi** [comment]
Adding compiler plugins would be really easy AFAIK; anyone want to take a shot at implementing it? We can already reload the compiler completely transparently, so it's just a matter of making a new one with some new plugins or options

> @lihaoyi wasn't too interested last time I asked.

That's not an accurate assessment, I just wanted a clear explanation of what the features were for, and some unit tests to demonstrate their usage, and then you got bored and left to do your own thing =P

I'm open to all of these features, but surely I can be excused for wanting some kind of discussion/understanding/testing before accepting a moderately-large diff..

**Comment by alexarchambault** [comment]
@lihaoyi There were things in my devs that were not clear enough to me at the time. I needed to try more things, out of a PR / reviewing frame, before having something more satisfactory. (Sorry if it felt harsh :-| )

I'm giving the compiler plugin - in this repo - a try (if nobody's already on it?).

**Comment by lihaoyi** [comment]
No offense taken; go for it =D
