### ISSUE TITLE
load.ivy should fail more helpfully in the absence of artifact dependencies.

### ISSUE THREAD

**Issue by mrmechko** [lihaoyi/Ammonite#151]
Failure is acceptable from time to time, particularly if caused by someone who didn't quite read the docs, but it should make us better as programmers and as people.  Late night grandiloqence aside, we should be getting helpful error messages when certain activities, such as `ivy.load`, fail.  This issue distills the problem encountered in #150.

In particular, **Ammonite should return detailed explanation of why `ivy.load` failed regardless of whether or not `verbose = true` is specified, and do so every time it runs**

What ensues is an description of the current behavior:

_Currently, it is explicitly stated that Ammonite only loads from Maven Central, so this issue does not address tactics on loading the offending snapshot dependencies._

**On the first attempt** to load an maven artifact with snapshot dependencies, and only if verbose output is requested, we get a full description of why things went wrong:

```sbt
:: problems summary ::
:::: WARNINGS
		module not found: com.github.mrmechko#swordnet_2.11;2.0-SNAPSHOT

	==== central: tried

	  http://repo1.maven.org/maven2/com/github/mrmechko/swordnet_2.11/2.0-SNAPSHOT/swordnet_2.11-2.0-SNAPSHOT.pom

	  -- artifact com.github.mrmechko#swordnet_2.11;2.0-SNAPSHOT!swordnet_2.11.jar:

	  http://repo1.maven.org/maven2/com/github/mrmechko/swordnet_2.11/2.0-SNAPSHOT/swordnet_2.11-2.0-SNAPSHOT.jar
```

**However** further attempts to load the offending library result in a rather uninformatively broad error:

```sbt
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
	scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
	scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
	scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
	scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
	scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
	scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
	ammonite.repl.interp.Compiler$$anon$4.<init>(Compiler.scala:142)
	ammonite.repl.interp.Compiler$.apply(Compiler.scala:120)
	ammonite.repl.interp.Interpreter.init(Interpreter.scala:225)
	ammonite.repl.interp.Interpreter$$anon$1$load$.ivy(Interpreter.scala:160)
	cmd1$$anonfun$1.apply$mcV$sp(Main.scala:48)
	cmd1$.<init>(Main.scala:49)
	cmd1$.<clinit>(Main.scala:-1)
```

**and in some hard to replicate cases** no error at all:

```sbt
Loading Ammonite Repl...
@ load.ivy("com.github.mrmechko" %% "strips2" % "0.0.3", true)

@ import strips._
Compilation Failed
Main.scala:51: not found: value strips
        import strips._
               ^
@
```

Ideally, the output should include whether or not the artifact was successfully loaded from Maven and in the case of failure, why it wasn't.

**Comment by mrmechko** [comment]
PS, I think the bulk of the work for this is between lines 108 and 109 of [IvyThing.scala](https://github.com/lihaoyi/Ammonite/blob/fc72fec37cd57e911402f00bd3813dcec6e660db/repl/src/main/scala/ammonite/repl/IvyThing.scala)

As I understand it, the type of `report` is `ResolveReport` ([source](https://svn.apache.org/repos/asf/ant/ivy/core/trunk/src/java/org/apache/ivy/core/report/ResolveReport.java)) and has a method `getUnresolvedDependencies()`

**Comment by mrmechko** [comment]
Made it a little better. Artifacts are no longer added to the cache if their dependencies aren't resolved.  Also, you're notified of successes and failures. Pull request incoming.

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/Ammonite/commit/9103e0a6f4600c9bfe634c807ba930d638ad7c29
