### ISSUE TITLE
An alternate FrontEnd using Lanterna to draw to the terminal

### ISSUE THREAD

**Issue by non** [lihaoyi/Ammonite#155]
I think this might be a good alternate rendering system for Ammonite:

https://github.com/mabe02/lanterna

**Comment by lihaoyi** [comment]
This would be great =D It can easily be done as a third party library using `load.ivy` and then activated using `frontEnd() = ...`. I probably won't work on it, having struggled a bit with Lanterna before, but I'm open to someone else doing it and seeing how it goes.

**Comment by photex** [comment]
Could/Would this enable Ammonite-Shell on windows?

**Comment by lihaoyi** [comment]
You can already use ammonite without the custom frontend, just using JLine. I dont know Lanterna enough to say how useful it would be

**Comment by photex** [comment]
But that's working as a shell replacement? I use Windows about half the time and was excited to run it under ConsoleZ only to get an error about there not being a /dev/tty

**Comment by lihaoyi** [comment]
Not sure, you'll have to try it out and let the people on https://github.com/lihaoyi/Ammonite/issues/119 know!

**Comment by lihaoyi** [comment]
Closing as Wishlist for now
