### ISSUE TITLE
Incorrect behaviour if `.type` used

### ISSUE THREAD

**Issue by hgiddens** [lihaoyi/Ammonite#159]
Scala's REPL:

    scala> val x = "1"
    x: String = 1
    
    scala> val t: x.type = x
    xt: x.type = 1

If I try this in Ammonite, it adds another `.type` for some reason (I only entered it once) and then freaks out:

    @ val x = "1"
    x: String = "1"
    @ val t: x.type.type = x
    Compilation Failed
    Main.scala:52: type mismatch;
     found   : String
     required: cmd0.x.type
    }.apply
      ^

**Comment by lihaoyi** [comment]
Didn't work

**Comment by lihaoyi** [comment]
Should be fixed
