### ISSUE TITLE
Readline next/previous line bindings (ctrl-n/p) don't work

### ISSUE THREAD

**Issue by hgiddens** [lihaoyi/Ammonite#160]
They are instead inserting literal control characters (`\u000e` and `\u0010`, respectively).

Reproduced in Terminal.app, iTerm.app, xterm, with `TERM` set to `xterm` and `xterm-256color`.

**Comment by lihaoyi** [comment]
This should have gotten fixed by https://github.com/lihaoyi/Ammonite/pull/153 in the latest 0.4.4 release; can you confirm whether the problem still exists?

**Comment by hgiddens** [comment]
Argh damn, I hadn't refreshed the page so I just re-used the old download link. You're right, this is fixed in 0.4.4.

**Comment by hgiddens** [comment]
Thanks!
