### ISSUE TITLE
Port :power mode from the Scala REPL to Ammonite

### ISSUE THREAD

**Issue by non** [lihaoyi/Ammonite#167]
Pretty much what it sounds like. `:power` is really useful when hacking on Scala itself, or learning more about how the compiler works.

**Comment by lihaoyi** [comment]
This was discussed previously, long ago https://github.com/lihaoyi/Ammonite/issues/25.

My conclusion at the time was:

- We have a nice module system, so not everything needs to live in the core =)
- It is now easily doable as a jar; Ammonite exposes the compiler in http://lihaoyi.github.io/Ammonite/#Builtins, and you should be able to do whatever you want with it
- The target market is sufficiently small that it's not useful in the general case
- This basically isn't specced out at all

Happy to keep talking, but hopefully someone else will go do this and I can just link to their module from my docs =D
