### ISSUE TITLE
Completion output should read sorted by column

### ISSUE THREAD

**Issue by non** [lihaoyi/Ammonite#169]
Currently, tab completion output looks like this:

```
!=                       &                        *
+                        -                        --
/                        ==                       \
abs                      asInstanceOf             bottom
combine                  contains                 crosses
crossesZero              dist                     doesNotContain
equals                   fold                     foldOver
getClass                 hasAbove                 hasAtOrAbove
hasAtOrBelow             hasBelow                 hashCode
intersect                intersects               isAt
isBounded                isEmpty                  isInstanceOf
isPoint                  isProperSubsetOf         ...
```

This ends up being a lot harder to read than sorting by columns instead (i.e. where `asInstanceOf` is displayed on the line below `abs`).

**Comment by lihaoyi** [comment]
Seems reasonable. Should be a pretty easy change [here](https://github.com/lihaoyi/Ammonite/blob/master/repl/src/main/scala/ammonite/repl/frontend/FrontEnd.scala#L40-L48) if anyone wants to pick it up

**Comment by ssanj** [comment]
[I've added some code to a Gist](https://gist.github.com/ssanj/a069fe662618c3eadf3d) which solves this issue. Feel free to use it if you think it's appropriate.

**Comment by lihaoyi** [comment]
This is fixed in master

**Comment by ssanj** [comment]
Awesome! 😊
