### ISSUE TITLE
On an empty line, tab should probably indent not complete

### ISSUE THREAD

**Issue by non** [lihaoyi/Ammonite#170]
At a minimum, this should be true for multi-line inputs. Currently, you have to repeatedly hit space in order to correctly indent multi-line code.

**Comment by lihaoyi** [comment]
Seems reasonable. I doubt the "show all 600 things in scope" behavior we have now is that useful at all

**Comment by lihaoyi** [comment]
Closing in favor of https://github.com/lihaoyi/Ammonite/issues/275
