### ISSUE TITLE
add sbt-native-packager

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/Ammonite#171]
[sbt-packager](https://github.com/sbt/sbt-native-packager) will be nice, it will allow to install ammonite console as an app to different platforms

**Comment by lihaoyi** [comment]
What's the advantage of installing it as an app, over just curling it? Honest question, not trying to be snarky

**Comment by antonkulaga** [comment]
After curling I have to add it to my PATH (after having to do it all I really hate this simple procedure) to use it on a regular bases insted os scala repl. while after installation (for instance by downloading .deb package or producting it by sbt task) sets PATH for me.

**Comment by lihaoyi** [comment]
@antonkulaga Feel free to grab it

**Comment by swhgoon** [comment]
:+1:  deb and then PPA :)

**Comment by lihaoyi** [comment]
Closing was wishlist; if anyone wants to do it then great. Otherwise I probably won't get to it
