### ISSUE TITLE
Add support for compiler flags

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#174]
We can already live-load compiler plugins into the REPL at runtime, adding support for compiler flags is easy in comparison (e.g. https://github.com/lihaoyi/Ammonite/issues/40)

**Comment by abelbryo** [comment]
Hi,
`-Ywarn-value-discard` flag doesn't seem to work.
```
λ compiler.settings.warnValueDiscard.value = true

λ def foo(n: Int): Unit = n * 2
defined function foo
```
Thanks
