### ISSUE TITLE
Changing predef/SBT project doesn't properly invalidate caches

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#177]
I've had problems where I needed to manually remove my ~/.ammonite/cache folder after fiddling with what I passed in to `ammonite.repl.Repl.run(predef="...")`, when using Ammonite integrated into an SBT project. 

It seems we're not using the SBT .class file classpath when computing cache tags, and this can leave the REPL with bad imports after starting: the exact same predef with an `import foo._` results in different sets of imports being added to the REPL depending on what members `foo` contains

**Comment by lihaoyi** [comment]
@laci37 want to take a look at this after you're done with https://github.com/lihaoyi/Ammonite/pull/189?

**Comment by laci37** [comment]
The code only changes the classpath hash if a new jar is added to classpath, so it's quite obvious, that stuff compiled with SBT is not hashed in. I'll take a look.

**Comment by laci37** [comment]
Can you please provide sample code to reproduce the bug?

**Comment by lihaoyi** [comment]
Sure next time I have a computer

**Comment by lihaoyi** [comment]
@laci37 here you go

```scala
haoyi-mbp:demo haoyi$ cat build.sbt
scalaVersion := "2.11.7"
libraryDependencies += "com.lihaoyi" % "ammonite-repl" % "0.4.5" % "test" cross CrossVersion.full

initialCommands in (Test, console) := """ammonite.repl.Repl.run("import demo.Main._")"""
haoyi-mbp:demo haoyi$ cat Main.scala
package demo
object Main{
  def x = 1
}
haoyi-mbp:demo haoyi$ sbt test:console
[info] Loading global plugins from /Users/haoyi/.sbt/0.13/plugins
[info] Loading project definition from /Users/haoyi/Dropbox (Personal)/Workspace/demo/project
[info] Set current project to demo (in build file:/Users/haoyi/Dropbox%20(Personal)/Workspace/demo/)
[info] Compiling 1 Scala source to /Users/haoyi/Dropbox (Personal)/Workspace/demo/target/scala-2.11/classes...
[info] Starting scala interpreter...
[info]
Loading...
Welcome to the Ammonite Repl 0.4.5
(Scala version 2.11.7 Java 1.8.0_25)
demo@ 1
res0: Int = 1
demo@ Bye!
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_25).
Type in expressions to have them evaluated.
Type :help for more information.

scala>
[success] Total time: 13 s, completed Aug 23, 2015 5:16:09 PM
haoyi-mbp:demo haoyi$ vim Main.scala
haoyi-mbp:demo haoyi$ cat Main.scala
package demo
object Main{
}
haoyi-mbp:demo haoyi$ sbt test:console
[info] Loading global plugins from /Users/haoyi/.sbt/0.13/plugins
[info] Loading project definition from /Users/haoyi/Dropbox (Personal)/Workspace/demo/project
[info] Set current project to demo (in build file:/Users/haoyi/Dropbox%20(Personal)/Workspace/demo/)
[info] Compiling 1 Scala source to /Users/haoyi/Dropbox (Personal)/Workspace/demo/target/scala-2.11/classes...
[info] Starting scala interpreter...
[info]
Loading...
Welcome to the Ammonite Repl 0.4.5
(Scala version 2.11.7 Java 1.8.0_25)
demo@ 1
Compilation Failed
Main.scala:89: value x is not a member of object demo.Main
import demo.Main.{
       ^
demo@
```

**Comment by laci37** [comment]
I added a hash of the classpath to cachetags, but it didn't fix the problem. The actual problem here is that it tries to import `x` from object `Main` but it's not there in the modified code, so the problem is somewhere else.

**Comment by lihaoyi** [comment]
This should get fixed by https://github.com/lihaoyi/Ammonite/commit/df48958efdecb1fe58a317b71dbcee06eb380505. @laci37 looks like your original change was hashing the directories listed as part of the classpath, which just gives you the hash of the file-list but *not* the hash of the files inside it! This change makes it walk over all the files to try and discover classfiles, and just mtimes rather than hashes them (for speed). Testing it by adding/removing members in `integration.Main` shows it recompiling/not as required.
