### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by pocorall** [lihaoyi/Ammonite#18]
When I run Ammonite on Windows, I got this exception:

```
Caused by: java.lang.IllegalArgumentException: requirement failed: Absolute Paths must start with /
	at scala.Predef$.require(Predef.scala:219)
	at ammonite.ops.Path$.apply(Path.scala:202)
	at ammonite.Bundle$class.$init$(Bundles.scala:37)
	at ammonite.all$.<init>(Bundles.scala:11)
	at ammonite.all$.<clinit>(Bundles.scala)
```

Mainly because of this

    val home = Path(System.getProperty("user.home"))

`System.getProperty("user.home")` returns something like `c:\Users\pocorall` in Windows.

**Comment by Kwestor** [comment]
https://github.com/lihaoyi/Ammonite/blob/master/core/src/main/scala/ammonite/ops/Path.scala#L213 here, `"/"` should be changed to File.separator`. Same with all other `/` in strings, it should be easy to implement.

**Comment by lihaoyi** [comment]
Yeah if anyone wants to send a PR making it work that'd be great.

**Comment by Kwestor** [comment]
I plan to showcase Ammonite in my company so I could probably do it then. In 2-3 weeks I think.

**Comment by NickPollard** [comment]
Checking for file-seperator is not the right way to do that; on Windows paths don't start with a separator, and more generally, that's an implementation detail of the file system you shouldn't be relying on.

It would be much better to simply ask the file system if it's an absolute path or not, or just ask the filesystem to give you the corresponding absolute path to the path you're holding. This is what the existing Java fs libraries do.

**Comment by OlegYch** [comment]
%(

**Comment by lihaoyi** [comment]
Windows paths are actually pretty different, since they include the drive and other rubbish in them. How does that jive with `class Path(segments: Seq[String])` definition that Ammonite uses? Can we just make the `C:` or `D:` or whatever be the first segment, or is it more subtle than that?

**Comment by MaggieLeber** [comment]
Might want to warn folks about this in the docs until it's fixed.

**Comment by Kwestor** [comment]
Unfortunately to support different file schema whole `Path.scala` should be refactored.

**Comment by lihaoyi** [comment]
@MaggieLeber I've added a note in the readme saying no Windows, and only Java >=7.

@Kwestor How exactly should it be refactored? At the core `Path.scala` is just

```scala
case class Path(segments: Seq[String])
```

How exactly will this differ on windows?

FWIW I don't have a windows machine handy to test/dev this stuff, so someone else who cares about this is going to have to make this happen and maintain it, though I'll happily work with whoever.

**Comment by felixbr** [comment]
I think the path representation should work for windows as well.

    c:\Users\name

can be represented as

    Seq("c:", "Users", "name")

@Kwestor Are you working on a refactoring right now? If not, I'd give it a shot myself.

**Comment by Kwestor** [comment]
Feel free to give it a shot, I don't have time for it right now.

--
Jerzy

**Comment by antonkulaga** [comment]
I also do not have time for it right now, but I want to emphasize that nowindows support blocks ammonite adoption inside many opensource lbis (incl. sbt plugins) as it breaks the project for windows users.
Is the problem only in slashes? (I do not use windows to check it)

**Comment by Kwestor** [comment]
Problem is with implementation of `Path`, it assumes path is `segments.mkString("/", "/", "")` and have no easy way to add a drive letter.

**Comment by lihaoyi** [comment]
Ammonite-Ops now works on windows naively. It's pretty dumb: it basically treats all absolute paths as relative to the current root drive, and provides no way for you specify otherwise. The bulk of tests pass on windows (running manually in my VM; we have no CI)

This is clearly incorrect, but I bet will cover 95% of the use case. Will open separate issues for the remaining details

**Comment by lihaoyi** [comment]
FTR https://github.com/lihaoyi/Ammonite/commit/916597d0dd83416754d23e73a8ca67fedf2b17c5
