### ISSUE TITLE
Constructor parameters are not tab-completed for case classes

### ISSUE THREAD

**Issue by ssanj** [lihaoyi/Ammonite#183]
As a simple example try tab-completing the constructor to scala.util.Success in Ammonite:

```scala
scala.util.Success.apply <tab>
```

There is no completion.

In the scala REPL you get:

```scala
scala> scala.util.Success.apply <tab><tab>
   def apply[T](value: T): Success[T]
```

unapply in the REPL:

```scala
scala> scala.util.Success.unapply <tab><tab>
   def unapply[T](Success[T]): Option[T]
```

It would be great to have this feature in Ammonite.

**Comment by lihaoyi** [comment]
Closing in favor of https://github.com/lihaoyi/Ammonite/issues/275
