### ISSUE TITLE
Tests use sources as test data?

### ISSUE THREAD

**Issue by Blaisorblade** [lihaoyi/Ammonite#191]
To generate Eclipse projects for Ammonite, I'm using sbteclipse with a special setup, so that Eclipse writes its class files in `bin/` instead of overwriting SBT's output — that's even the default since release 4.0.0 of sbteclipse. However, that makes [a test](https://github.com/lihaoyi/Ammonite/blob/e8454a7b5bc68d43a6f8feb0da9cae24d5ec9bbd/repl/src/test/scala/ammonite/repl/session/AdvancedTests.scala#L48-L60) fail, because it does not expect `ops/bin` to exist.

```
@ import ammonite.ops._
import ammonite.ops._
@ ls! wd/'ops
res1: LsSeq = LsSeq(
  'bin,
  'src,
  'target
)
@ %%ls 'ops
res2: CommandResult =
bin
src
target
```

**Comment by lihaoyi** [comment]
Yes, that's how the test works now. Want to fix it by changing the `ls` to a different folder? Shouldn't be so hard.

**Comment by lihaoyi** [comment]
I'm not going to fix this, but feel free to send a PR
