### ISSUE TITLE
`ls!` does not sort output on Linux (unlike expected by tests)

### ISSUE THREAD

**Issue by Blaisorblade** [lihaoyi/Ammonite#192]
On Linux, [a test](https://github.com/lihaoyi/Ammonite/blob/e8454a7b5bc68d43a6f8feb0da9cae24d5ec9bbd/repl/src/test/scala/ammonite/repl/session/AdvancedTests.scala#L48-L60) (the same I mentioned in #191) fails because the output of `ls!` is not sorted like the test expects. If the test is correct, this seems an actual bug.
```
@ import ammonite.ops._
import ammonite.ops._
@ ls! wd/'ops
res1: LsSeq = LsSeq(
  'target,
  'src
)
@ %%ls 'ops
res2: CommandResult =
src
target
```

**Comment by lihaoyi** [comment]
That's odd; all our tests run on linux in travis-ci; how is it not blowing up?

**Comment by Blaisorblade** [comment]
Assuming `ls!` does not sort the output, I'd guess it reads entries according to the order on disk. That order can be deterministic, depending on the order the entries are created and the filesystem. On traditional filesystems (OS X's HFS+, ext2, maybe ext3), IIRC, the on-disk order is the order the entries are created (here, first `src`, then `target`), but the box on which I'm observing the bug uses ext4, a B-tree filesystem.

**Comment by Blaisorblade** [comment]
I read the source code. This boils down to DirectoryStream, whose docs explain that "the elements returned by the iterator are in no specific order".

**Comment by lihaoyi** [comment]
This should (?) get fixed by https://github.com/lihaoyi/Ammonite/commit/6f918e07fc5152e4bab4399aed93a9268d18b059
