### ISSUE TITLE
`sbt test` should succeed by itself, as everywhere else

### ISSUE THREAD

**Issue by Blaisorblade** [lihaoyi/Ammonite#195]
6f918e07fc5152e4bab4399aed93a9268d18b059 regresses here:
> Undo hacky `sbt/assembly` call inside the test suite

I'd agree that call is hacky, but I believe the behavior is still important — this caused one of the spurious failures.

A non-hacky way would be a SBT dependency — I'll see if I can code that up.

**Comment by lihaoyi** [comment]
It was causing classfile-out-of-date problems when I was running it locally =/ so flaky with, flaky without.

The problem with a SBT dependency is that it would add the cost of SBT assembly to every test run, even if the test doesn't use the standalone executables. That is slow (1min?) and painful.

A better solution may be to move the `StandaloneTests` into their own SBT subproject; then that subproject's tests can depend on assembly, but the "fast" `repl/test`s don't need to.

**Comment by Blaisorblade** [comment]
All good points. Regarding long tests, I often end up with similar setups, so :+1:

**Comment by lihaoyi** [comment]
This has happened

**Comment by Blaisorblade** [comment]
Ah, in 53d2d24505ab2827dc6a0c3f92cc4c254dca4a77. Thanks!
