### ISSUE TITLE
reverse-i-search not working in Repl

### ISSUE THREAD

**Issue by fsvehla** [lihaoyi/Ammonite#197]
In the SBT repl `CTRL` + `R` searches backwards in the history, for example:

1) Enter Text

```text
scala> val foo = 22
```

2) `CTRL` + `R` + `f` `o` will find and highlight the line, with this output:

```
(reverse-i-search)`fo': val foo = 22
```

3) `RETURN` accepts the choice

**Comment by lihaoyi** [comment]
There's no reason this is missing, just nobody's implemented it yet. However, I am probably not the best person to implement this, as I'm not actually familiar with how this works. If anyone wants to take a crack at it, you can put it in https://github.com/lihaoyi/Ammonite/blob/master/terminal/src/main/scala/ammonite/terminal/ReadlineFilters.scala with the rest of the readline hotkey filters

**Comment by fsvehla** [comment]
Switching the frontend to use JlineUnix works as a workaround, but when I do that, what functionality am I missing?

**Comment by lihaoyi** [comment]
You're missing

- Multiline editing
- Input-syntax-highlighting
- Desktop-style Alt-{left, right} navigation, Shift-selection
- Probably a few other things I don't remember off the top of my head

**Comment by lastland** [comment]
From the code of jline2, how `reverse-i-search` works seems quite simple. It just searches the most recent command that contains the given string. See https://github.com/jline/jline2/blob/8beae1a471aef17e4c721021ea4be3be918da37f/src/main/java/jline/console/ConsoleReader.java#L2844-L2864 and https://github.com/jline/jline2/blob/8beae1a471aef17e4c721021ea4be3be918da37f/src/main/java/jline/console/ConsoleReader.java#L3890-L3930 .

BTW, notice that there are a bunch of searching commands besides `reverse-i-search` in `readline`: http://www.delorie.com/gnu/docs/readline/rlman_15.html
Perhaps we should implement all of them?

**Comment by lihaoyi** [comment]
Fixed in https://github.com/lihaoyi/Ammonite/pull/335
