### ISSUE TITLE
status code and stderr for %%

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/Ammonite#207]
Would be great if %% would return not only the stdout but also stderr and status code. Also, it seems %% is broken in that it terminates commands too early. I tried to use it with tar and ended up with empty or broken archives while % works fine, but writes all output to stdout.

**Comment by lihaoyi** [comment]
Yeah, I haven't figured out how to make `%%` capture those other things, but I'm sure it's possible and I want to do it.

I wonder if the early-termination problem is something to do with not fully consuming the output `Stream` given by `%%` causing the background process to block and not make progress. 

Do you have a nice self-contained repro of the problem I can add to my test suite? That'd make it easier to attack

**Comment by cvogt** [comment]
regarding the api, how giving the return value a lazy member `stderr` for the error stream and a blocking member for the status code. Maybe it would be cleaner to make the stdout a member rather than the return value itself, too, but that may have other api implications I am not aware of. Never used the piping.

**Comment by lihaoyi** [comment]
yeah seems reasonable. Some kind of structured data would be nice. The whole lazy-vs-strict thing is kinda still in flux; right now most things are strict, so we could make this strict as well and figure out how to make lazy things lazy later if we decide we care

**Comment by lihaoyi** [comment]
If we end up with something more flexible to deal with the `stdout` and `stderr` of the subprocess, we should probably support all the "common" redirect operations, e.g. all those here:

http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-3.html

**Comment by cvogt** [comment]
sounds good. structured data for what?

**Comment by lihaoyi** [comment]
Structured data so we can access things like the output stream, error stream, exit code, and other things without having to have 100 different `%%%%%` operators to give us the individual bits we need

**Comment by cvogt** [comment]
agreed

**Comment by lihaoyi** [comment]
Fixed by https://github.com/lihaoyi/Ammonite/commit/5d7fb687a33dff6e64e79d9ea264db8b2c2df6fb, will go out in 0.5.1

**Comment by cvogt** [comment]
awesome :)!
