### ISSUE TITLE
support for ctrl + arrow

### ISSUE THREAD

**Issue by scalway** [lihaoyi/Ammonite#217]
In scala repl it works fine. It is very helpful and I miss that.

**Comment by lihaoyi** [comment]
what does it do?

**Comment by agapep** [comment]
It moves cursor to left/right by exactly one word.

**Comment by falconepl** [comment]
Yup, that's definitely a must-have. Not only Scala REPL supports it. Standard Bash shell handles that shortcut too.

**Comment by lihaoyi** [comment]
I think the reason I missed it is that on OSX it's captured by the OS and doesn't make it to the shell. One of you will have to implement it, check out the `terminal/` subproject to see where the rest of the keyboard commands are =)
