### ISSUE TITLE
show return type when exception is thrown

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/Ammonite#222]
Would be great to see the return type of `x(5)` regardless of the exception.

```scala
@ def x[T](t: T): T = ???
defined function x
@ x(5)
scala.NotImplementedError: an implementation is missing
	scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	cmd8$.x(Main.scala:61)
	cmd9$$anonfun$1.apply$mcI$sp(Main.scala:62)
	cmd9$.<init>(Main.scala:63)
	cmd9$.<clinit>(Main.scala:-1)

```

**Comment by lihaoyi** [comment]
What's the use case of this?

**Comment by cvogt** [comment]
Ammonite can be used for type-inference exploration, but this makes it slightly harder. I was experimenting with some implicits to see how scala would infer things. I didn't implement their bodies, so I got exceptions and didn't see the messages. In this case if would have been nice to see what Scala inferred for `List(1,2,3) * List(2,3,4)`: https://github.com/lihaoyi/Ammonite/issues/221

**Comment by lihaoyi** [comment]
Closing as wishlist because I doubt I'd ever get to it, it would require substantial changes in the synthesized code wrapper, and the savings of 4 characters `()=>` is not sufficient to win me over =P
