### ISSUE TITLE
Ammonite should be interruptible when it is not used interactively

### ISSUE THREAD

**Issue by patrick-premont** [lihaoyi/Ammonite#224]
Ammonite captures control-c and #214 suggests capturing control-z. This is useful when using ammonite interactively as a shell. However this becomes a liability when working non-interactively. 

I am unsure if using --code or passing in a <file> parameter currently disables the capture of control-c. But #223 seems to suggest that control-c is captured even when input is redirected. If that is the desired behavior, perhaps we need a command-line flag to explicitly disable the capture of control-c ?

**Comment by lihaoyi** [comment]
We probably should disable all the signal capturing rubbish when not run interactively, e.g. through running script files or running with `-c`

**Comment by lihaoyi** [comment]
Should be fixed by #242 I think
