### ISSUE TITLE
ammonite-ops_2.11-0.4.7-sources.jar broken

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/Ammonite#227]
ammonite-ops_2.11-0.4.7-sources.jar contains relative paths to surrounding folders. That's invalid and actually crashes Apache VFS (https://issues.apache.org/jira/browse/VFS-219) which in turn crashes ensime-server.

This was introduced between 0.4.6 and 0.4.7, I suppose by this commit: https://github.com/lihaoyi/Ammonite/commit/53d2d24505ab2827dc6a0c3f92cc4c254dca4a77

```
$ unzip -l ./com.lihaoyi/ammonite-ops_2.11/srcs/ammonite-ops_2.11-0.4.7-sources.jar
Archive:  ./com.lihaoyi/ammonite-ops_2.11/srcs/ammonite-ops_2.11-0.4.7-sources.jar
  Length     Date   Time    Name
 --------    ----   ----    ----
      125  09-06-15 09:51   META-INF/MANIFEST.MF
        0  09-06-15 09:51   ../
        0  09-06-15 09:51   ../project/
        0  09-06-15 09:51   ammonite/
        0  09-06-15 09:51   ammonite/ops/
     3461  08-31-15 20:06   ammonite/ops/Extensions.scala
     4083  08-31-15 20:06   ammonite/ops/Model.scala
     1139  08-31-15 20:06   ammonite/ops/package.scala
     7712  08-31-15 20:06   ammonite/ops/Path.scala
    10349  08-31-15 22:16   ammonite/ops/FileOps.scala
     3271  08-28-15 11:26   ammonite/ops/Shellout.scala
       61  09-06-15 09:29   ../project/Constants.scala
 --------                   -------
    30201                   12 files
```

**Comment by lihaoyi** [comment]
@cvogt this issue is going entirely above my head. I have no idea what sources jars are, why apache VFS doesn't like them, or why moving out the unit tests (!) into their own project would change them. Not sure if I can help fix =/

**Comment by cvogt** [comment]
@lihaoyi I can fix it, but I need more info. Why did you move Constants.scala into the project folder?

**Comment by lihaoyi** [comment]
It is used by both the `build.sbt` code to set the `scalaVersion`, as well as the runtime code to print the loading banner & for `load.ivy` with `%%` to work, and integration tests to load the binary for testing. 

I don't know what you mean by "move"; AFAIK it's always been in the project folder

**Comment by cvogt** [comment]
Alright, always been there. Probably the -repl jar always had that problem, but now that the setting `(unmanagedSources in Compile) += baseDirectory.value/".."/"project"/"Constants.scala"` moved to the sharedSettings in 53d2d24, it probably propagated to ammonite. It can probably be considered an sbt bug in the end, that it creates these broken jars instead of crashing or using a default folder merge strategy. The fix is to manually rewrite the location in the jar to one inside using the sbt setting seen in the PR.

**Comment by cvogt** [comment]
accidentally stumbled over it in the sbt docs http://www.scala-sbt.org/0.13/docs/Howto-Package.html#Modify+the+contents+of+the+package

**Comment by cvogt** [comment]
So the above PR fixes the problem. With the patch the jar looks like this:
```
unzip -l local/com.lihaoyi/ammonite-ops_2.11/0.4.7/srcs/ammonite-ops_2.11-sources.jar
Archive:  local/com.lihaoyi/ammonite-ops_2.11/0.4.7/srcs/ammonite-ops_2.11-sources.jar
  Length     Date   Time    Name
 --------    ----   ----    ----
      125  09-13-15 03:09   META-INF/MANIFEST.MF
        0  09-13-15 03:09   ammonite/
        0  09-13-15 03:09   ammonite/ops/
     1139  09-12-15 15:22   ammonite/ops/package.scala
     4083  09-12-15 15:22   ammonite/ops/Model.scala
     3461  09-12-15 15:22   ammonite/ops/Extensions.scala
    10349  09-12-15 15:22   ammonite/ops/FileOps.scala
       61  09-13-15 03:09   Constants.scala
     7712  09-12-15 15:22   ammonite/ops/Path.scala
     3271  09-13-15 03:09   ammonite/ops/Shellout.scala
 --------                   -------
    30201                   10 files
```
