### ISSUE TITLE
ValDef returns misleading error reports in repl

### ISSUE THREAD

**Issue by lastland** [lihaoyi/Ammonite#230]
For example, entering the following code in repl:

    @ val a: Int = "1"

will result in:

    Compilation Failed
    Main.scala:37: type mismatch;
     found   : String
     required: Int
    }.apply
      ^

I believe the problem was caused by the following code fragment: https://github.com/lihaoyi/Ammonite/blob/ecfff6b3dc707658123d506acabfa08c9a3295c9/repl/src/main/scala/ammonite/repl/interp/Preprocessor.scala#L108-L111

**Comment by lihaoyi** [comment]
Yeah, that fragment is to try and move computation out of the static-initializer, because that stuff doesn't get JITed and is thus 10x as slow. We may want to rip it out in exchange for better errors, since the workaround (move the expensive thing into a function) is straightforward

**Comment by lihaoyi** [comment]
This should be gone in 0.5.0 where I reverted the wrapping code. I judge that sacrificing the small amount of perf is probably OK for now, since most "heavy" compute is going to happen in some kind of library or already-defined function.

```scala
Welcome to the Ammonite Repl 0.5.0
(Scala 2.11.7 Java 1.8.0_25)
@ val a: Int = "1"
Compilation Failed
Main.scala:32: type mismatch;
 found   : String("1")
 required: Int
val a: Int = "1"
             ^
@
```
