### ISSUE TITLE
Explicitly specifying cwd does not work as described in the document

### ISSUE THREAD

**Issue by lastland** [lihaoyi/Ammonite#234]
In the [document](http://lihaoyi.github.io/Ammonite/#CurrentWorkingDirectory) it says you can specify current working directory like this:

    %(cwd) ls 

What I've actually got is:

    Welcome to the Ammonite Repl 0.4.7
    (Scala 2.11.7 Java 1.8.0_40)
    @ import ammonite.ops._
    import ammonite.ops._
    @ %(cwd) ls
    Compilation Failed
    Main.scala:93: could not find implicit value for parameter wd: ammonite.ops.Path
    %(cwd) ls
     ^

With implicit `wd` imported, it will be:

    @ import ammonite.ops.ImplicitWd._
    import ammonite.ops.ImplicitWd._
    @ %(cwd) ls
    Compilation Failed
    Main.scala:110: value ls is not a member of Int
    %(cwd) ls
           ^

**Comment by lihaoyi** [comment]
Looks like it rotted because the example wasn't taken from a unit test, shouldn't be too hard to fix it and keep it working in future

**Comment by lastland** [comment]
How do you plan to make it work with features like "invoking with files"? 

`%(cwd/'other) cwd/'something%(args)` or `cwd/'something%(cwd/'other)`? The first one looks quite strange with two `%`s. The latter one looks better, but how do you tell whether `cwd/'other` is the working directory or an argument?

**Comment by lihaoyi** [comment]
Haven't quite figured it out yet; probably will change the syntax in the next major version

**Comment by lihaoyi** [comment]
This will be fixed by (the poorly named commit) https://github.com/lihaoyi/Ammonite/commit/c67d59a2ff14b5526db2f2854025b4428fffbaa0. The "final" syntax will be

```scala
%(cwd/'other, args)
```

**Comment by lastland** [comment]
Thanks for the fix! I see that you can now use `%ls.()(cwd)` to explicitly declare the working directory, but I'm still not sure what it will be like, say, invoking a program from `wd1` at `wd2`?

**Comment by lihaoyi** [comment]
@lastland you'd so something like 

```scala
%.apply(wd1/'program1, args)(wd2)
```

It's kinda annoying you have to do the explicit `.apply` thing, but that's Scala for you.

You could also make `wd2` implicit and it'll get picked up automatically

**Comment by lastland** [comment]
Thanks! I see. :smile: 

Do you think if this usage should be tested or documented as well? I understand that `wd2` can be made implicit (and I like that design very much) but in some cases it may be easier to explicitly specify one.

**Comment by lihaoyi** [comment]
Yeah it should be... I'll go do that now
