### ISSUE TITLE
Gradle support? 

### ISSUE THREAD

**Issue by zxcvbn97** [lihaoyi/Ammonite#237]
Hi there,

Please help supporting this awesome REPL with gradle.
I'm trying to use ammonite with gradle. However, I'm getting error: 

![image](https://cloud.githubusercontent.com/assets/9757976/9967784/5f59a0f2-5e0a-11e5-8249-16411c984c3d.png)

This is my gradle configuration.

apply plugin: 'scala'
repositories {
mavenCentral()
}

dependencies {
   runtime 'com.lihaoyi:ammonite-repl_2.11.7:0.4.7'
}

 task console(type: JavaExec, dependsOn: classes){
   main = 'ammonite.repl.Repl'
    classpath = configurations.runtime + sourceSets.main.output + sourceSets.test.output
}

**Comment by lihaoyi** [comment]
@zxcvbn97 I don't actually know gradle; what does `gradle console -q` do?

**Comment by zxcvbn97** [comment]
`-q` is the quiet mode, it suppresses gradle debug output.

**Comment by raiju** [comment]
@zxcvbn97 Can you try adding `standardInput = System.in` to your console task?

Also, I've been experimenting gradle and JLine a bit, which didn't end very well. Gradle seems to be buffering the input to the task, which means that things like autocomplete, and command history don't really work anymore (if you find a solution to this, I'd be happy to hear about it).

**Comment by lihaoyi** [comment]
I'm going to punt on this and say if someone wants this, they can do it themselves. Ammonite already doesn't really have much SBT support other than generating a file that it runs, or being called in a main method, both of which presumably gradle can do too

**Comment by edio** [comment]
@lihaoyi , is the contract between a build tool and ammonite described somewhere?

I believe, I'm doing in gradle exactly the same thing you're doing for sbt on ammonite home page, but it still fails for me with some tty-related errors.

**Comment by indraniel** [comment]
Perhaps this blog post, [How to add a REPL to your Project, using Ammonite and Gradle](https://projectmaxs.org/flow/posts/2017-09-28-how-to-add-a-repl.html), can serve as inspiration for others in the future.  

The corresponding github project example is: https://github.com/MiniDNS/minidns .
