### ISSUE TITLE
is possible a lazy ls.rec! ???

### ISSUE THREAD

**Issue by cocodrino** [lihaoyi/Ammonite#239]
Hi guys, I've a small question, I'm curious if it's possible use a lazy ls because this 

```scala
ls.rec! root |? filtr1 |! someOutputF 
```
generate me a GC java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by lihaoyi** [comment]
Try `ls.rec!! root`, which should return an iterator

**Comment by hkirk** [comment]
Just for others (beside me) who see this answer. Has been renamed `ls.rec.iter!`
