### ISSUE TITLE
Completion options could take `new` into account and use different colors

### ISSUE THREAD

**Issue by soc** [lihaoyi/Ammonite#243]
The list of available types when tab-completing something like `new foo.<TAB>` could use different colors for:

- types which can be directly newed (concrete classes),
- those which require some implementation (traits, abstract classes),
- and the things which are uninstantiable (objects, packages), but could be used to progress further into the namespace

Maybe even ordering them, or displaying them in different columns would be useful?

**Comment by lihaoyi** [comment]
Closing in favor of https://github.com/lihaoyi/Ammonite/issues/275
