### ISSUE TITLE
Less noisy loading of dependencies in the success case

### ISSUE THREAD

**Issue by soc** [lihaoyi/Ammonite#244]
It would be nice if loading dependencies would only take up one line, like other operations.

Not sure if JLine supports that, but it would be cool if amm displayed a spinning animation (`/`, `–`, `\`, ...), and would replace that line with a simple "loaded X" on success.

**Comment by lihaoyi** [comment]
Given all the benign error messages seem to be gone, I'm demoting this to `wishlist`

**Comment by lihaoyi** [comment]
If nobody has bothered to do this after two years, probably a wontfix
