### ISSUE TITLE
Show newly available namespaces when loading dependencies

### ISSUE THREAD

**Issue by soc** [lihaoyi/Ammonite#245]
There are dependencies where the names and the packages provided differ, sometimes substantially.

In my experience, it's annoying to add a dependency and then having to search which packages have actually become available.

It would be cool if amm provided some helpful hints when loading a dependency, like:

```
loaded foo-bar, new available packages: org.foo.bar, org.foo.internal
```

**Comment by lihaoyi** [comment]
Closing this as a wishlist item; if anyone wants to take a crack at it, go ahead
