### ISSUE TITLE
The `:power` command doesn't work

### ISSUE THREAD

**Issue by gkossakowski** [lihaoyi/Ammonite#25]
Power REPL mode is very handy for compiler writers (small number of folks) but also for macro writers that want to poke around.

We would need some equivalent or preferably direct port of `:power` command.

**Comment by lihaoyi** [comment]
I doubt I'm going to have a direct port; at the very least anything going into Ammonite will need well-documented semantics, and I'm very very reluctant to introduce any special syntax handling.

Anything that goes in is going to have to be exposed as plain-old-functions, or a plain-old-library available within the REPL, especially if it's going to be used by a small number of folks. I'm putting the cost of each new built-in function as "very high" so we don't end up with a mess of undocumented things that don't work (like `:vals`). The mess of stuff I see in `interpreter.Power`, with chat-history left in the codebase as comments, probably isn't going to happen =P

To the point: exactly what are the things that power mode gives you that you like, and why do you like those things? Perhaps we could find something tighter and more principled that would provide all the flexibility you need

**Comment by lihaoyi** [comment]
I wonder, if Ammonite exposes the right bits, whether power mode can be split out into its own library and just `load`-ed by those few who care about it. Then it can be developed on its own and both ammonite and power mode can make progress faster independently

**Comment by gkossakowski** [comment]
I use just small number of features of power mode. It's all about accessing live compiler easily. The things I care about are:

  - `typed`
  - `typeOf`
  - `reify` (and the rest of compile-time reflection)
  - `definitions`

So it's really about poking around the compiler.

**Comment by lihaoyi** [comment]
Ok cool. Plausibly I could just expose the `Global` and then whoever wanted to write helpers could write whatever they want. I won't have time to pick this up any time soon (it seems like a pretty niche concern) but if anyone else wants to champion it we can figure out the right way to do things

**Comment by lihaoyi** [comment]
The `def compiler: Global` is now available within the REPL; from there you can build whatever you want on top of it
