### ISSUE TITLE
"something's wrong: no Current.scala in List[Int]RangePosition(Current.scala, 1510, 1510, 1519)" ...

### ISSUE THREAD

**Issue by soc** [lihaoyi/Ammonite#251]
... on trying to auto-complete `(l: List[Int]).`

**Comment by lihaoyi** [comment]
Closing in favor of https://github.com/lihaoyi/Ammonite/issues/275

**Comment by lihaoyi** [comment]
@odersky seems to be your code, any idea? 

https://github.com/scala/scala/blob/2.12.x/src/interactive/scala/tools/nsc/interactive/Global.scala#L343 

I'm not sure why the presentation compiler is full of `println`s anyway... shouldn't there be some proper logging mechanism?
