### ISSUE TITLE
Tab completion on Array causes ammonite to exit

### ISSUE THREAD

**Issue by dickwall** [lihaoyi/Ammonite#252]
If you hit tab to complete on the following line after opening ammonite:

`val a = new Array` then hit tab to invoke completion, you get a `scala.reflect.internal.FatalError` and ammonite immediately exits. Example transcript is shown below.

Note that I found this because I created an `ArrayElement` class for a demo, and hit tab to complete after typing Array. Ammonite probably shouldn't completely bug out in this case even if there is an error in the completion.

```
Loading...
Welcome to the Ammonite Repl 0.4.8
(Scala 2.11.7 Java 1.8.0_60)
@ class ArrayElement {
    def x = 10
  }
defined class ArrayElement
@ val ae = new ArrayException in thread "main" scala.reflect.internal.FatalError: Something is wrong: cannot find T in applied type Array
   sought  T in Array
 classSym  Array in scala
  tparams  T in Array

	at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.correspondingTypeArgument(TypeMaps.scala:565)
...
```

**Comment by lihaoyi** [comment]
Fixed by @ssanj , thanks!
