### ISSUE TITLE
Support the options that can be passed to `scala`

### ISSUE THREAD

**Issue by AbigailBuccaneer** [lihaoyi/Ammonite#253]
Hi,

We have a fairly complex (SCons-based) build system in one of our projects. One of the tasks is to compile a bunch of Scala code, and run `scala -i` with a bunch of arguments for the classpath and other compiler options:

`env JAVA_OPTS={opts} scala -cp {classpath} -Xmax-classfile-name 80 -Yrepl-sync -i console_predef.scala`

I'd love to be able to use `amm` as a drop-in replacement for those who have it on their system, and reuse the same console code. Unfortunately that's currently not possible as I'd need to create a new script to set the classpath and then call it with different arguments and different files.

**Comment by nachtfisch** [comment]
Hi. I'm having the same problem here. How do you handle the class path issue? Can you maybe share your script? Being able to set the class path would be great, passing VM parameters even better. I have the same use case as @AbigailBuccaneer

**Comment by lihaoyi** [comment]
Some compiler flags can be passed to the compiler in-REPL, or in your `predef.scala` file. e.g.
```scala
haoyi-static-analysis@ compiler.settings.maxClassfileName.value = 100
```

For JVM flags, you can set them by call `java -jar` on the ammonite file directly, e.g.

```
haoyi-mbp:static-analysis haoyi$ java -Xmx100M -jar ~/amm
Loading...
Welcome to the Ammonite Repl 0.4.8
(Scala 2.11.7 Java 1.8.0_25)
```

You should be able to set the classpath in a similar way, using Java's `-cp` flag (caveat: I haven't tried)

Others like `-Yrepl-sync` don't really apply to Ammonite, as far as I know. 

Are there any kinds of flags that you need? This covers all the compiler flags and the JVM flags, I don't know if there are other scala-REPL-specific flags that you would need

**Comment by nachtfisch** [comment]
Hey. Thanks a lot. -jar does not work together with -cp, but I managed by just running the main class. In my concrete example I have a maven module that I want to run your REPL with and I get the class-path from the module and run it. Auto completion gets pretty slow though and it doesn't limit it's output but that's probably some other issue. Thanks a lot. In case other people struggle, here my shell script 

https://gist.github.com/nachtfisch/b2fda09041829672d8e0

**Comment by lihaoyi** [comment]
If you want to add modules, you can use `load.jar` while inside the REPL, which should add them to the classpath. Then you don't need any special flags. You can also add it to your `predef.scala` so you don't need to keep typing it in

**Comment by lihaoyi** [comment]
Closing this for now, I think I've covered all the use cases
