### ISSUE TITLE
Tab completion after def results in an NPE

### ISSUE THREAD

**Issue by edwardsmatt** [lihaoyi/Ammonite#257]
If you type `def` and hit tab to invoke completion (without a space) a Null Pointer Exception occurs and Ammonite exits.

For example:
```bash
Loading...
Welcome to the Ammonite Repl 0.4.8
(Scala 2.11.7 Java 1.8.0_65)
matt-matt@ defException in thread "main" java.lang.NullPointerException
```

The full stack trace can be seen in the attached file.
[amm-def-tab-npe.txt](https://github.com/lihaoyi/Ammonite/files/33416/amm-def-tab-npe.txt)

**Comment by lihaoyi** [comment]
This wasn't actually fixed it seems.

**Comment by edwardsmatt** [comment]
Interesting, when running head using sbt shell/test:run or repl/run `def<tab>` doesn't result in a NPE for me. Do you have any further instructions on how you're reproducing this so I can follow up?

**Comment by lihaoyi** [comment]
I ran the standalone distribution https://github.com/lihaoyi/Ammonite/releases/tag/0.4.9, which should have your things in it because I merged your stuff earlier? Unless I screwed it up...

**Comment by lihaoyi** [comment]
Ah ok, I must have borked the release then, maybe I forgot to pull after merging your stuff on the website. It'll go out next release then =)

**Comment by edwardsmatt** [comment]
:+1:  :+1:
