### ISSUE TITLE
multiline strings fail to be processed

### ISSUE THREAD

**Issue by holgerbrandl** [lihaoyi/Ammonite#264]
Pasting the following multiline-string into the regular scala repl works but fails when using ammonite shell:
```
   val cmd = """
    echo "hello scala"
    """
```

The reported error is 
```
SyntaxError: found "\"", expected "\"\"\"" | StringChars | Interp | NonTripleQuoteChar in
    echo "hello scala"
```

Since multi-line strings are a common feature in scala nowadays they should work with ammonite as well.

**Comment by lihaoyi** [comment]
For some reason pasting it in line by line works, not sure why pasting it in all together is misbehaving

**Comment by lihaoyi** [comment]
This is a problem with ScalaParse. As far as I can tell, one possible solution would be to turn

```scala
      val NonTripleQuoteChar = P( "\"".? ~ "\"".? ~ !"\"" ~ AnyChar )
```

Into

```scala
      val NonTripleQuoteChar = P( "\"".? ~ "\"".? ~ !"\"" ~ (AnyChar | End) )
```

In order to properly handle the EOF case which is tripping up Ammonite. 

There may be other solutions too I'm not aware of, but this shouldn't be too hard

**Comment by lihaoyi** [comment]
Fixed by https://github.com/lihaoyi/Ammonite/commit/f56c5b4e0de3dccf67393aecac28cf3cd2338f2c
