### ISSUE TITLE
Stream evaluated on definition

### ISSUE THREAD

**Issue by nmehitabel** [lihaoyi/Ammonite#27]
e.g.
In standard scala repl
scala> val s = Stream.from(1)
s: scala.collection.immutable.Stream[Int] = Stream(1, ?)

In ammonite
@ val s = Stream.from(1)
s: scala.collection.immutable.Stream[Int] = Stream(
  1,
  2,
  3,
  4,
...

**Comment by lihaoyi** [comment]
Yeah that's "intentional", although perhaps it's worth revisiting the decision (e.g. making it cut off after N rows)

**Comment by lihaoyi** [comment]
This is fixed in 0.3.0, where even though the stream is evaluated, it gets cut off thanks to @laci37's work and avoids running forever.
