### ISSUE TITLE
Unresolved scalatex-api error when compiling against Scala 2.10.5

### ISSUE THREAD

**Issue by ssanj** [lihaoyi/Ammonite#271]
If I try to compile the source against Scala 2.10.5 with

```
++ 2.10.5 test:compile
```

The build fails to resolve scalatex-api:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lihaoyi#scalatex-api_2.10;0.3.1: not found
[warn] 	:: com.lihaoyi#scalatex-site_2.10;0.3.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.scala-lang#scala-library;2.10.5 ...
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.lihaoyi:scalatex-api_2.10:0.3.1 ((scalatex.SbtPlugin) SbtPlugin.scala#L49)
[warn] 		  +- readme:readme_2.10:0.1-SNAPSHOT
[warn] 		com.lihaoyi:scalatex-site_2.10:0.3.1 ((scalatex.ScalatexReadme) SbtPlugin.scala#L110)
[warn] 		  +- readme:readme_2.10:0.1-SNAPSHOT
```

and fails:

```
[error] (readme/*:update) sbt.ResolveException: unresolved dependency: com.lihaoyi#scalatex-api_2.10;0.3.1: not found
[error] unresolved dependency: com.lihaoyi#scalatex-site_2.10;0.3.1: not found
```

I couldn't seem to find the  com.lihaoyi#scalatex-site_2.10;0.3.1 artefact in [mavenrepository](http://mvnrepository.com/artifact/com.lihaoyi) or [maven.org](https://repo1.maven.org/maven2/com/lihaoyi). Has this artefact been uploaded somewhere globally accessible? The Travis build seems to work so I presume it has been uploaded somewhere or has been locally installed for Travis. Do I need to include an additional resolver into the build.sbt?

**Comment by lihaoyi** [comment]
`test:compile` isn't generally usable. You probably want `tested/test:compile`.

For this sort of thing ask in gitter first before opening an issue =P
