### ISSUE TITLE
Pretty printing does not work for parallel collections

### ISSUE THREAD

**Issue by holgerbrandl** [lihaoyi/Ammonite#278]
Here's an example
```
(1 to 10).toList.map(_+1)

(1 to 10).toList.par.map(_+1)
```
The first one looks pretty, the second one looks suboptimal even if the return values are both part of scala's built in collection hierarchy.

**Comment by lihaoyi** [comment]
I'm probably gonna call this a wontfix because parallel collections are an unmaintained basket case
