### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by alexarchambault** [lihaoyi/Ammonite#28]
Are the tests supposed to pass right now?

See their output [here](https://travis-ci.org/alexarchambault/Ammonite/jobs/53315706) for example.

**Comment by lihaoyi** [comment]
Uhh no they're not. Sorry, I've been kinda sloppy developing this. 

`longExample` and `lsR` should pass. I know there are race conditions with them that I haven't fully tracked down. The `scopePrefix` test also has race conditions which is super annoying and I haven't managed to figure out

**Comment by lihaoyi** [comment]
The others are known failures and should really be commented out

**Comment by lihaoyi** [comment]
All tests should pass now, including on 2.10
