### ISSUE TITLE
Broken readline style key navigation for multiline editing

### ISSUE THREAD

**Issue by mkotsbak** [lihaoyi/Ammonite#291]
In "Ammonite Repl 0.5.1", ctrl-p, ctrl-n, ctrl-b and ctrl-f does not behave as expected in multiline editing.

**Comment by lihaoyi** [comment]
How do they behave now? And what is "expected"? And what does this have to do with emacs?

**Comment by mkotsbak** [comment]
ctrl-p moves to the last complete statement. Expected it to works like arrow up, to move inside the statement (even though it would be nice to have separate commands for moving between statements and inside multiline-statements).

Inside a statement, ctrl-p and ctrl-n both works as right arrow, expected like arrow up and down.

It's just probably that those keys are shared with emacs.

**Comment by lihaoyi** [comment]
What about ctrl-b and ctrl-f, What's wrong with them? And what does this have anything to do with emacs?

**Comment by mkotsbak** [comment]
They work as expected :ľ

**Comment by mkotsbak** [comment]
Search for emacs here, bash uses readline: https://cnswww.cns.cwru.edu/php/chet/readline/rluserman.html

**Comment by lihaoyi** [comment]
I don't understand this issue, and I don't know anything about emacs, except it has nothing to do with Ammonite

**Comment by lihaoyi** [comment]
Feel free to follow up in gitter if you think this should stay open...

**Comment by mkotsbak** [comment]
It is not emacs, but readline as described in the docs:

```
All the readline-style navigation hotkeys like Ctrl-W to delete a word or Esc-Left/Right to navigate one word left/right still work. If you're comfortable with consoles like Bash, Python, IPython or even the default Scala console, you should have no trouble as all the exact same hotkeys work in Ammonite
```

Please try this out in a multi line editing scenario.

**Comment by lihaoyi** [comment]
Seems to work for me.

@mkotsbak I believe you there is something wrong but you have not managed to express what is wrong in a way I can understand. Perhaps you can just send a PR with the fixes you want?

**Comment by jbyler** [comment]
I think I understand, because I also would like this feature.  In most shells (e.g. bash), ctrl-p invokes the previous-history command, and ctrl-n invokes next-history.  This matches the default readline bindings as seen in [section 1.4.2](https://cnswww.cns.cwru.edu/php/chet/readline/rluserman.html#SEC15).  In ammonite REPL, up arrow and down arrow move through the history, but ctrl-p and ctl-n do not.

In addition, some shells (e.g. zsh) support multi-line commands, with multi-line editing.  Such shells generally bind ctrl-n and ctrl-p to next-line and previous-line, so they behave just like the arrow keys.  This has no direct readline equivalent as readline seems to be oriented toward editing a single line of text.  But many users expect ctrl-n and ctrl-p to do whatever the down and up arrow keys would do.

The connection to emacs is that emacs by default binds ctrl-f, ctrl-b, ctrl-n, ctrl-p to the four arrow keys, and this is the source of a lot of other software using these same key bindings.

Thanks for considering!

**Comment by mkotsbak** [comment]
@jbyler thanks for explaining.

**Comment by mkotsbak** [comment]
Please open and consider this issue again. Its a blocker issue for me to use it.

**Comment by lihaoyi** [comment]
This should be fixed in https://github.com/lihaoyi/Ammonite/commit/1283cf8a37cf9761029e62f4750e6fa01d6f50ec. Can one of you `sbt repl/test:run` the main repo and play around with some multi-line commands, to verify it works?

**Comment by mkotsbak** [comment]
Works perfect now, thanks!

**Comment by lihaoyi** [comment]
Great! Thanks @jbyler for explaining everything. This should go out in the next release whenever that happens

**Comment by jbyler** [comment]
Thanks much, @lihaoyi!  ^P and ^N now work (mostly) as I would expect.

One funny thing I notice: ^P, when reaching the beginning of history, wraps around and starts over again from the end of history.  ^N, by contrast, does not wrap around.  This behavior is also observed with the arrow keys, so I don't think it's specific to issue #291, but I thought I'd point out that I found it a bit surprising that the wrapping behavior is different depending on which direction you're going.

Another related observation: In ammonite, ^K kills to the end of the input, even if that's multiple lines, and ^U kills to start of input, even if that's multiple lines.  More commonly in other software that uses emacs- or readline-style bindings, ^K kills to the end of the *current line*, and ^U kills to the start of the *current line* (or sometimes, kills the whole current line).  I tested these behaviors in zsh without my dotfiles, but with "bindkey -e" to enable emacs keys mode, and compared the behavior with what ammonite does.  I'm not sure if ammonite has similar line-based editing commands, but if it does, binding them to ^U and ^K would be nice too.

One final note in case anybody else sees this and wants to test: the packages have changed, so if you are testing on the current master branch, the command is now `sbt amm/test:run`.

Thanks again for this fix, @lihaoyi!

**Comment by lihaoyi** [comment]
>  I'm not sure if ammonite has similar line-based editing commands, but if it does, binding them to ^U and ^K would be nice too.

Honestly, it doesn't follow any real standard. I tried to take what was the standard for readline style single-line command-lines, and generalized them ad-hoc to the multi-line nature of Ammonite. I honestly don't know what precedence there is for `^K` and `^U`, but I'd be happy to be persuaded that killing to start/end-of-multiple-lines is not useful/standard/common and we should make it kill to start/end-of-current-line-only

**Comment by jbyler** [comment]
OK!  Well, here's the readline documentation: [Section 1.4.4](https://cnswww.cns.cwru.edu/php/chet/readline/rluserman.html#SEC17) says that `^K` is bound to "Kill the text from point to the end of the line." and `^U` is bound to "Kill backward from the cursor to the beginning of the current line." by default.

Or, for zsh: [ZSH Line Editor](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html).  `^K` is bound to kill-line, "Kill from the cursor to the end of the line. If already on the end of the line, kill the newline character.".  And `^U` is bound to kill-whole-line, "Kill the current line."

I'm not aware of any precedent for using `^U` as kill to start of input or start of file, or `^K` as kill to end of input or end of file.

**Comment by mkotsbak** [comment]
I would also expect those commands to work on only current line.

Btw, how do I build a new version and install it as a "amm" executable?

**Comment by lihaoyi** [comment]
`sbt amm/test:assembly` builds it in `amm/target/scala-2.11/amm`. If you want to test changes, `sbt ~amm/test:run` works.

I'll to leave the modification of `^K` and `^U` to you guys; Ammonite's relatively easy to modify. https://github.com/lihaoyi/Ammonite/commit/1283cf8a37cf9761029e62f4750e6fa01d6f50ec gives you a starting point, you shouldn't have too much difficulty finding where those two bindings are defined, and modifying them to work by-line instead of by-entire-input should be relatively straightforward.

When you're done with it, send a PR and we'll merge it =)

**Comment by mkotsbak** [comment]
Ok, thanks. Am I doing anything wrong, or is it broken now? I get:

```
:/tmp/Ammonite/amm/target/scala-2.11$ ./amm
Loading...
LoadedPredef.scala:8: type mismatch;
 found   : ammonite.frontend.FullReplAPI
 required: ammonite.repl.frontend.ReplAPI
;val res_5 = ammonite.shell.Configure(repl, wd)
                                      ^
Exception in thread "main" java.lang.RuntimeException: Error during Predef: Compilation Failed
```

**Comment by lihaoyi** [comment]
Ah a bunch of the code changed in a non-backwards-compatible way; if you're using the shell predef you'll need to `sbt shell/publishLocal` the ammonite project and possibly clear the cache at `~/.ammonite/cache` to make it recompile properly (hopefully this should be fixed in the latest version).
