### ISSUE TITLE
Word-navigation key shortcuts C-left/C-right produce garbage in REPL

### ISSUE THREAD

**Issue by gnprice** [lihaoyi/Ammonite#293]
If I'm at the REPL and try to move a word at a time with my usual shortcuts C-left / C-right, instead of moving I get garbage characters inserted.

Copying and pasting the C-left output to another terminal and running through `xxd` to decode the bytes, it looks like it's `\x1b[1;5D`, except that the `\x1b` byte gets displayed as a Unicode unknown-character glyph.

The same key combinations work fine in bash in the same terminal, as well as everything else I use :) including Emacs and my browser.

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/Ammonite/pull/273 Is meant to fix it and should be brought into our codebase by D158653. I haven't verified it at all since Ctrl-Arrow is captured by the OS on a mac =P 

Want to patch that down and see if it works for you?

**Comment by lihaoyi** [comment]
Seems like that fixed it, and it works in master

**Comment by gnprice** [comment]
Yeah, that is one of the first things I fix when I use a Mac. =P  (My notes say it's in Keyboard -> Shortcuts -> Mission Control.)

WFM with that patch. Thanks!
