### ISSUE TITLE
Accidentally pressing the down arrow too many times loses edits

### ISSUE THREAD

**Issue by dickwall** [lihaoyi/Ammonite#297]
During some demos during training last week, I used the ammonite editing to go back and correct mistakes or simply update things from a previous demo. Often I would hit the down arrow just once too many times, at which point when you press up again all of the changes have disappeared and you have to make them again. It would be great if either ammonite could remember those changes, or prevent accidentally going past the end in a hurry.

**Comment by lihaoyi** [comment]
I've been bitten by this multiple times before. The solution I like would be to make Ammonite remember the edits you make to any history-access, at least until you press `[enter]` and submit the command to run. 

As a plus, this would make the behavior more or less similar to Bash and other REPLs.

**Comment by lihaoyi** [comment]
This might actually be "fixed" by https://github.com/lihaoyi/Ammonite/pull/281, which won't throw away the current input text if you press up/down while typing...

**Comment by lihaoyi** [comment]
This is fixed by https://github.com/lihaoyi/Ammonite/pull/335
