### ISSUE TITLE
Shift-Up/Down scrolls Cygwin window.

### ISSUE THREAD

**Issue by senia-psm** [lihaoyi/Ammonite#303]
Shift-Up/Down scrolls terminal window instead of selecting text.
Environment: Cygwin terminal + ssh + screen.

Workaround with `Ctrl/Alt+Shift+Up/Down` inserts character instead of selecting text.

According to error message on Ctrl/Alt+Shift+Up/Down, Enter:
```scala
SyntaxError: found "\u001b[1;6A", expected TopPkgSeq | Import | Prelude ~ BlockDef | Expr | End at index 0
```
`Ctrl+Shift+Up` - "\u001b[1;6A"
`Ctrl+Shift+Down` - "\u001b[1;6B"
`Alt+Shift+Up` - "\u001b[1;4A"
`Alt+Shift+Down` - "\u001b[1;4B"

**Comment by lihaoyi** [comment]
This and other cygwin related bugs should probably be reported under https://github.com/lihaoyi/Ammonite/issues/119 just to keep all the windows related stuff in one place
