### ISSUE TITLE
Loading current sbt project in ammonite repl like "sbt console" in current project directory

### ISSUE THREAD

**Issue by pamu** [lihaoyi/Ammonite#310]
sbt console in the current sbt project loads the project into to the repl. Is it possible to do the same with ammonite repl as well.

something like this

```
sbt console

```
output: loading current sbt project ....
similarly 

```
amm console
```
output: loading current sbt project....

**Comment by lihaoyi** [comment]
This is probably made redundant by the fact you can already run Ammonite in any SBT project pretty trivially 

http://lihaoyi.github.io/Ammonite/#Ammonite-REPL

**Comment by pamu** [comment]
thanks :+1:

**Comment by prozz** [comment]
@lihaoyi i dont think its trivial, i just failed to do this with use of docs description (probably dont know sbt enough and got multi-module project here). while searching for solution to the problem found this ticket.

i think you should reevaluate this feature request. easier level of entry is always welcome i guess.

regards

**Comment by estsauver** [comment]
Another thought: It would be very nice to be able to say "Run this script in the context of this sbt project."

```
import $sbt:~/Dev/myrepo/
```

would be very exciting.

**Comment by fmv1992** [comment]
> This is probably made redundant by the fact you can already run Ammonite in any SBT project pretty trivially
> 
> http://lihaoyi.github.io/Ammonite/#Ammonite-REPL

I disagree and agree with @prozz . I'm also trying to figure out how to run ammonite inside an sbt session the same I can `sbt 'project myproject' 'console'`.

Any directions?

**Comment by akaivola** [comment]
Agreed, just spent close to two hours trying to get Ammonite running and gave up.

**Comment by phyllisstein** [comment]
Since there's a little recent chatter, I thought I'd add that I found the linked instructions to _mostly_ work... except that sbt kept forking. Adding this line to `build.sbt` let me start Ammonite with `sbt test:run`:

```scala
Test / run / fork := false
```

**Comment by soronpo** [comment]
> @lihaoyi i dont think its trivial, i just failed to do this with use of docs description (probably dont know sbt enough and got multi-module project here). while searching for solution to the problem found this ticket.
> 
> i think you should reevaluate this feature request. easier level of entry is always welcome i guess.
> 
> regards

I agree

**Comment by beyondpie** [comment]
Sorry, anyone can tell me how to figure this out? The link discussed in the issue is broken.
Thanks!
