### ISSUE TITLE
bash `cd ~` counter part in ammonite repl

### ISSUE THREAD

**Issue by pamu** [lihaoyi/Ammonite#314]
in bash

```
cd ~
```

output: takes user to home.

`cd ~ ` support for ammonite repl

**Comment by lihaoyi** [comment]
There's `cd! home~

**Comment by lihaoyi** [comment]
Also, ask questions in gitter if you're not sure. The issue tracker is for issues, not questions

**Comment by pamu** [comment]
ok. Thanks
