### ISSUE TITLE
Support classpath argument

### ISSUE THREAD

**Issue by weixu02** [lihaoyi/Ammonite#317]
Ammonite is a great enhancement to scala REPL, and I am sure it it will be more and more popular quickly. The only pain I have right now is to load local libraries (either jar or a folder containing class files). Is it possible to support -classpath argument like the scala REPL? 

Thanks a lot.

**Comment by smungee** [comment]
+1 this would be awesome

**Comment by lihaoyi** [comment]
What would this let you do that you can't already do with `load.jar`, or in future when you can `load.dir` after https://github.com/lihaoyi/Ammonite/issues/315 gets implemented?

**Comment by smungee** [comment]
Well my use-case is, I want to quickly fire up amm with the classpath of the project I'm currently working on. This is what I do with the Scala REPL:

```
java -Dscala.usejavacp=true \
     -classpath "$(gradle printClasspath --quiet)" \
     scala.tools.nsc.MainGenericRunner
```

Is there a way to achieve the same effect with `amm` ?
(BTW, Loving ammonite repl.)

**Comment by weixu02** [comment]
My use case is similar, especially for a path containing .class files. These paths are usually output of dependent local projects. Since ammonite is such a great repl, I would like to use it to test/try the classes in my local projects. IMHO, this probably would be a common use case for any serious development with Scala.

Does "load" support loading of .class files? If so user can work out their our routines to initialize the environment. But still supporting the -classpath would make the repl even more convenient.

Thanks.

**Comment by lihaoyi** [comment]
@smungee you should be able to use `load.jar` to load a jar into the classpath. e.g.

```scala
~/amm --predef 'import ammonite.ops._; load.jar(cwd/"file.jar")'
```

There aren't really much docs on this, so feel free to send a PR to write it up and add it to the readme under [Artifact Loading](http://lihaoyi.github.io/Ammonite/#ArtifactLoading). If it doesn't work let me know, because it should.

@weixu02 `load` does not support loading of class files. That is what https://github.com/lihaoyi/Ammonite/issues/315 is all about. When someone (e.g. you =P) fixes that then we'll all be able to load folders full of class files into the REPL =D

**Comment by lihaoyi** [comment]
Also, if `load.jar` is causing issues, come chat on gitter and maybe we'll open a new issue for that. Loading loose classfiles can be discussed at #315

**Comment by dportabella** [comment]
this does not work anymore, and i didn't find the answer in the documentation: http://www.lihaoyi.com/Ammonite/#Ammonite-REPL
what is the correct way to doing this now?
i've tried with this without success
```
import $jar.`/path/filejar`, mypackage.myclass
```

**Comment by lihaoyi** [comment]
try 
```scala 
import $cp.path.to.`file.jar`
```
? 

Not sure if that would work but something like that should

`load.jar` is now available under `interp.load.jar`, and it should still work

**Comment by dportabella** [comment]
the first approach worked, thanks.

the second approach didn't:
```
@ import ammonite._, ammonite.ops._
@ interp.load.jar
cmd5.sc:1: value jar is not a member of ammonite.runtime.Load
val res5 = interp.load.jar
```

**Comment by kliuless** [comment]
@dportabella This worked for me (it's `load.cp`, not `load.jar`):
```
interp.load.cp(pwd / "somelib.jar")
```

**Comment by nielsen-at-cgt** [comment]
Hmm, I know there's something I'm missing.  I'm just learning Ammonite and so far I think it's amazing!

I have some scala code packaged into a jar file, that I'm trying to use with 1.0.0 of Ammonite REPL,.

I've tried to load my jar with interp.load.cp(pwd/"myjar.jar"), which did not complain.

The classes/objects in the jar are visible via the auto-complete (tab), but when I try to use them either with a fully-qualified name or in an import, I see "not found: value AwsImage" where AwsImage is the name of the object in question from the jar file.

My gratitude for a little help would be enormous.

Thanks!

**Comment by kliuless** [comment]
@nielsen-at-cgt A couple points:

I assume you've imported `ammonite.ops._`.

1. This probably doesn't apply to you, but is good to check nonetheless. `load.cp` won't complain if the jar doesn't exist. You can make sure the jar exists by using `exists! pwd / "myjar.jar"`.

2. I suggest you google for `scala "not found: value"` and read the top 5 matches. I suspect your issue isn't due to `load.cp`, but some confusion about scala imports/scoping.

**Comment by nielsen-at-cgt** [comment]
Thanks @kliuless, I was indeed importing ammonite.ops._, and did check that I was loading the jar.
The jar file defined a few objects (e.g. AwsImage), and tab-completion did, in fact, offer suggestions for members of AwsImage after my interp.load.cp whereas it didn't do so before the load, so I'm pretty sure the jar was loaded.

If the REPL offers completions, doesn't that imply the objects are in-scope?

Here's a snippet showing how I've defined the objects in my library:

    object AwsImage {
        case class ProductCode(ProductCodeType: String, ProductCodeId: String)
        implicit val productCodeFormat: OFormat[ProductCode] = Json.format[ProductCode]
        case class Tag(Value: String, Key: String)
        implicit val tagFormat: OFormat[Tag] = Json.format[Tag]
        case class Ebs(DeleteOnTermination: Boolean,
                               SnapshotId: String,
                                VolumeSize: Int,
                                VolumeType: String,
                                Encrypted: Boolean)

        implicit val ebsFormat: OFormat[Ebs] = Json.format[Ebs]
    ...

It may well be the case that I'm confused (or something) about imports/scoping.  If that's the case, I would be grateful for your gentle pointer. 

What I don't quite understand is why my imports fail, despite the REPL offering options with tab-completion:

    mnielsen-mnielsen@ import AwsImage.
    !=                         ImageDescription           ebsFormat                  imageFormat                |>
    ==                         ProductCode                equals                     isInstanceOf
    BlockDeviceMapping         Tag                        getClass                   productCodeFormat
    Ebs                        asInstanceOf               hashCode                   tagFormat
    Image                      blockDeviceMappingFormat   imageDescriptionFormat     toString

    mnielsen-mnielsen@ import AwsImage._
    cmd5.sc:1: not found: value AwsImage
    import AwsImage._
           ^
    Compilation Failed
    mnielsen-mnielsen@ import AwsImage.ProductCode
    cmd5.sc:1: not found: value AwsImage
    import AwsImage.ProductCode
           ^
    Compilation Failed

The code works fine when I run it as a script.

**Comment by piotrkwiecinski** [comment]
@nielsen-at-cgt could you create new issue for this and include small reproducer which works with scripts and doesn't with shell? It's always easier to help with debugging actual code than last bit before failure.

**Comment by kliuless** [comment]
@nielsen-at-cgt Is `AwsImage` in an explicit package? If not, try that. You may be running into [this issue](https://stackoverflow.com/a/9822212). You shouldn't rely on the fact that it works in a script.

**Comment by nielsen-at-cgt** [comment]
Thank you!

That was it.

**Comment by nielsen-at-cgt** [comment]
Hi Piotr; thanks for your reply.

I didn’t have my objects in an explicit package– apparently that’s bad.

**Comment by schlichtanders** [comment]
I spend several hours getting the right syntax how to load jars into ammonite 1.0.3
for others like me, here is the way I finally converged at:

```
amm --predef-code 'interp.load.cp(ammonite.ops.Path("/absolute/path/to/my/whateveryouwant.jar"))'
```
This works for both repl and scripts in principle

**Caution 1**: even doing ``import ammonite._`` before calling ``interp.load.cp`` will result in an error, that ``load`` cannot be found on ``interp``, see #758

**Caution 2**: script file name needs to be add *after* the amm options, but this is well documented indeed in ``amm --help``

**Caution 3**: There seem to be current issues with supporting insertion of arbitrary jars... see #756 and #757

**Comment by nielsen-at-cgt** [comment]
@schlichtanders : Thanks!

**Comment by raould** [comment]
As a potential new customer to ammonite I want to urge adding support for bog-standard boring old "-cp" or "-classpath" or both or whatever command line arguments per scala repl or java style. Having to go and learn some new syntax for something basic like that just to get started productively is kind of a brick wall in terms of usability.

**Comment by erikerlandson** [comment]
second @raould, being able to add directories or individual jar-files to the classpath is the difference between usability and non-usability for some use cases.  It should be something that can be done either inside the REPL or via an environment variable detected by the REPL when it starts up.

**Comment by olofwalker** [comment]
I know this opinion has been voiced previously, but having a `-cp` flag would make Ammonite go from a neat tool used now and then, to something I would use almost every day.....
