### ISSUE TITLE
Pre-compiled scripts start up really slowly

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#322]
```scala
haoyi-mbp:~ haoyi$ vim script.scala
haoyi-mbp:~ haoyi$ cat script.scala
println(1)
@
println(2)
haoyi-mbp:~ haoyi$ ~/amm script.scala
1
2
haoyi-mbp:~ haoyi$ time ~/amm script.scala
1
2

real	0m2.344s
user	0m6.381s
sys	0m0.359s
```

This may seem related to https://github.com/lihaoyi/Ammonite/issues/235, but really isn't: in that issue the main cause of slowness is the Scala compiler. Here, the scripts are already compiled and cached. There is no reason they shouldn't be able to start executing at full speed immediately upon request, and a compiler shouldn't be necessary. We need to investigate what's taking so long and remove it or speed it up

**Comment by tomjridge** [comment]
Do we get the similar results with the default scala interpreter (with -save) ?

**Comment by lihaoyi** [comment]
This has been basically solved, with @coderabhishek's work over GSOC. The above snippet starts in about 0.5 seconds.
```
haoyi-mbp:test haoyi$ cat main.sc
println(1)
@
println(2)
haoyi-mbp:test haoyi$ time amm main.sc
1
2

real	0m5.418s
user	0m12.646s
sys	0m0.646s
haoyi-mbp:test haoyi$ time amm main.sc
1
2

real	0m0.527s
user	0m0.716s
sys	0m0.078s
haoyi-mbp:test haoyi$
```

Currently, the startup profile looks like it's dominated by classloading time:

<img width="836" alt="screenshot 2016-07-25 20 02 32" src="https://cloud.githubusercontent.com/assets/934140/17100703/d33c3470-52a2-11e6-9f99-2678eaa4f6bd.png">

So presumably any perf-perf optimizations wouldn't have much of an effect, and we'd need to reduce the amount of classes being loaded.

Anyway, this issue can probably be considered closed
