### ISSUE TITLE
Blocks reading special file and can't be interrupted

### ISSUE THREAD

**Issue by Governa** [lihaoyi/Ammonite#323]
Reading the serial port with "read(root/'dev/'ttyS0)" will never end as it is a "stream" of data, but Ctrl+C can't interrupt the command. This forces the user to kill the shell.

**Comment by lihaoyi** [comment]
If you're reading from `/dev/tty`, you need `Ctrl-D` to kill it

**Comment by Governa** [comment]
Pressing Ctrl-D directly on the Ammonite terminal, doesn't stop the read.

Do you mean the Ctrl-D should be sent by the other side? If so, then there is nothing I can do, as I don't control what the other device, connected to the machine by an serial port, sends.

**Comment by lihaoyi** [comment]
Can you provide the terminal log of a complete minimal repro I can try at home?

**Comment by Governa** [comment]
This blocks indefinitely for me:

read(root/'dev/'tty8)

Using scala 2.11.7 with Java 1.8.0_72

**Comment by lihaoyi** [comment]
```
Welcome to the Ammonite Repl 0.5.3
(Scala 2.11.7 Java 1.8.0_25)
haoyi-Ammonite@ read(root/'dev/'tty8)
java.nio.file.NoSuchFileException: /dev/tty8
```

Fails for me; any other way I can repro this?

**Comment by Governa** [comment]
For me, any tty device shows this behaviour.

2016-02-02 15:41 GMT-02:00 Li Haoyi <notifications@github.com>:
