### ISSUE TITLE
File read should not need to put the entire file content on memory

### ISSUE THREAD

**Issue by Governa** [lihaoyi/Ammonite#324]
This issue is related with #323, where I need to read a file that does not end (serial port).

Right now I can't use the built-in read as it will block waiting forever.

Ideally what I would like to do is:
for (line <- read.lines(...)) {
  //Process line
}

**Comment by lihaoyi** [comment]
You probably want `read.lines.iter`

**Comment by Governa** [comment]
is there an equivalent to read.bytes?

**Comment by lihaoyi** [comment]
not that I know of
