### ISSUE TITLE
(Ammonite/REPL) add command to recompile the project and drop back to ammonite

### ISSUE THREAD

**Issue by matanster** [lihaoyi/Ammonite#327]
It would be a major productivity booster if one could recompile the project without exiting the ammonite REPL, or more practically, have an ammonite REPL command that closes the REPL, compiles (or runs some other arbitrary sbt command), then drops back into the ammonite REPL for the same sbt sub-project as it was originally launched for. 

Manually going through this is quite very tedious and urges a productivity boost.

If only an atomic command to drop out of the REPL & execute an sbt command was added in the ammonite REPL, the rest would be a piece of cake and mostly solved.

**Comment by lihaoyi** [comment]
Have you tried `sbt ~subproject/test:run`? Then it's just `exit` and it'll re-compile and re-run ammonite for you

**Comment by matanster** [comment]
Thanks, that's a good idea indeed. I can make it a custom sbt task even.
