### ISSUE TITLE
Tab-completion of import of non-existent package crashes REPL

### ISSUE THREAD

**Issue by andrewconner** [lihaoyi/Ammonite#328]
If you attempt to tab-complete inside an import of a package that doesn't exist, Ammonite REPL crashes. Steps to reproduce:

1) Start Ammonite REPL 0.5.2
2) Type `import fake.pkg.`
3) Press tab. Bang.

Reproduction:

![](http://acon.s3.amazonaws.com/tab-bang.gif)

Ammonite REPL 0.5.2
Scala 2.11.7

**Comment by coderabhishek** [comment]
I tried this on my machine it didn't crash?
Is it fixed for bug still shows open?

**Comment by lihaoyi** [comment]
@coderabhishek you're right, this should be fixed in https://github.com/lihaoyi/Ammonite/commit/d197c00361b6bbc0eec2e15e7b7b4e25993394ae
