### ISSUE TITLE
Problems when running Ammonite as an ssh server from a process without tty

### ISSUE THREAD

**Issue by gaborfeher** [lihaoyi/Ammonite#330]
I have Ammonite integrated into a Scala program, which exposes it via an ssh server. Like this:

```
./my_program
```

and then from another shell, I can do:

```
ssh -p 2203 ammonite@localhost
```

And it works fine.
1. The problem starts if I want to run my program in the background:

```
./my_program &
```

and then:

```
ssh -p 2203 ammonite@localhost
```

waits forever after I enter password. If I go back to the shell where I started my program and say `fg`, then the ssh login completes and I can use Ammonite.
1. Things get worse if I start my program using `nohup`:

```
nohup ./my_program &
```

then ssh-ing just prints the following error:

```
Welcome to the Ammonite Repl 0.5.2
(Scala 2.10.5 Java 1.7.0_91)
/bin/stty: standard input: Input/output error
/bin/stty: standard input: Input/output error
Connection to localhost closed.
```

Both these cases can be fixed by adding

```
repl.frontEnd() = ammonite.repl.frontend.FrontEnd.JLineUnix
```

into the predef, according to https://github.com/lihaoyi/Ammonite/issues/143#issuecomment-128534720

It looks like Ammonite somehow depends on the server's tty instead of the client's tty. Unfortunately, I have no idea how to improve this.

**Comment by lihaoyi** [comment]
This is basically the same issue as https://github.com/lihaoyi/Ammonite/issues/276
