### ISSUE TITLE
Modifying last command incorrectly autocompletes when using a subsequence

### ISSUE THREAD

**Issue by andystanton** [lihaoyi/Ammonite#338]
#### System

* OS: OSX 10.10.5
* Ammonite REPL Version: 0.5.3
* Terminal: OSX Terminal and iTerm2 beta 3.
* Shell: zsh and bash

#### Steps to reproduce

1. Load Ammonite REPL
2. Type `println("foo")`.
3. Push return.
4. `foo` is printed out as expected.
5. Push up arrow to show last command.
6. Use left arrow to place cursor after the last 'o'.
7. Push backspace so the command now reads `println("fo")`
8. Push return.
9. Command changes to `println("foo")` and `foo` is printed out instead of `fo`.

This affects numbers as well e.g.

1. Load Ammonite REPL
2. Type `println(100)`.
3. Push return.
4. `100` is printed out as expected.
5. Push up arrow to show last command.
6. Use left arrow to place cursor after the last '0'.
7. Push backspace so the command now reads `println(10)`
8. Push return.
9. Command changes to `println(100)` and `100` is printed out instead of `10`.

#### Notes

* This issue specifically affects *modifying* previous statement as described in steps. Entering `println("foo")` followed by manually typing `println("fo")` works as expected.
* This issue specifically affects subsequences of the string/number, so changing `foo` to `bar` or `100` to `200` will behave as expected.

**Comment by lihaoyi** [comment]
looks like I forgot that `BACKSPACE` counts as a control character

**Comment by andystanton** [comment]
That was ridiculously quick. Many thanks for your great work @lihaoyi
