### ISSUE TITLE
Ctrl - C doesn't work in this case, printing an infinite stream.

### ISSUE THREAD

**Issue by Saheb** [lihaoyi/Ammonite#342]
```
@ load.ivy("com.typesafe.akka" %% "akka-stream" % "2.4.2-RC1")
@ import akka.stream.scaladsl._
@ import akka.stream._
@ import akka.actor._
@ implicit val system = ActorSystem("TestMe")
@ implicit val materializer = ActorMaterializer()
@ val src = Source.repeat(1)
src: Source[Int, akka.NotUsed] = akka.stream.scaladsl.Source@249fb46b
@ src runForeach println
1
1
1
```
I am not able to stop this by any key combinatin, let me know if you have something to stop such a thing.

**Comment by lihaoyi** [comment]
This is probably a wontfix

`Ctrl-C` does, in fact, give you back control of the terminal. You can enter more commands, or `Ctrl-D` to exit from there. You can verify this by `Ctrl-C`ing, then re-entering the above code with the `Source.repeat(1)` replaced by `Source.repeat(2)`. You'll see it start interleaving the 1s and 2s, indicating that yes the command did go through.

In generally, Ammonite can't stop things you spawned of in separate threads, and I don't really see any way of teaching it. This is a limitation common to every other REPL I've used. Perhaps someone has a clever solution but it's not really a bug

**Comment by lihaoyi** [comment]
@Saheb Swing by gitter if you want to talk about it :)
