### ISSUE TITLE
Error at definition of Type

### ISSUE THREAD

**Issue by joiskov** [lihaoyi/Ammonite#343]
I try write this:

```scala
type T = {
```

but get an error:

```scala
SyntaxError: found "{", expected NamedType ~ Refinement.? | Refinement at index 9
type T = {
         ^
```

If i use scala REPL, all works fine:

```scala
scala> type T = {
     | type X = Int
     | def x: X
     | type Y
     | def y: Y
     | }
defined type alias T
```

**Comment by lihaoyi** [comment]
Looks like a bug in [ScalaParse](http://lihaoyi.github.io/fastparse/#ScalaParse) where it's not properly inserting a `~/` cut after the open-curly after a type declaration:

https://github.com/lihaoyi/fastparse/blob/master/scalaparse/shared/src/main/scala/scalaparse/Types.scala#L32

The second `~` on that line should be a `~/` to make this behave correctly.

**Comment by lihaoyi** [comment]
This is fixed in master
