### ISSUE TITLE
Scaladoc seems broken for some types

### ISSUE THREAD

**Issue by jarandaf** [lihaoyi/Ammonite#345]
Wanted to check some stuff about [resolvers](https://lihaoyi.github.io/Ammonite/api/repl/index.html#ammonite.repl.Resolver), which seems down.

**Comment by lihaoyi** [comment]
I bet I forgot to `git add -A` it when I added these new classes. I should make that part of my workflow...

**Comment by lihaoyi** [comment]
The scaladoc has been pushed, and I updated the readme to make sure to `git add` it every time in case it changes. Resolvers is now here
