### ISSUE TITLE
Command-F and Command-B abort Ammonite REPL on OS X

### ISSUE THREAD

**Issue by bmc** [lihaoyi/Ammonite#355]
Steps to reproduce:

1. Bring up the REPL.
2. Type Command-F. (Intention: Go forward one word.)
3. Watch stack trace abort the JVM.

```
Exception in thread "main" java.util.NoSuchElementException: key not found:
 	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ammonite.terminal.Ansi$Str$$anonfun$parse$3.apply(Ansi.scala:133)
	at ammonite.terminal.Ansi$Str$$anonfun$parse$3.apply(Ansi.scala:129)
	at scala.collection.immutable.Stream$StreamWithFilter.foreach(Stream.scala:570)
	at ammonite.terminal.Ansi$Str$.parse(Ansi.scala:129)
	at ammonite.repl.frontend.AmmoniteFrontEnd$$anonfun$6.apply(AmmoniteFrontEnd.scala:130)
	at ammonite.repl.frontend.AmmoniteFrontEnd$$anonfun$6.apply(AmmoniteFrontEnd.scala:119)
	at ammonite.terminal.TermCore$.x$3$lzycompute$1(TermCore.scala:222)
	at ammonite.terminal.TermCore$.x$3$1(TermCore.scala:222)
	at ammonite.terminal.TermCore$.transformedBuffer0$lzycompute$1(TermCore.scala:222)
	at ammonite.terminal.TermCore$.transformedBuffer0$1(TermCore.scala:222)
	at ammonite.terminal.TermCore$.readChar$1(TermCore.scala:227)
	at ammonite.terminal.TermCore$.readLine(TermCore.scala:299)
	at ammonite.repl.frontend.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:114)
	at ammonite.repl.frontend.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:26)
	at ammonite.repl.Repl.action(Repl.scala:56)
	at ammonite.repl.Repl.loop$1(Repl.scala:89)
	at ammonite.repl.Repl.run(Repl.scala:107)
	at ammonite.repl.Main$.run(Main.scala:135)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:82)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:81)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Main$.main(Main.scala:81)
	at ammonite.repl.Main.main(Main.scala)
```

Also happens if you're at the beginning of a line (type something, then do Ctrl-A) and you hit Command-F. Command-B (Emacs-speak for "backward-word") also fails.

**Comment by lihaoyi** [comment]
This should make it stop crashing and just forward the escape codes through to the final terminal:

https://github.com/lihaoyi/Ammonite/commit/a0804d75be4f01c7a9a837dd96aa651fd0e50d63

I have no idea what Cmd-F and Cmd-B are, as my macbook's OSX or iTerm captures them and they never even reach the repl process. Can you Ctrl-T before hitting those key-combos so I can see what the exact escape sequence being printed is?

**Comment by bmc** [comment]
Cmd-F: Char 27, Char 70
Cmd-B: Char 27, Char 66

I have iTerm2 wired to pass those through, because I'm used to using them with Emacs and Emacs-like things.

**Comment by lihaoyi** [comment]
- How do you make iterm pass those through? I was poking around the various settings dialogs and didn't see anything obvious
- What are they meant to do in Bash? Could you link to something which describes it?

**Comment by bmc** [comment]
On a Linux system (which I use from time to time, as well), Alt-F is "forward-word" in Emacs key bindings, and Alt-B is "backward-word". Emacs refers to "Alt" as "M" (meta). Bash uses GNU Readline on Linux (though I believe it uses libedit on Mac OS X, which is based on FreeBSD). In any case, see <http://web.mit.edu/gnu/doc/html/rlman_1.html>  Look for the M-f and M-b bindings.

When I use the Mac, I'm used to those keybindings, and the Cmd key is where the Alt key is, so I usually rebind those keys for convenience. In iTerm2, I found I could rebind them in the main "Keys" tab (not the "Keys" tab under "Profiles", but the main "Keys" tab up top.

**Comment by lihaoyi** [comment]
Meta-B and Meta-F are meant to be the same as Esc-B and Esc-F on OS-X right? On my machine,

- Esc-F Char 27 Char 102
- Esc-B: Char 27, Char 98

Seems similar, but not quite the same as what you were getting

**Comment by lihaoyi** [comment]
Ah I got it. I'm using Esc-f and Esc-b (lowercase) while you are using Esc-F and Esc-B (UPPERCASE)

Is the uppercase version meant to work? Are *all* uppercase versions meant to work? They seem to work in bash, and I never made any of the uppercased commands work in Ammonite since I didn't know you could do that. It wouldn't be hard to add uppercase support to the few places that need it

**Comment by bmc** [comment]
Hmm. I'm not _explicitly_ using upper case, but it wouldn't surprise me if Meta-F in iTerm2 _happens_ to generate that sequence. Seems worth supporting.

Ultimately, down the road, supporting a key map might be the way to go. That's what `libedit`, GNU Readline and JLine2 do. Could be a lot of work, though.

**Comment by lihaoyi** [comment]
@bmc for now do you want to try copy-pasting some uppercase versions of the three `Alt + ...` listed commands here:

https://github.com/lihaoyi/Ammonite/blob/7b6533e4c05d45c45e1768751a19c64ce45d84f9/terminal/src/main/scala/ammonite/terminal/filters/ReadlineFilters.scala#L43-L53

And seeing if it works for you? I could make the change myself but I'd want you to verify it actually works anyway at some point, so you might as well do it. If it does send a PR and I'll merge it in. 

Supporting a keymap is plausible but probably out of scope for now, let's just get this working for you first

**Comment by lihaoyi** [comment]
For what it's worth, the `Alt + "[A"`-style keycodes that the arrow keys emit seems to be decidedly case-sensitive, so only the three linked above need to be duplicated

**Comment by bmc** [comment]
What's the easiest way to build it? If I type `assembly` or `package` at the top level (in SBT), I get `java.lang.IllegalArgumentException: a module is not authorized to depend on itself: com.lihaoyi#ammonite-repl_2.11.7;0.5.5`

**Comment by lihaoyi** [comment]
try `sbt repl/test:run`. The other useful commands are listed here https://github.com/lihaoyi/Ammonite#manual-testing

**Comment by bmc** [comment]
No luck. No luck switching to `project repl` then doing a `test:run`. Same error: `ava.lang.IllegalArgumentException: a module is not authorized to depend on itself: com.lihaoyi#ammonite-repl_2.11.7;0.5.5`

**Comment by lihaoyi** [comment]
Odd, lemme try pulling a fresh clone and seeing what happens

**Comment by lihaoyi** [comment]
Below is what it looks like for me on a fresh clone. Did you by any chance happen to add ammonite to your global sbt config so it appears in every project? If that's the case you'll need to take it out

```scala
haoyi-mbp:Workspace haoyi$ rm -rf Ammonite/
haoyi-mbp:Workspace haoyi$ git clone git@github.com:lihaoyi/Ammonite.git
Cloning into 'Ammonite'...
Saving password to keychain failed
Identity added: /Users/haoyi/.ssh/id_rsa (/Users/haoyi/.ssh/id_rsa)
remote: Counting objects: 14863, done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 14863 (delta 75), reused 0 (delta 0), pack-reused 14725
Receiving objects: 100% (14863/14863), 8.68 MiB | 1.31 MiB/s, done.
Resolving deltas: 100% (6657/6657), done.
Checking connectivity... done.
haoyi-mbp:Workspace haoyi$ cd Ammonite/
haoyi-mbp:Ammonite haoyi$ sbt repl/test:run
[info] Loading global plugins from /Users/haoyi/.sbt/0.13/plugins
[info] Loading project definition from /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/project
[info] Updating {file:/Users/haoyi/Dropbox%20(Personal)/Workspace/Ammonite/project/}ammonite-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-c5d1b95fdcc1e1007740ffbecf4eb07[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to ammonite (in build file:/Users/haoyi/Dropbox%20(Personal)/Workspace/Ammonite/)
[info] Updating {file:/Users/haoyi/Dropbox%20(Personal)/Workspace/Ammonite/}ops...
[info] Updating {file:/Users/haoyi/Dropbox%20(Personal)/Workspace/Ammonite/}terminal...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Updating {file:/Users/haoyi/Dropbox%20(Personal)/Workspace/Ammonite/}repl...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 13 Scala sources to /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/terminal/target/scala-2.11/classes...
[info] Compiling 7 Scala sources to /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/ops/target/scala-2.11/classes...
[warn] /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/ops/src/main/scala/ammonite/ops/Path.scala:204: match may not be exhaustive.
[warn] It would fail on the following input: BasePathImpl()
[warn]   def apply(p: BasePath, base: Path) = p match{
[warn]                                        ^
[warn] there were two feature warnings; re-run with -feature for details
[warn] one warning found
[warn] there were 24 feature warnings; re-run with -feature for details
[warn] two warnings found
[info] Compiling 25 Scala sources to /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/repl/target/scala-2.11/classes...
[warn] /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/repl/src/main/scala/ammonite/repl/Main.scala:134: match may not be exhaustive.
[warn] It would fail on the following input: (Some(_), Some(_))
[warn]     (file, code) match{
[warn]     ^
[warn] /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/repl/src/main/scala/ammonite/repl/interp/Interpreter.scala:158: match may not be exhaustive.
[warn] It would fail on the following input: Exit(_)
[warn]         ev match {
[warn]         ^
[warn] there were 12 deprecation warnings; re-run with -deprecation for details
[warn] there were 8 unchecked warnings; re-run with -unchecked for details
[warn] there were 7 feature warnings; re-run with -feature for details
[warn] 5 warnings found
[info] Compiling 16 Scala sources to /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/repl/target/scala-2.11/test-classes...
[warn] there were two deprecation warnings; re-run with -deprecation for details
[warn] there were 25 feature warnings; re-run with -feature for details
[warn] two warnings found
[info] Running ammonite.repl.TestMain
Loading...
Welcome to the Ammonite Repl 0.5.7-SNAPSHOT
(Scala 2.11.7 Java 1.8.0_25)
@
```

**Comment by bmc** [comment]
Ha! That's it. Forgot I added it to my global config.

Will try shortly.

**Comment by bmc** [comment]
I'm not having much luck. Now, even Ctrl-P is not working properly. I'm going to play with it a little myself. Note: I built as follows:

```
$ sbt
> project repl
> assembly
```

Then, I ran with `java -jar /Users/bmc/src/open-source/scala/Ammonite/repl/target/scala-2.11/ammonite-repl-0.5.7-SNAPSHOT-2.11.7` _just_ to be sure SBT's JLine2-based console wasn't in the way somehow.

When I type Ctrl-P or Ctrl-N, I get spaces in the repl, rather than cycling through the history. I may take a whack at some of the source myself a little later.

**Comment by lihaoyi** [comment]
lol i bet that's because of https://github.com/lihaoyi/Ammonite/commit/77f8c4afc896f8b023641506d0f03f8689b5f740, where I couldn't figure out what those shortcuts were for and deleted them. That'll teach me to not-comment my magic strings. Feel free to revert that diff as part of your PR

**Comment by bmc** [comment]
Finally got around to re-testing this. (Sorry, I've been unbelievably swamped.)

Works like a charm now! Thanks!
