### ISSUE TITLE
Problem with imports (wrappers?)

### ISSUE THREAD

**Issue by alexarchambault** [lihaoyi/Ammonite#36]
Using the current master branch, I get
```scala
Loading Ammonite Repl...

@ load.ivy("com.chuusai" %% "shapeless" % "2.1.0")
:: resolving dependencies :: com.chuusai#shapeless_2.11-caller;working
	...
res0: Unit = ()

@ import shapeless._
import shapeless._

@ () // Nothing compiles starting from here, whatever the line we enter
Compilation Failed
Main.scala:1136: '}' expected but identifier found.
  ~?>$,
     ^

@ 
```
(re-formatted/stripped for readability).

The wrapper fails to compile once one imported `shapeless._`

**Comment by lihaoyi** [comment]
Definitely a problem with the wrapper generation, shouldn't be too hard to fix once i have time to take a look

**Comment by alexarchambault** [comment]
Possibly related to https://github.com/lihaoyi/Ammonite/issues/35

**Comment by lihaoyi** [comment]
Don't try to fix this yet, I have a bunch of WIP improving the import handling (and tests) that I haven't pushed

**Comment by lihaoyi** [comment]
I pushed https://github.com/lihaoyi/Ammonite/commit/a576aa4980c5846776b470677400ae453a611498 which is still kinda/sorta WIP but might (maybe?) fix some of these issues. Will take a look later

**Comment by alexarchambault** [comment]
Hope they don't conflict too much with my last PR...

**Comment by alexarchambault** [comment]
Ok, conflict =|

**Comment by alexarchambault** [comment]
@lihaoyi Not fixed :-| Last error is now
```scala
@ ()
Compilation Failed
Main.scala:1136: '}' expected but identifier found.
  ~?>$ => ~?>$,
     ^
```

**Comment by lihaoyi** [comment]
This particular one looks like an issue with the `backtickWrap` function not properly wrapping this, and perhaps a problem in importing things we shouldn't import (Private? Synthetic? Who knows?). 

In theory we could fall-back to the old behavior and just backtick-wrap everything, but I'd prefer to instead fix-forward and fix the backtick-wrapper. The parboiled parser must be correct and if it's not we should fix it until it is (like @paulp has done for his) and import fixing can't be that hard

**Comment by lihaoyi** [comment]
This should work now https://github.com/lihaoyi/Ammonite/blob/master/repl/src/test/scala/ammonite/repl/AdvancedTests.scala#L184-L193
