### ISSUE TITLE
Publish Ammonite Libraries for 2.11.8

### ISSUE THREAD

**Issue by chipsenkbeil** [lihaoyi/Ammonite#361]
Just wondering what the timeline is for publishing the Ammonite REPL library (and others) for Scala 2.11.8. I was previously running 2.11.6, but Ensime wants me to bump up to 2.11.8. When I did that, I realized that Ammonite hasn't publish any of its dependencies under 2.11.8. Since it looks like the 2.11 version is quite old for the REPL (0.2.7), I have to wait until 2.11.8 is published, or check with Ensime to see if I can downgrade back to Scala 2.11.6 or just bump to 2.11.7.

**Comment by lihaoyi** [comment]
It's been merged into master, I just haven't published it yet. For now you can force it to `ammonite-repl_2.11.7` (or for sshd) and it *should* work, though I haven't tested. At some point I'll publish the next version with 2.11.8 support

**Comment by chipsenkbeil** [comment]
Cool, that's all I needed to know. Thanks!
