### ISSUE TITLE
Ammonite 0.5.7 internally marked as 0.5.8-SNAPSHOT

### ISSUE THREAD

**Issue by apjanke** [lihaoyi/Ammonite#372]
The 0.5.7 tagged release on GitHub (https://github.com/lihaoyi/Ammonite/releases/tag/0.5.7) is pointing at commit ef731099ba0fb6ff15fcce1935f6115e27f1a26a ("onward to 0.5.8") instead of 3ec52cfe62a1b9b0ef8291ee67da79350e98fc97 ("0.5.7"), so the internal version number is 0.5.8-SNAPSHOT.

This is causing the build to fail in some cases: https://github.com/Homebrew/legacy-homebrew/pull/50648.

Could you make an "0.5.7a" release or similar that has the right internal version number?

**Comment by lihaoyi** [comment]
I re-tagged it and homebrew is apparently fixed...
