### ISSUE TITLE
Use CMS as the default GC in Ammonite REPL

### ISSUE THREAD

**Issue by veegee** [lihaoyi/Ammonite#380]
Currently, G1GC is being used as the default GC, but CMS has better performance for small heaps (< 4G), which is the most common use case for the REPL I think.

**Comment by lihaoyi** [comment]
Do you have numbers to back that up? Something in the same vein as https://github.com/lihaoyi/Ammonite/issues/216 would definitely convince me.

**Comment by veegee** [comment]
I don't have numbers specifically for this as I didn't set up the environment to test. But I do know from experience in running many other different JVM apps that CMS occupies less RSS than G1GC, and is much more efficient for small heaps, and has a lower latency. For large heaps (> 4GB), G1GC seems to be better in terms of latency.

**Comment by lihaoyi** [comment]
Let's close this for now until we have concrete numbers as the basis for discussion; feel free to ping/re-open when that happens!
