### ISSUE TITLE
Extra ' ' (space) required in the installation instruction for OSX users

### ISSUE THREAD

**Issue by adamatan** [lihaoyi/Ammonite#386]
# Problem description

The [installation instructions](http://www.lihaoyi.com/Ammonite/#GettingAmmonite-Shell) include the following step:

    $ curl -L -o amm https://git.io/vVfy5; chmod +x amm; ./amm

However, when copying this command to zsh on iTerm2 in OSX, `https://git.io/vVfy5;` becomes `https://git.io/vVfy5\;` because iTerm2 escapes the `;`, considering it a part of the URL.

# Suggested fix

If a space is added before the semicolon:

    $ curl -L -o amm https://git.io/vVfy5 ; chmod +x amm; ./amm

The problem is solved.

Could we please make this change to the instructions? It can remove a significant barrier for inexperienced users on the OSX shell.

**Comment by alexarchambault** [comment]
Alternatively, you could separate the commands with `&&`.

**Comment by adamatan** [comment]
@alexarchambault That's even better.

**Comment by lihaoyi** [comment]
Seems like an iTerm2/zsh problem; I use iTerm2 on OSX with Bash and i've been copy-pasting that url forever without issue.

I'll go swap it over to use `&&`; apart from fixing this probably better bash anyway
