### ISSUE TITLE
Allow parent .. and self . references in absolute paths

### ISSUE THREAD

**Issue by leslie-leder** [lihaoyi/Ammonite#388]
I use **ammonite-ops** not in the shell but as regular lib in a scala project. It took me quite a while to understand how to add a parent dir segment to an absolute path. 

First try which feel naturally 
  `cwd / ".." / "server" / "build" / "install" / "server"`
throws an 
  `InvalidSegment: [..] on absolute path #387 `

In order to get it right I'm required to construct a RelPath("..") object, which does not smoothly fit to the DSL:
  `cwd / RelPath("..") / "server" / "build" / "install" / "server"`

Wouldn't it be possible to allow the following paths: 
    
    cwd / ".." / "server" / "build" / "install" / "server"
   
    val externallyDefinedRelPath = "install/server"
    cwd / ".." / "server" / "build" / externallyDefinedRelPath

The latter one is useful if I need to construct paths with externally (not under my control) defined path segments.

With the current behavior I would need to pre-process all path segments I receive from others before I could use it. Which means split into segments and create *RelPath* objects for special segments like "." and "..".  This would not be worth the effort. The j.n.f.Path would deal with it like expected but its just not so nice like the ammonite dsl.

**Comment by lihaoyi** [comment]
For `".."` what you really want is the `up` operator.

If you are taking paths from outside which include multiple segments and possible `..`s, the correct thing to do is to use the `Path(...)` or `RelPath(...)` constructors. You don't need to split it, just call `RelPath` on the whole thing:

```scala
haoyi-Ammonite@ RelPath("abc/def")
res0: RelPath = 'abc/'def
haoyi-Ammonite@ RelPath("abc/def/../ghi/./jkl")
res1: RelPath = 'abc/'ghi/'jkl
```

I'll add the `up` suggestion to the error message, and make the absolute path error message better, but the behavior overall is probably not going to change. It's an explicit goal to provide some level of inconvenience when you want to deal with "raw" paths, making you wrap them in `Path` or `RelPath` if you want to parse them, and making sure none of them "leak into" your Ammonite program unless you explicitly want them
