### ISSUE TITLE
REPL requires two carriage returns to move to a new line

### ISSUE THREAD

**Issue by jacksonja** [lihaoyi/Ammonite#393]
I am using ammonite-repl 0.5.8 and scala 2.11.8 on a Mac and every time I try to add a new line to my code it requires pressing enter twice to get a new line.

**Comment by jacksonja** [comment]
I just installed 0.5.7 to compare and it does not require double enters to get a new line.

**Comment by lihaoyi** [comment]
Yeah this is a bug
