### ISSUE TITLE
Support prompt themes

### ISSUE THREAD

**Issue by oswaldo** [lihaoyi/Ammonite#399]
Hello,

I'm a [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) user and I'd like to know if ammonite supports/could support similar theme feature. Actually I've recently read that [sbt-prompt](https://github.com/agemooij/sbt-prompt) reached 1.0, So I wonder if that couldn't be integrated.

Regards,
Oswaldo

**Comment by lihaoyi** [comment]
This is already possible. You can use `prompt.bind{...}` to set your prompt to the result of any expression; in that `bind` clause, you can get the user, the current working directory, git branch, whatever and return a `String` for what you want to display. For example, here's the Ammonite-Shell binding to show the user and enclosing-folder;

https://github.com/lihaoyi/Ammonite/blob/master/shell/src/main/scala/ammonite/shell/Configure.scala#L14-L19

```scala

    repl.prompt.bind(
      sys.props("user.name") +
      "-" +
      wd.segments.lastOption.getOrElse("") +
      "@ "
    )
```

If you want a library of "themes", those are really just functions you can define. Someone can go define a bunch of functions, but Ammonite doesn't need to change anything to make it happen

**Comment by oswaldo** [comment]
Cool. Thanks for the clarification.
