### ISSUE TITLE
-Yno-imports

### ISSUE THREAD

**Issue by paulp** [lihaoyi/Ammonite#40]
Here's what the scala repl does if you start it with -Yno-imports:
```
scala -Yno-imports
Welcome to Scala version 2.11.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_40).
Type in expressions to have them evaluated.
Type :help for more information.

scala> <console>:6: error: not found: type Any
  def set(x: Any) = value = x.asInstanceOf[scala.tools.nsc.interpreter.IMain]
             ^
```
It flounders even harder in sbt. There's no way to fix it without hacking the repl.

This leaves me with hundreds and hundreds of identifiers in scope in the psp-std repl which I don't want.

If you can get me to a repl where I only have my own identifiers I would undoubtedly abandon the scala repl. It would be a start to expose Settings somehow, as right now I see no way at it. If you're advertising "null" as the argument to main clearly you're not getting a lot of mileage out of the arguments. How about
```
ammonite.repl.Repl.main(Array("-Yno-predef", "-Yno-imports"))
```
Speaking of too many identifiers,
```
Loading Ammonite Repl...
@ <tab> Display all 678 possibilities? (y or n)
```
Does that really seem like an improvement to you? There's a reason the scala repl doesn't blast every identifier it has ever seen at you in response to a tab. But it's especially bad for me, because in my source base none of those 678 offerings should be in scope except the tiny subset which I have aliased into one of my packages.

**Comment by lihaoyi** [comment]
yeah seems reasonable.

**Comment by lihaoyi** [comment]
Closing in deference to https://github.com/lihaoyi/Ammonite/issues/40
