### ISSUE TITLE
Repl history has forced autocompletion

### ISSUE THREAD

**Issue by randomstatistic** [lihaoyi/Ammonite#414]
If I:

1. Enter a command in the repl
2. Up-arrow to get it back from the history
3. Edit the command by removing trailing characters
4. Press Enter

The original command is run, rather than my modified command.
Example: http://imgur.com/vbvzHjB

Since I mostly use the repl to iterate on variations of a command, I find this tremendously irritating.

**Comment by lihaoyi** [comment]
This has been fixed a long time ago IIRC and isn't present in 0.6.2 AFAICT, or the latest snapshot
