### ISSUE TITLE
https://git.io/vKSbm is not found

### ISSUE THREAD

**Issue by tkawachi** [lihaoyi/Ammonite#415]
Download URL https://git.io/vKSbm (mentioned in http://www.lihaoyi.com/Ammonite/) is not found.

It redirects to https://github.com/lihaoyi/Ammonite/releases/0.7.0/0.7.0, and download URL seems like https://github.com/lihaoyi/Ammonite/releases/download/0.7.0/0.7.0.

**Comment by lihaoyi** [comment]
nice catch, thanks!
