### ISSUE TITLE
Custom java options (JAVA_OPTS env var support)

### ISSUE THREAD

**Issue by sscarduzio** [lihaoyi/Ammonite#419]
As a Finagle user, I need to pass some java options to the framework, but the `amm` command (which is a bash wrapper that invokes the JVM) does not seem to accept a way to pass custom java options to the JVM.

Historically one would have a JAVA_OPTS environmental variable containing all the Java options, and the bash wrapper would add this string as an argument when the JVM is invoked.

I believe Ammonite should support JAVA_OPTS or an equivalent mechanism.

**Comment by lihaoyi** [comment]
Seems reasonable.

As a workaround, you could write your own wrapper script that does this for you:

```scala
java -jar $(which amm) "$@"
```

and passes along whatever JVM arguments you need. And send a PR to add this functionality to our bash wrapper :P

**Comment by lihaoyi** [comment]
This is now available in the latest unstable build http://www.lihaoyi.com/Ammonite/#UnstableVersions
