### ISSUE TITLE
Use custom argument parser with ammonite

### ISSUE THREAD

**Issue by benwbooth** [lihaoyi/Ammonite#423]
I would like to be able to use a custom argument parser with ammonite instead of the built in one. How can I achieve this? Is there some way to access the command line arguments directly from the script without needing to use the `@main` annotation? It would be nice if there were an annotation like this:

`@args val args: Seq[String] = null`

or maybe:

`val args: Seq[String] = ammonite.main.Scripts.args`

which automatically filled in the command line arguments to a variable. This would also enable users to not have to provide a `@main` function in their scripts. Is this possible to achieve?
Thanks!

**Comment by lihaoyi** [comment]
Ideally 

```scala
@main def main(args: String*) = {
  ...
}
```

Should work. It currently doesn't, but that can be fixed.

We could expose the arguments as a global, which is what Python does, but I'd like to avoid that if possible. Exposing the command-line arguments as, well, arguments should in theory push people in the direction of dealing with them at the entry-point rather than grabbing them randomly throughout their scripts, which I think is the right thing to do

**Comment by benwbooth** [comment]
Fair enough. The one reason I like having the arguments as a "global" or being able to get them from a global function, is that it allows me to write the entire script at the top-level instead of within the main() function, which to me feels more script-y.

But if the syntax you posted worked, that would be a big improvement.

**Comment by benwbooth** [comment]
What about setting `this.args` to be the full command-line arguments in the script top-level? That way, the arguments are visible only to the script, and are not global.

**Comment by lihaoyi** [comment]
Discussed with @coderabhishek in gitter, we will try first to make String* work fine with the `generateRoutes` macro and scopt. If that doesn't work, we'll fall back to having it available as a global.

**Comment by lihaoyi** [comment]
Fixed by https://github.com/lihaoyi/Ammonite/commit/7608d6f726fd05256f03e237a49ea20b69887502; this allows you to take `String*` arguments in your `@main` methods, which will then take in all kinds of sets of arguments un-changed that you can then feed into whatever argument parser you want

**Comment by benwbooth** [comment]
I noticed a problem, with the following script I'm not getting the right command line arguments:

```
#!/usr/bin/env amm

@main def main(args: String*) = {
  println(args)
}
```

If I run that script using a `--`:

```
$ ./test.sc a b c -- d e
Vector(d, e, a, b, c)
```

The `--` is removed, and everything after the `--` is moved before the first set of arguments. This bug will prevent users from being able to correctly use custom argument parsers.

**Comment by benwbooth** [comment]
Also, is there any chance that the full arguments could also be exposed as a read-only global? It's the programming style a lot of people coming from other scripting languages (including myself) would prefer. I don't like having to indent my entire script in order to access the command-line arguments. Thanks!

**Comment by lihaoyi** [comment]
> The -- is removed, and everything after the -- is moved before the first set of arguments. This bug will prevent users from being able to correctly use custom argument parsers.

Ahh yeah that is a result of a hack I put in to distinguish script args from Ammonite's args; I hadn't realized it would result in this poor interaction. That will need to be fixed.

> Also, is there any chance that the full arguments could also be exposed as a read-only global?

sure I can do that

**Comment by lihaoyi** [comment]
> sure I can do that

Actually, @benwbooth would you like to do the honors of making a change and sending a PR? Concretely you'll need to add a `def scriptArgs: Vector[String]` onto our abstract `trait InterpAPI` and then from `Main.scala`, plumb the arguments down into wherever we end up instantiating our `InterpAPI`

**Comment by benwbooth** [comment]
Sure, no problem: #440

I had a question about whether `passThroughArgs` actually contains all the unprocessed arguments, or just the non-keyword positional arguments. Hopefully it contains all the arguments, since that's what I'm passing into the InterpAPI.args field.

Thanks!

**Comment by lihaoyi** [comment]
Fixed in https://github.com/lihaoyi/Ammonite/commit/c605d8600c9749b13ade1f85aa6250f959a0a7ff#diff-d624941e18d4c528c725d4c3c0bd0517R1089

This lets `@main` methods with varargs properly slurp in everything, allowing you to then use your own custom argument parser. The only caveat is you cannot use `--` in your own argument list, since that is reserved to separate Ammonite's arguments from your script's arguments. 

Please take a look at the changelog entry which describes this and let me know if this satisfies your requirements

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out
