### ISSUE TITLE
Cannot chdir into symlinked directory

### ISSUE THREAD

**Issue by winitzki** [lihaoyi/Ammonite#432]
On Mac OSX, amm 0.7 shell cannot execute `cd! 'abcd` if `abcd` is a symlink to a directory.

To reproduce:
```
$ amm
@ mkdir! 'test
@ %ln ("-s", "test", "test1")
@ cd! 'test1
```

Expected behavior: `cd!` should be successful. The symlinked directory `test1` exists and is accessible to the user. The behavior of `cd! 'test1` should be the same as in `bash`.

Actual result: Exception, current directory remains unchanged.
```
java.nio.file.NotDirectoryException: /private/tmp/test1
  ammonite.shell.ShellSession$$anonfun$1.apply(ShellSession.scala:22)
  ammonite.shell.ShellSession$$anonfun$1.apply(ShellSession.scala:21)
  ammonite.ops.Callable1.$bang(Extensions.scala:42)
  $sess.cmd104$.<init>(cmd104.sc:1)
  $sess.cmd104$.<clinit>(cmd104.sc:1)
```

On Mac OS X, `/tmp` is a symlink, so this problem prevents me from doing `cd! root/'tmp` on Mac OS X.

Another point is that the built-in `ln` cannot seem to produce symlinks, only hard links (is that right?). That's why I am calling the external `ln` in this example shown above.

**Comment by lihaoyi** [comment]
In theory `ln.s!` should be able to create symlinks. Of course, shelling out to the `ls` executable is a perfectly fine way of doing it too
