### ISSUE TITLE
printing method types

### ISSUE THREAD

**Issue by paulp** [lihaoyi/Ammonite#44]
Why do I get to know the type of val f but not of def f?
```
@ def f: Int -> String = 5 -> ""
defined function f
@ val f: Int -> String = 5 -> ""
f: psp.std.->[psp.std.Int,psp.std.String] = 5 ->
@
```
It seems you're not printing any methods types. This seems a significant omission.

**Comment by lihaoyi** [comment]
Sure, we should add them. Didn't realize the scala repl did this so just monkeyed its behavior for classes and objects and traits

**Comment by lihaoyi** [comment]
This will actually be a whole bunch of work. Up till now we're just calling `.toString` on the type and printing whatever it gives us. There's quite a lot of space to improve if we do things manually, but of course we'd actually need to write code to do it =/

**Comment by lihaoyi** [comment]
If anyone wants to take a crack at it go ahead

**Comment by lihaoyi** [comment]
Closing as Wishlist; if someone wants to do it then great, but I have no plans to tackle this
