### ISSUE TITLE
clearer documentation on how import $file lookup works

### ISSUE THREAD

**Issue by benwbooth** [lihaoyi/Ammonite#442]
I read the documentation on the `import $file` statement, but it's a little unclear:

> And so on, importing files as many or as deep as you want. You can use ^ segments at the start of your import $file to import things from outside your current working directory, e.g. import $file.^.^.foo will import the script file ../../foo.sc and make it available for you to use.

Is the documentation implying that `import $file` searches relative to the user's current working directory, or the directory in which the script lies? Because if `import $file` is relative to the current working directory, that seems like a big problem. Say I want to write a script that searches the current working directory for files and alters them in some way. If that script has any dependencies, it will not be able to find them if those dependencies are not in the current working directory. The `import $file` lookup should definitely be relative to the script's directory.

**Comment by DavidPerezIngeniero** [comment]
+1

**Comment by winitzki** [comment]
Perhaps there should be some sort of "script import path" from which the scripts can be imported. Alternatively, an absolute path should be given.

Right now, is there a possibility to import a script given its absolute path? `interp.load.module` is still available in scripts, or not any more?

**Comment by giftig** [comment]
This is causing me problems as well, as I'm trying to load other scripts into my predef.sc and it's looking for them relative to my cwd, which seems very wrong.

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/Ammonite/commit/7161d22992fecae8a0cbf198458fad99df3a36bf tweaks the docs to make sure they talk about "current scripts enclosing folder" rather than "current working directory", since that's what it's meant to do.

https://github.com/lihaoyi/Ammonite/commit/dfcf512524c9d12cb8f189d5820b73057a20d66a fixes predef imports to be relative to the predef script's enclosing folder, rather than pwd
