### ISSUE TITLE
Have all the capabilities of fish shell, possibly reusing their code

### ISSUE THREAD

**Issue by strelec** [lihaoyi/Ammonite#444]
I love the Ammonite shell, however, I love fish's history handling, auto-completion, command and output coloring, custom prompt, man page completions, git & apt-get auto-completion, and much more.

An ideal combination for me would be the syntax of Ammonite shell with all the capabilities of fish.

Can this be achieved somehow?

**Comment by lihaoyi** [comment]
Ammonite is not going to be the same as Fish. Fish is great, Ammonite is just something else.

If you want to ask about individual features, feel free to ask on the gitter channel!

**Comment by strelec** [comment]
I would just like

Ammonite Syntax
+
Fish Capabilities

Best of both worlds.
