### ISSUE TITLE
Multiple colors in prompt

### ISSUE THREAD

**Issue by lbialy** [lihaoyi/Ammonite#445]
Is it possible to have multiple colors in prompt? Right now even if I enter
```
repl.prompt.bind(prompt)
def prompt = {
  s"λ ${wd} " + fansi.Color.Green("~> ")
}
```
into `predef.sc` colors in prompt will get overridden by default magenta or any other color selected via `repl.colors().prompt() = ...`

**Comment by lihaoyi** [comment]
@Ibialy this works

```scala
λ /Users/haoyi/Dropbox (Personal)/Workspace/fastparse ~> {
                                                         repl.colors().prompt() = fansi.Attrs.Empty
                                                         repl.prompt.bind(prompt)
                                                         def prompt = {
                                                           s"λ ${wd} " + fansi.Color.Green("~> ")
                                                         }
                                                         }
```

the `fansi.Attrs.Empty` at the start nulls out the "default" prompt color, which was over-writing your custom coloration. That lets your colors shine through.

This could use a not in the docs, or somewhere else

**Comment by lbialy** [comment]
Thanks!
