### ISSUE TITLE
printing infix types

### ISSUE THREAD

**Issue by paulp** [lihaoyi/Ammonite#45]
```
@ val f: Int -> String = 5 -> ""
f: psp.std.->[psp.std.Int,psp.std.String] = 5 ->
@
```
Scala choose a pathologically awful way to print the type ```Int -> String```. That issue goes [back forever](https://issues.scala-lang.org/browse/SI-4700). You could print them sensibly, with the operator infix.

**Comment by lihaoyi** [comment]
This will actually be a whole bunch of work. Up till now we're just calling .toString on the type and printing whatever it gives us. There's quite a lot of space to improve if we do things manually (color, multi-line prettyprinting) but of course we'd actually need to write code to do it =/

**Comment by paulp** [comment]
Yes, it's some work. The real home run would be pluggable type pretty-printing, just like the value printing and for the same reason. I want that type printed as Int -> String, not psp.std.Int -> psp.std.String, but there's no general way to know when and whether to dealias types or omit packages.

**Comment by lihaoyi** [comment]
Would something like "pick the shortest path from the things in scope to reach the desired type" work? That way if you import things like `collection.mutable`, then you'd get `mutable.Buffer` and such. 

It could be expensive, but pretty-printing may not be that performance critical...

**Comment by paulp** [comment]
There are a lot of heuristics one could apply, just like scala does, but it will never be satisfying if there's no way to control it. It's the same reason you have a PPrint trait for values: it matters how things print, but the same thing should print differently in different situations. You have to have more visibility into what's being printed than string concatenation offers if you want to do anything sensible under composition, a part of the type might need to be rendered in red because a configuration says so, they might need to be truncated or abbreviated to fit in a diagram, etc etc etc.

**Comment by lihaoyi** [comment]
This has been fixed in the latest merge. You can now define an implicit `TPrint[T]` in order to control how a type is pretty-printed. Naturally, it works recursively like values and will apply to any type being printed, even in a larger compount type, and it can make use of the `TPrint[V]` for any components of the type `T` by taking them as implicits.
