### ISSUE TITLE
repl won't exit if non-daemon threads still active

### ISSUE THREAD

**Issue by tdyas** [lihaoyi/Ammonite#450]
If any non-daemon threads are running, the Ammonite repl will hang after Ctrl-D is pressed instead of exiting. (Saw this with 0.7.5 on Scala 2.11.8.)

Proposed solution: Add a `System.exit(0)` to the end of `ammonite.Main.main` in https://github.com/lihaoyi/Ammonite/blob/master/amm/src/main/scala/ammonite/Main.scala (or whatever other location(s) need it).

I can submit a PR with this. Thoughts?

**Comment by lihaoyi** [comment]
Sounds reasonable. Putting it at the end of `ammonite.Main.main` should suffice

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/Ammonite/commit/678f2a368066f219020ca02ce7da00b92b965f86

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out
