### ISSUE TITLE
bugs fixed by Ammonite

### ISSUE THREAD

**Issue by paulp** [lihaoyi/Ammonite#46]
I think you should start a list somewhere of open tickets fixed in Ammonite. Random example from early in the search results is [REPL can't handle (A*) => A](https://issues.scala-lang.org/browse/SI-8971).
```
scala> val f: (Int*) => Int = _.size
<console>:5: error: type mismatch;
 found   : Int* => Int
 required: Seq[Int] => Int
  lazy val $result = f
                                          ^
```
vs.
```
@ val f: (Int*) => Int = _.size
f: Seq[psp.std.Int] => psp.std.Int = <function1>
@
```

**Comment by paulp** [comment]
I guess I'm thinking wiki page.

**Comment by lihaoyi** [comment]
This could go in the readme docsite, feel free to send a PR ^_^ I don't personally care enough to go dig through JIRA and find these things
