### ISSUE TITLE
Some imports fail on the first attempt

### ISSUE THREAD

**Issue by cb372** [lihaoyi/Ammonite#484]
Importing seems to fail once with the following error, and work fine if you try again.

```
$ amm
Loading...
Welcome to the Ammonite Repl 0.7.7
(Scala 2.11.8 Java 1.8.0_101)
@ import $ivy.`org.typelevel::cats-core:0.7.2`
import $ivy.$
@ import cats.Traverse
cmd1.sc:1: package cats contains object and package with same name: implicits
one of them needs to be removed from classpath
import cats.Traverse
       ^
Compilation Failed
@ import cats.Traverse
import cats.Traverse
@
```

The `cats-core` lib and all its dependencies were already in my Ivy cache, in case that matters.

**Comment by lihaoyi** [comment]
Seems to have gone away after https://github.com/lihaoyi/Ammonite/commit/662859f84f5a77efca3e7e4d3074626570a992cf

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out
