### ISSUE TITLE
Ease to update Ammonite

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#488]
I've observed that the URL to download Ammonite changes with a new release.

In order to easy the process of updating Ammonite, I propose:
- URL to update latest stable version of Ammonite to be fixed
- A mechanism to trigger autoupdate of Ammonite.

**Comment by lihaoyi** [comment]
Now that you can `brew install ammonite` this is basically solved

**Comment by DavidPerezIngeniero** [comment]
`brew` is only for Mac.

**Comment by SiliconMeeple** [comment]
https://docs.brew.sh/Homebrew-on-Linux
