### ISSUE TITLE
Get the exit status of a command

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#489]
Many commands like `/usr/bin/test` or `grep` when return a result different of zero, it doesn't mean a failed state.

I'd like a variation of `%%` that report the `CommandResult` independently of the exit status value.
Something like:

```
def %%%(command: String) = 
           try %%(command)
           catch {
                case ex: ShelloutException => ex.result
           }
```

**Comment by lihaoyi** [comment]
I think just trying and catching is probably fine; you can use `%` if you don't need the stdout, but `%%%` is probably a bit too cryptic...

**Comment by lihaoyi** [comment]
you could also define that in your own `predef.sc` and use it everywhere

**Comment by DavidPerezIngeniero** [comment]
I agree that %%% is too cryptic, but another name can be used.  It was just an example.
