### ISSUE TITLE
cannot add a resolver from within a script

### ISSUE THREAD

**Issue by dportabella** [lihaoyi/Ammonite#491]
This works good:

```
$ amm
Loading...
@ val oss = Resolver.Http(
    "ambiata-oss",
    "https://ambiata-oss.s3-ap-southeast-2.amazonaws.com",
    IvyPattern,
    false
  )
@ interp.resolvers() = interp.resolvers() :+ oss
@ import $ivy.`com.ambiata::mundane:1.2.1-20141230225616-50fc792`
import $ivy.$
```

However, this fails:

```
cat >script <<'EOF'
import ammonite._, Resolvers._

val oss = Resolver.Http(
  "ambiata-oss",
  "https://ambiata-oss.s3-ap-southeast-2.amazonaws.com",
  IvyPattern,
  false
)

interp.resolvers() = interp.resolvers() :+ oss

import $ivy.`com.ambiata::mundane:1.2.1-20141230225616-50fc792`
EOF

$ amm script
Compiling script
:: loading settings :: url = jar:file:/usr/local/Cellar/ammonite-repl/0.7.8/bin/amm!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: com.ambiata#mundane_2.11-caller;working
    confs: [default]

:: problems summary ::
:::: WARNINGS
        module not found: com.ambiata#mundane_2.11;1.2.1-20141230225616-50fc792

    ==== local: tried

      /Users/david/.ivy2/local/com.ambiata/mundane_2.11/1.2.1-20141230225616-50fc792/ivys/ivy.xml

      -- artifact com.ambiata#mundane_2.11;1.2.1-20141230225616-50fc792!mundane_2.11.jar:

      /Users/david/.ivy2/local/com.ambiata/mundane_2.11/1.2.1-20141230225616-50fc792/jars/mundane_2.11.jar

    ==== m2: tried

      /Users/david/.m2/repository/com/ambiata/mundane_2.11/1.2.1-20141230225616-50fc792/ivy-1.2.1-20141230225616-50fc792.xml

      -- artifact com.ambiata#mundane_2.11;1.2.1-20141230225616-50fc792!mundane_2.11.jar:

      /Users/david/.m2/repository/com/ambiata/mundane_2.11/1.2.1-20141230225616-50fc792/mundane_2.11-1.2.1-20141230225616-50fc792.jar

    ==== central: tried

      http://repo1.maven.org/maven2/com/ambiata/mundane_2.11/1.2.1-20141230225616-50fc792/mundane_2.11-1.2.1-20141230225616-50fc792.pom

      -- artifact com.ambiata#mundane_2.11;1.2.1-20141230225616-50fc792!mundane_2.11.jar:

      http://repo1.maven.org/maven2/com/ambiata/mundane_2.11/1.2.1-20141230225616-50fc792/mundane_2.11-1.2.1-20141230225616-50fc792.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" ammonite.runtime.tools.IvyThing$IvyResolutionException: failed to resolve ivy dependencies unresolved dependency: com.ambiata#mundane_2.11;1.2.1-20141230225616-50fc792: not found
```

For some reason, `interp.resolvers() = interp.resolvers() :+ oss` is not taken into accound when run from within a script.

Note: I need this to create a script with the `#!/usr/bin/env amm` header.

**Comment by Eli-Golin** [comment]
Having exactly the same issue.
http://stackoverflow.com/questions/40257174/using-ammonite-repl-for-scala-scripting

**Comment by lihaoyi** [comment]
The problem here is that the resolvers only get added when the code executes, but the `import $ivy` takes effect *before* the code executes.

A workaround would be to put the resolver-mangling into a separate compilation block, using `@` to split the file in two:

```scala
import ammonite._, Resolvers._

val oss = Resolver.Http(
  "ambiata-oss",
  "https://ambiata-oss.s3-ap-southeast-2.amazonaws.com",
  IvyPattern,
  false
)

interp.resolvers() = interp.resolvers() :+ oss

@

import $ivy.`com.ambiata::mundane:1.2.1-20141230225616-50fc792`
...
```

Perhaps at some point we can add a magic `import $resolver` that can do this for us and let us avoid the annoying `@`

**Comment by dportabella** [comment]
cool! however I tried this and it fails with the same error.

**Comment by dportabella** [comment]
@Eli-Golin, does the solution proposed by @lihaoyi work for you?

**Comment by lihaoyi** [comment]
sorry, haven't had time to look at this properly. I'm hoping that when @alexarchambault releases coursier 1.0.0 I can switch to it and all my ivy problems will magically go away... I don't actually know how ivy works

**Comment by hohonuuli** [comment]
Just a note that I'm having the same issue. Using `@` didn't fix it for me either. (Also, ammonite is fantastic BTW)

**Comment by drdozer** [comment]
Is there a fix for this? I have a dependency on the postgres jdbc jar, in https://maven.atlassian.com/3rdparty/ and while i can load this in the REPL, I can't work out how to add the resolver in a script to get it to work.

**Comment by drdozer** [comment]
A work-around is to manually load that dependency into your local maven cache:

mvn dependency:get -DrepoUrl=https://maven.atlassian.com/3rdparty/ -DgroupId=postgresql -DartifactId=postgresql -Dversion=9.4.1208-jdbc42-atlassian-hosted

**Comment by lihaoyi** [comment]
Should be fixed in https://github.com/lihaoyi/Ammonite/commit/daa476809a8307586dca30703ae7e7f8fba74ab8

**Comment by dportabella** [comment]
cool! i see the fix is committed in the "test" branch.
is it possible to get a notification when the fix is released?

**Comment by lihaoyi** [comment]
Come hang out in the gitter channel or follow me on twitter and you'll get pinged =)

**Comment by lihaoyi** [comment]
At some point, the Ammonite REPL will start pinging you about updated versions (https://github.com/lihaoyi/Ammonite/issues/488) but that's for the future

**Comment by dportabella** [comment]
ok, thx!

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out

**Comment by dportabella** [comment]
https://github.com/helgeho/Web2Warc/issues/2#issuecomment-304621043
