### ISSUE TITLE
Compilation cache not cleared when creating assembly and running with java -cp

### ISSUE THREAD

**Issue by rubenpieters** [lihaoyi/Ammonite#499]
I set up a small repo to illustrate what I mean https://github.com/rubenpieters/AmmCacheIssue

so the repro steps are:

git clone https://github.com/rubenpieters/AmmCacheIssue.git
cd AmmCacheIssue
sbt assembly
-- at this point you can check java -cp "target/scala-2.10/\*" test.AmmoniteShell and you can print out valX
vi src/main/scala/AmmCacheIssueRepro.scala <edit for example valZ to valY>
sbt assembly
-- now when trying java -cp "target/scala-2.10/\*" test.AmmoniteShell if you try to print out valX it will mention:

cmd0.sc:60: value valZ is not a member of object test.TestObject
import _root_.test.TestObject.{
       ^
Compilation Failed

Manually clearing the compilation cache as suggested in gitter (rm -r ~/.ammonite/cache) makes things work again.

**Comment by lihaoyi** [comment]
Fixed by 5ad6ad193fc0d67ecdb2f544e417afaa3bdc9bd8, which properly mtimes jar files in addition to class files when determining if a recompile is necessary
