### ISSUE TITLE
Loading multiple versions of the same library?

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#502]
I have this imports in my script:

    import $ivy.`ch.qos.logback:logback-classic:1.1.7`
    import $ivy.`com.logentries:logentries-appender:1.1.32`

When running my script I see:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dd/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dd/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
```

2 differents versions of logback-classic are loaded at once!!!!

After some research, here is a dependency of logentries-appender:

```xml
<dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.0.11</version>
            <optional>true</optional>
</dependency>
```

I'm used to SBT and Maven behavior.  They remove automatically old versions of libraries if there is a more recent one.

**Comment by lihaoyi** [comment]
This is because our ivy implementation is pretty janky; I'll probably swap over to @alexarchambault's Coursier when it reaches 1.0

**Comment by DavidPerezIngeniero** [comment]
Or maybe even reusing portions of SBT.

**Comment by lihaoyi** [comment]
Given https://github.com/lihaoyi/Ammonite/commit/662859f84f5a77efca3e7e4d3074626570a992cf, If you do

```scala
import $ivy.{
  `ch.qos.logback:logback-classic:1.1.7`,
  `com.logentries:logentries-appender:1.1.32`
}
```

to perform the imports in one batch, I believe Coursier will now de-duplicate the jars if you have more than one version of each.

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out

**Comment by alexarchambault** [comment]
@lihaoyi In your example above, if both `ch.qos.logback:logback-classic:1.1.7` and `com.logentries:logentries-appender:1.1.32` are resolved at the same time (with a single coursier resolution), its result shouldn't have duplicated jars.
