### ISSUE TITLE
Fail to parse multiline anonymous function

### ISSUE THREAD

**Issue by nikitajz** [lihaoyi/Ammonite#507]
I'm following examples of twitter school using your console (https://twitter.github.io/scala_school/basics.html)
The following example fails to be parsed, though it works properly in _sbt console_

```
@ { i: Int =>
    println("hello world");
    i * 2
  }
```
with the following error:

> fastparse.core.ParseError: found "(\"hello world\");\n  i", expected Semis | End | BacktickId | PlainId | "with" at index 19
>   println("hello world");
>          ^
>   fastparse.core.Parsed$class.get(Parsing.scala:32)
>   fastparse.core.Parsed$Failure.get(Parsing.scala:74)
>   ammonite.runtime.Interpreter$$anonfun$processLine$2$$anonfun$apply$9$$anonfun$15.apply(Interpreter.scala:219)
>   ammonite.runtime.Interpreter$$anonfun$processLine$2$$anonfun$apply$9$$anonfun$15.apply(Interpreter.scala:217)
>   scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
>   scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
>   scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
>   scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
>   scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
>   scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
>   ammonite.runtime.Interpreter$$anonfun$processLine$2$$anonfun$apply$9.apply(Interpreter.scala:217)
>   ammonite.runtime.Interpreter$$anonfun$processLine$2$$anonfun$apply$9.apply(Interpreter.scala:213)
>   ammonite.util.Res$Success.map(Res.scala:62)
>   ammonite.runtime.Interpreter$$anonfun$processLine$2.apply(Interpreter.scala:213)
>   ammonite.runtime.Interpreter$$anonfun$processLine$2.apply(Interpreter.scala:209)
>   ammonite.util.Catching.flatMap(Res.scala:108)
>   ammonite.runtime.Interpreter.processLine(Interpreter.scala:209)
>   ammonite.repl.Repl$$anonfun$action$4$$anonfun$apply$2.apply(Repl.scala:88)
>   ammonite.repl.Repl$$anonfun$action$4$$anonfun$apply$2.apply(Repl.scala:87)
>   ammonite.repl.Scoped$$anonfun$flatMap$1.apply(Signaller.scala:44)
>   ammonite.repl.Signaller.apply(Signaller.scala:29)
>   ammonite.repl.Scoped$class.flatMap(Signaller.scala:44)
>   ammonite.repl.Signaller.flatMap(Signaller.scala:11)
>   ammonite.repl.Repl$$anonfun$action$4.apply(Repl.scala:87)
>   ammonite.repl.Repl$$anonfun$action$4.apply(Repl.scala:74)
>   ammonite.util.Res$Success.flatMap(Res.scala:57)
>   ammonite.repl.Repl.action(Repl.scala:74)
>   ammonite.repl.Repl.loop$1(Repl.scala:98)
>   ammonite.repl.Repl.run(Repl.scala:117)
>   ammonite.Main.run(Main.scala:108)
>   ammonite.Main$$anonfun$main$1$$anonfun$apply$1.apply(Main.scala:249)
>   ammonite.Main$.ammonite$Main$$ifContinually$1(Main.scala:228)
>   ammonite.Main$$anonfun$main$1.apply(Main.scala:230)
>   ammonite.Main$$anonfun$main$1.apply(Main.scala:230)
>   scala.Option.foreach(Option.scala:257)
>   ammonite.Main$.main(Main.scala:230)
>   ammonite.Main.main(Main.scala:-1)
> Something unexpected went wrong =(

**Comment by lihaoyi** [comment]
This actually isn't a bug but a consequence of Ammonite using `{}` to wrap multi-statement commands. Thus, the outer `{}` is always stripped before code is parsed/run, which causes this error. Thus this works:

```scala
@ {{ i: Int =>
      println("hello world");
      i * 2
    }}
res0: Int => Int = <function1>
```

Nonetheless, I'll leave it marked as a bug because we really should fix the error message to avoid showing a stack trace

**Comment by nikitajz** [comment]
thanks a lot for advice and taking a look at this

**Comment by lihaoyi** [comment]
As of ae4b0b575261d53da0f7b517dd44f7c1cdf09bf2, Ammonite now fails with a more reasonable error message 

```scala
@ {i: Int => i}
<console>:1: ';' expected but '=>' found.
i: Int => i
```

This is identical to what you see if you put the same code, without curlies, into the normal Scala REPL:
```scala
scala> i: Int => i
<console>:1: error: ';' expected but '=>' found.
i: Int => i
       ^
```

As such, it's probably good enough for now. As mentioned, if you want a function literal, double up on `{{...}}` the same way if you want non-stripped curlies for whatever other reason (local variables, etc.)
