### ISSUE TITLE
Documentation error in Ammonite SSHD?

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#509]
The documentation states:

    libraryDependencies += "com.lihaoyi" % "ammonite-sshd" % "0.8.0" cross CrossVersion.full

It doesn't compile under SBT 0.13.9 when I use this:

```scala
projectDependencies ++= Seq(
  "com.lihaoyi" % "ammonite-sshd" % "0.8.0" cross CrossVersion.full
)
```

I have to use:

```scala
projectDependencies ++= Seq(
  "com.lihaoyi" % "ammonite-sshd" % "0.8.0" Compile cross CrossVersion.full
)
```

**Comment by lihaoyi** [comment]
No idea, it seems to work for other people? 

https://github.com/iozozturk/amonaki/blob/fc50ccd0be58a2c2669ddadee10d93d2e51b16c0/build.sbt#L8
