### ISSUE TITLE
Feature request: support for scalas style scripts

### ISSUE THREAD

**Issue by jbyler** [lihaoyi/Ammonite#510]
I love how fast the Ammonite script runner is: it has much less overhead than `scalas` and the startup for running pre-compiled scripts is much faster with Ammonite.

However, a `scalas` script has one big advantage: by specifying the dependencies in a comment, the script remains valid scala.  It can be named *.scala, and IDEs and syntax highlighters recognize the script as valid scala code.

It would be great if ammonite could support the same syntax as scalas does for specifying library dependencies and scala version.  See [example code here](http://www.scala-sbt.org/0.13/docs/Scripts.html#Example) for what the syntax looks like.

For bonus points, it would be even better if the Ammonite executable could be linked to the name "scalas" and used as the runner for scalas-style scripts, allowing these same scripts to run unmodified with the `#!/usr/bin/env scalas` shebang line, on either `scalas` or Ammonite.

**Comment by lihaoyi** [comment]
Probably not going to happen; even with the deps in comments, IDEs will still barf over all the code for which it doesn't understand the imports for. So if we're going to fix IDEs to make them understand whatever custom dependency-definition syntax we're using, might aswell add in support for the `@` block-separator and be done with it.

Overall, I don't think there are enough `scalas` scripts out there for it to be worth it for us to try and provide a migration-path to use them with Ammonite. Hopefully Ammonite itself will be sufficiently popular (fingers crossed!) that the number of Ammonite scripts will far exceed the number of `scalas` scripts, which would mean we should prioritize work that helps new users over bridging from `scalas`

**Comment by jbyler** [comment]
Yep, fair enough, there probably aren't that many `scalas` scripts out there.  Thanks for the response!  Perhaps I was too specific in my feature request though.  What I'm really asking for is a good way to edit an Ammonite script.  Would you be open to a different feature request along those lines?

Specifically: currently an Ammonite script is not valid Scala code, and thus IDEs and syntax highlighters all choke.  I would like to use Ammonite scripts for lots of things, but I need a good workflow.  I have set up a scala-scripts project with an IDE configuration that includes libraries I might want to use, so the IDE can resolve these 3rd party imports.  I can then use the IDE to edit and test the scripts.  The question is, how to install the script into `~/bin`?

As a workaround, I plan to create a post-processing build step that prepends an Ammonite header to each script file, so that the file can be run from the command line, without dependence on the IDE project.  But if Ammonite scripts were valid Scala code, and I could include the dependencies in a comment the way scalas does, then I wouldn't need this extra post-processing step, and the Ammonite scripts could be copied directly to ~/bin or run in-place.

I merely picked the `scalas` format because it exists already and is valid Scala, and there are at least a few examples around of scalas scripts which could then be run by Ammonite.  But I don't really care about scalas compatibility very much; I just want Ammonite scripts to be valid Scala so I can use an IDE.

Note that I have seen Issue #434, and I agree that would be another way to solve this issue.  But it seems like a much harder route than what I was proposing here, and it's still only a partial solution since vim, emacs, and other IDEs would each need a separate implementation of Ammonite script support.

Do you mind if I ask how you currently edit Ammonite scripts?

p.s. Thanks for the great talk at Scala by the Bay! I'm inspired to use Ammonite more...  =)

**Comment by lihaoyi** [comment]
Making an IDE that does *not* choke on Ammonite scripts is tracked here https://github.com/lihaoyi/Ammonite/issues/434

Hopefully someone will step up to the plate and do it 😛  Otherwise, there's next year's GSOC...

**Comment by Miuler** [comment]
Seria fantástico poder agregar una cabecera al estilo:
  `#!/usr/bin/env amm`

It would be great to be able to add a header to the style:
  `#!/usr/bin/env amm`
