### ISSUE TITLE
tweak Ctrl-k behavior (request)

### ISSUE THREAD

**Issue by emanresusername** [lihaoyi/Ammonite#514]
I'm used to `zsh` so i might be biased, but i almost always want `Ctrl-k` to only delete the current line, instead of deleting **__everything__** after the cursor

say i were to hit `Ctrl-k` in the following scenario, the `|` represents the cursor
```scala
{
|import com.duplicate.thing
import com.duplicate.thing
val lots = """
and
lots
of
lines
after
that
you
want
to
keep
"""
}
```
i'd prefer the result to simply remove the duplicate line, instead of the current behavior which would remove everything after the cursor and leave me with just
```scala
{
```

**Comment by lihaoyi** [comment]
Go ahead and send a PR; many of these commands were ported from Bash, which does not have multiple lines at all, so it makes sense to tweak them to be more useful in a multi-line context

**Comment by emanresusername** [comment]
haven't dug into the code base at all yet, any pointers on where to start?

**Comment by lihaoyi** [comment]
Probably here https://github.com/lihaoyi/Ammonite/blob/3ccb6b18cd5a18ce63070b2179884995125aaa57/terminal/src/main/scala/ammonite/terminal/filters/ReadlineFilters.scala#L151

**Comment by lihaoyi** [comment]
Fixed by https://github.com/lihaoyi/Ammonite/pull/529, should be out in the next unstable build
