### ISSUE TITLE
$maven dependencies resolver

### ISSUE THREAD

**Issue by kgignatyev** [lihaoyi/Ammonite#524]
how difficult it might be to add $maven dependency resolver?
so it would use  ~/.m2/settings.xml that lists local repository mirrors and local private repos?

**Comment by deusaquilus** [comment]
Okay, I did exactly this with #580, not sure why the Scala 2.10.6 build in Trevor specifically and not others. Any comment would be appreciated.

**Comment by lihaoyi** [comment]
As of https://github.com/lihaoyi/Ammonite/commit/662859f84f5a77efca3e7e4d3074626570a992cf, you should be able to use @alexarchambault's Coursier APIs to create your own maven resolver, and with https://github.com/lihaoyi/Ammonite/commit/b5c44b0d8496b07adc2d323c497fdf622a22fd09 you should be able to properly add resolvers in multi-block scripts.

I'm not sure whether Coursier comes with a builtin way of dealing with settings.xml, but it should be possible to load that config in some way without needing to patch Ammonite I think

**Comment by alexarchambault** [comment]
Yeah, coursier doesn't load things from `~/.m2/settings.xml`. It might have some global config file at some point, which I can imagine could allow to load settings from `~/.m2/settings.xml` too.
