### ISSUE TITLE
Private members do not work with unwrapping

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#526]
This should work
```scala
@ { 
  private[this] def x = 1 
  }
SyntaxError: found "private[this] def x ", expected ";" | Newline.rep(1) | "}" | `case` at index 2
{ private[this] def x
  ^
```

And the outer curlies should be stripped to leave a private method defined in that command's wrapper object. The fact that it does not parse is a bug in the parser we're using to unwrap/split the input into statements

**Comment by tkroman** [comment]
I think I'll take a stab at this in the next few days.

**Comment by lihaoyi** [comment]
yes, we want to provide the `{ private[this] def x } => private def x` transformation. That is because Ammonite uses the outer-most pair of `{}`s to handle block-input, whereas the standard REPL does not (it uses `:paste` instead). Thus the standard REPL doesn't need to support access modifiers in blocks, but we should
