### ISSUE TITLE
Is the exclude syntax for the REPL documented?

### ISSUE THREAD

**Issue by mslinn** [lihaoyi/Ammonite#533]
If you want Ammonite to exclude multiple transitive dependencies, separate them with commas, like this:

    import $exclude.`maven-group1:maven-id1`, $ivy.`maven-group2:maven-id2:optionalVersion`, $ivy.`maven-group3:maven-id3`

Notice that the first transitive dependency was prefaced with `$exclude`, while the remainder were prefaced with `$ivy`. I have not found documentation on this syntax; this is merely what seems to work. Is there documentation on this? Have I correctly phrased the explanation?

**Comment by alexarchambault** [comment]
@mslinn It's something you must have seen in [jupyter-scala](https://github.com/alexarchambault/jupyter-scala) or its underlying [modified Ammonite](https://github.com/alexarchambault/ammonium). It's specific to them for now.

The implem in them depends on coursier, which is not used by Ammonite, although @lihaoyi expressed some interest for it (after its 1.0 release). It might be possible to have an implementation with Ivy that Ammonite currently used though.

**Comment by mslinn** [comment]
@alexarchambault Thank you for your quick reply. The `$exclude` syntax is undocumented and I think perhaps inconsistent. To be consistent, the first excluded transitive dependency should mention `$ivy`, or is `$ivy` a default?

    import $exclude.$ivy.`maven-group1:maven-id1`, $ivy.`maven-group2:maven-id2:optionalVersion`, $ivy.`maven-group3:maven-id3`

Ammonium has no documentation regarding how it differs from Ammonite. Some documentation on this syntax, and any other user-visible changes would be helpful.
