### ISSUE TITLE
Loading jar file in script via interp.load.cp does not work properly

### ISSUE THREAD

**Issue by danbills** [lihaoyi/Ammonite#546]
after running interp.load.cp([valid Path]) I am unable to use classes from Jar file.

I tried the same code in Repl and it works as expected.

I also printed out repl.sess.frames.head.classpath and it shows the jar file in the classpath, as expected.

Unfortunately when I try to import or use classes it simply says "value not found" on root package name.

code I'm running:
```
import $ivy.`com.google.protobuf:protobuf-java:3.1.0`

val path = java.nio.file.FileSystems.getDefault().getPath("/home/dan/speech/jsoundProto/target/scala-2.10/jsoundproto_2.10-0.1-SNAPSHOT.jar")

val x = ammonite.ops.Path(path)

interp.load.cp(x)

println(repl.sess.frames.head.classpath)

//FAILS HERE
val x = billco.sound.Javasound.MixerInfo.newBuilder

println("done")
```

**Comment by foxlog** [comment]
No problem in my Mac OS X.

val path = java.nio.file.FileSystems.getDefault().getPath("/tmp/ojdbc14.jar")
val x = ammonite.ops.Path(path)
interp.load.cp(x)

oracle.jdbc.driver.Const.BUILD_DATE

//res7: String = "Sat_Feb__2_11:39:35_PST_2008"

**Comment by danbills** [comment]
That's strange, I'm on Mac OS X.

I verified w/ another jar (scala parser combinators):
```
val path = java.nio.file.FileSystems.getDefault().getPath("/tmp/scala-parser-combinators_2.12-1.0.5.jar")
val x = ammonite.ops.Path(path)
interp.load.cp(x)

import scala.util.parsing.combinators.RegexParsers //No package parsing found in scala.util
```

**Comment by danbills** [comment]
Also confirmed on LInux java 8

**Comment by lihaoyi** [comment]
You need to put a `@` between your `interp.load.cp` and your `import`, as documented http://www.lihaoyi.com/Ammonite/#Multi-stageScripts
