### ISSUE TITLE
Ammonite Repl does not support \u

### ISSUE THREAD

**Issue by Atry** [lihaoyi/Ammonite#548]
```val `a\u0060 = 1``` is a valid Scala expression and can be compiled in Official Scala REPL:

```
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_102).
Type in expressions for evaluation. Or try :help.

scala> val `a\u0060 = 1
a: Int = 1
```

However, Ammonite Repl does not support it:

```
Welcome to the Ammonite Repl 0.8.1
(Scala 2.12.1 Java 1.8.0_102)
@ val `a\u0060 = 1 
SyntaxError: found "`a\\u0060 = 1", expected Binding ~ InfixPattern | InfixPattern | VarId at index 4
val `a\u0060 = 1
    ^
```

**Comment by lihaoyi** [comment]
This is a limitation that is unlikely to ever go away, due to the way the parser works, unfortunately. Although I've tried to support every weird edge case of the Scala language, some things are just to weird and too edge for me to think it's worth supporting
