### ISSUE TITLE
Running code in object-initializers makes things slow

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#55]
Apparently code directly inside an `object Foo{ ... }` block doesn't get JITed, and the commands that you enter into Ammonite all are run that way. This seems to result in a 10x slowdown in the rare-ish case you're doing intensive work directly in that block.

```scala
@ (() => {val start = System.currentTimeMillis(); var i = 1L; while(i < 1000000000L) i += (i % 2) + 1; System.currentTimeMillis() - start})()
res13: Long = 1065L
@ {val start = System.currentTimeMillis(); var i = 1L; while(i < 1000000000L) i += (i % 2) + 1; System.currentTimeMillis() - start}
res14: Long = 11464L
```

A solution would be to lift all `var`/`val`/`lazy val`/`<expr>` statements automatically into `(() => ...)()` in the `Preprocessor`.

**Comment by som-snytt** [comment]
This is a common problem in typesafe repl, and the reason for `-Yrepl-class-based` or whatever.

**Comment by lihaoyi** [comment]
Fixed, thanks @laci37!

**Comment by som-snytt** [comment]
There's another take on scala/scala to use App, where DelayedInit solves the init problem (which is similar to this fix).

https://github.com/scala/scala/pull/4349
