### ISSUE TITLE
Ammonite fails to recognize lazy concatenation operator for Streams

### ISSUE THREAD

**Issue by saniyatech** [lihaoyi/Ammonite#554]
I am using Ammonite REPL version 0.8.0.

I pasted the following code in Ammonite shell:

```
val fact:Stream[BigInt] = 
   1 #:: 
   fact.zip(
        Stream.from(2))
   .map(x => x._1 * x._2)
```

Ammonite gives error on the second line (specifically the concatenation operator): 
```cmd0.sc:2: value #:: is not a member of Int```

I started the Scala REPL and pasted the same code. It works fine. The Scala REPL is using Scala version 2.11.8.

**Comment by lihaoyi** [comment]
You need to wrap it in parens otherwise statement-inference does the wrong thing

```scala
val fact:Stream[BigInt] = {
   1 #:: 
   fact.zip(
        Stream.from(2))
   .map(x => x._1 * x._2)
}
```

Unfortunate but unlikely to ever get fixed
