### ISSUE TITLE
Parallel map hangs indefinitely

### ISSUE THREAD

**Issue by z-chen** [lihaoyi/Ammonite#556]
I'm on Ammonite 0.8.1 (Scala 2.12.1 Java 1.8).

Running a simple parallel map like `(1 to 10).par.map(_+1)` seems to hang indefinitely (or at least for more than 4 minutes). Returns a ParVector as expected in SBT console.

**Comment by jhnsmth** [comment]
It's not an Ammonite issue.  See https://issues.scala-lang.org/browse/SI-9824

**Comment by z-chen** [comment]
Great, thanks @jhnsmth.

**Comment by eptx** [comment]
work around...
```
object foo {
	def bar = (0 until 5).par.foreach { i => println(i.toString)}
}

foo.bar
```

**Comment by eptx** [comment]
work around...
```
object foo {
	def bar = (0 until 5).par.foreach { i => println(i.toString)}
}

foo.bar
```

**Comment by FelAl** [comment]
'''
@ val result = Array(1, 2, 3, 4,4,5,6,7,54,543, 2,345,3454).par.fold(0)((sum, value) => sum + value) 
^C
Interrupted! (`repl.lastException.printStackTrace` for details)

@ lazy val result = Array(1, 2, 3, 4,4,5,6,7,54,543, 2,345,3454).par.fold(0)((sum, value) => sum + value) 
result: Int = <lazy>

@ result 
res46: Int = 4430
'''

**Comment by hepin1989** [comment]
```
 import scala.concurrent._, duration._, ExecutionContext.Implicits.global
import scala.concurrent._
import duration._
import ExecutionContext.Implicits.global
scala> Await.result(Future(1), Duration("1s"))
```
workaround

```
lazy val future = Future(1)
```

**Comment by coreyoconnor** [comment]
In case anybody runs across this in 2022: Yes, this issue still exists. 
The Scala issue linked by @jhnsmth is closed. I don't know if the issue is still the same.
For what it's worth: I like @FelAl 's solution of using `lazy val` instead of `val`. Which is a nice and easy work around IMO.
