### ISSUE TITLE
bad link in releases page for amm executable

### ISSUE THREAD

**Issue by thunderc90** [lihaoyi/Ammonite#560]
http://www.lihaoyi.com/Ammonite/#0.8.2

Releases page has this URL for retrieving amm: https://git.io/vMFBZ

This currently downloads:
Not Found

Assuming the URL is wrong/expired but not certain.

**Comment by lihaoyi** [comment]
huh somehow my 0.8.2 tag commit disappeared... what on earth

**Comment by lihaoyi** [comment]
Somehow it ended up as an orphaned commit (???) let's see if https://travis-ci.org/lihaoyi/Ammonite brings it back...

**Comment by lihaoyi** [comment]
Seems to be fixed now
