### ISSUE TITLE
Add support for key-based authentication to SshdRepl

### ISSUE THREAD

**Issue by mslinn** [lihaoyi/Ammonite#564]
After poking around, it seems there might be limited key-based support after all. I found docs that said there was no such support, BTW: "Currently it doesn't supports key-based auth, and password-based auth is notoriously weak."

One limitation is that the host key is assumed to be in a physical file, not embedded in a resource like a jar file.

```
import ammonite.ops.Path.home
import ammonite.ops.resource

SshServerConfig(
    address = "localhost", // or "0.0.0.0" for public-facing shells
    port = 22222, // Should be > 1024
    username = "repl",
    password = "",
    ammoniteHome = home,
    hostKeyFile = Some(resource/"host.key") // this is not supported yet
)
```

Currently `SshServerConfig` requires `password` to be specified. This should be an optional parameter, and if omitted, password authentication should be disabled.

**Comment by lihaoyi** [comment]
Merged as part of https://github.com/lihaoyi/Ammonite/pull/594, I think that should support your use case?

**Comment by mslinn** [comment]
Looks promising, a usage example in the docs would also help, thanks!

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out
