### ISSUE TITLE
Akka HTTP microservice example no longer uses Ammonite

### ISSUE THREAD

**Issue by mslinn** [lihaoyi/Ammonite#565]
The Ammonite docs say "sshd repl server is embedded in the Akka HTTP microservice example". That might have been true in the past, but it is no longer true.

**Comment by lihaoyi** [comment]
I don't mean that the github repo online uses Ammonite, I mean the screenshot shows how you can add Ammonite to the github repo yourself to expose a debugging endpoint you can SSH into...
