### ISSUE TITLE
Messages about compiling files should go to stderr rather than stdout

### ISSUE THREAD

**Issue by nessus42** [lihaoyi/Ammonite#574]
Ammonite messages about compiling files should go to stderr rather than stdout.

Yes, I know I can silence such output with "-s", but sometimes it is useful to see such output (so, e.g., I know why the script is running slowly), without having it ruin the contents of the output file when you run a script like so:
```
$ amm foo.sc > output.txt
```
The Ivy output currently all goes to stderr (which is where it should go), so having the compiling messages go to the same place would also be more consistent.

**Comment by DavidPerezIngeniero** [comment]
+1

**Comment by lihaoyi** [comment]
Yeah that's a great idea.
