### ISSUE TITLE
Feature not to add some lines to history

### ISSUE THREAD

**Issue by emanresusername** [lihaoyi/Ammonite#576]
Maybe something like [HIST_IGNORE_SPACE in zsh](http://zsh.sourceforge.net/Doc/Release/Options.html) because auto reverse history substring search with somebody looking over your shoulder can be a dangerous game 😅 
e.g.
- "oh let me show you how to connect to a `port` in ammonite, it's in my history somewhere"
- types `por` and starts hitting up arrow
- things seen that can't be unseen

(i guess the classic passwords exposed example works here too... but that one was more entertaining :) )

**Comment by lihaoyi** [comment]
I think this is probably not common enough to be worth doing in Ammonite's core. If you want to, you can write your own helper function that goes through `~/.ammonite/history` and filters it all you want, and any changes should immediately take effect in the REPL
