### ISSUE TITLE
initial commands

### ISSUE THREAD

**Issue by siddhartha-gadgil** [lihaoyi/Ammonite#58]
It will be convenient for me to import a bunch of stuff in the ammonite REPL, but "initialCommand in console" is ignored inside the ammonite REPL

**Comment by lihaoyi** [comment]
How are you running Ammonite?

**Comment by siddhartha-gadgil** [comment]
In sbt, starting project/test:console

**Comment by siddhartha-gadgil** [comment]
In the usual console, my imports work.

In my build.sbt I have:
initialCommands in console := """ammonite.repl.Repl.main(null); import
provingground._ ; import HoTT._"""
I also tried putting the ammonite.repl.Repl.main(null) command last.

**Comment by lihaoyi** [comment]
Yeah that's not going to work =/ we don't grab things from the surrounding scope, even though I'd like to at some point. https://github.com/lihaoyi/Ammonite/pull/56 makes predefs slightly-more-but-not-quite possible, and with a bit of work should be sufficient

**Comment by lihaoyi** [comment]
Fixed in d57ffac384f68c927b809c01b1f31c41d3ecb4c7, will push an updated version 0.3.0 some time

**Comment by siddhartha-gadgil** [comment]
Thanks.
