### ISSUE TITLE
load.ivy() doesn't work

### ISSUE THREAD

**Issue by ganeshchand** [lihaoyi/Ammonite#582]
I am using 0.8.2 ammonite version. I have imported ammonite.ops._

```
 load.ivy("com.lihaoyi"` %% "scalatags" % "0.6.2")
cmd8.sc:1: not found: value load
val res8 = load.ivy("com.lihaoyi" %% "scalatags" % "0.6.2")
           ^
Compilation Failed
```
I have also tried 
`interp.load.ivy("com.lihaoyi" %% "scalatags" % "0.6.2")`

**Comment by feliperazeek** [comment]
same issue for me

**Comment by kamatsuoka** [comment]
+1, using Scala 2.11 version.

**Comment by lihaoyi** [comment]
You need `interp.load.ivy` since 0.7.0 I believe; though this has largely been superseded by the `import $ivy` syntax as described in https://www.lihaoyi.com/Ammonite/#0.7.0

**Comment by ganeshchand** [comment]
I just downloaded ammonite 0.85 and tried ```$interp.load.ivy("com.lihaoyi" %% "scalatags" % "0.6.2")``` and it worked! Thanks

**Comment by JWDobken** [comment]
@ganeshchand I guess @lihaoyi is suggesting to run:

```sc
import $ivy.`com.lihaoyi:scalatags:0.6.2`
```
