### ISSUE TITLE
Function Parameter suggestion (a la Intellij)

### ISSUE THREAD

**Issue by Akinevz** [lihaoyi/Ammonite#584]
Ctrl+P in Intellij shows a pop-up with a list of all of the parameters and their types that are applicable for the currently typed function.

Suggestion: Can be implemented like tab completion, where pressing the shortcut will for each declaration of the function print its arguments with their types.

Example: entering `new java.io.File(` then pressing the shortcut, without sources present
Example output: 
``` scala
new File(file:File, s:String)
new File(s:String)
new File(s:String, file:File)
new File(uri:URI)
```

Example: entering `new java.io.File(` then pressing the shortcut, with sources present
Example output: 
``` scala
new File(parent:File, child:String)
new File(pathname:String)
new File(parent:String, child:File)
new File(uri:URI)
```

**Comment by lihaoyi** [comment]
This already happens with functions:

```scala
@ System.out.println
def println(): Unit                               def println(x$1: Double): Unit
def println(x$1: Any): Unit                       def println(x$1: Float): Unit
def println(x$1: Array[Char]): Unit               def println(x$1: Int): Unit
def println(x$1: Boolean): Unit                   def println(x$1: Long): Unit
def println(x$1: Char): Unit                      def println(x$1: String): Unit
```

it doesn't work on constructors, but is part of the larger issue https://github.com/lihaoyi/Ammonite/issues/275
