### ISSUE TITLE
Docs on streamed reading of std.in

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/Ammonite#588]
It would be nice to see some docs that will explain how to make something like:
```bash
while read LINE; do
   echo ${LINE}    
done
```
That is common in many scripts that receive streamed input (for instance from Spark's pipe's)

**Comment by lihaoyi** [comment]
You should be able to use standard Java APIs to do this; a while loop with `BufferedReader#readLine` on `System.in` works great
