### ISSUE TITLE
Publish for 2.11.9

### ISSUE THREAD

**Issue by stanch** [lihaoyi/Ammonite#589]
Pretty please :)

**Comment by stanch** [comment]
Missed that! From a quick search I don’t see where that was publicly announced, but indeed the release was not announced either...

**Comment by stanch** [comment]
It seems that `2.11.10` is also [DOA](https://github.com/scala/scala-dev/issues/359#issuecomment-293436670) :( So we are waiting for `2.11.11`.

**Comment by joegallo** [comment]
`2.11.11` [is out](https://www.scala-lang.org/download/2.11.11.html).

**Comment by stanch** [comment]
I see it’s published for both `2.11.1` and `2.12.2`.

**Comment by joegallo** [comment]
Thanks!
