### ISSUE TITLE
Parallel collections no longer work since 0.8.1

### ISSUE THREAD

**Issue by ErkiDerLoony** [lihaoyi/Ammonite#590]
For versions 0.8.1 and 0.8.2 parallel collections no longer work. Previously (0.8.0) we got
```
Loading...
Compiling LoadedPredef.sc
Welcome to the Ammonite Repl 0.8.0
(Scala 2.11.8 Java 1.8.0_66)
@ List(1,2,3).par.foreach(println)
2
1
3

@ Bye!
```

Now (0.8.1 and 0.8.2) the call
```
Loading...
Compiling LoadedPredef.sc
Welcome to the Ammonite Repl 0.8.1
(Scala 2.12.1 Java 1.8.0_66)
@ List(1,2,3).par.foreach(println)
```
never terminates. Attached you will find a stack trace of the hanging program version 0.8.1.
[trace.txt](https://github.com/lihaoyi/Ammonite/files/926879/trace.txt)

**Comment by jhnsmth** [comment]
It's a regression in scala 2.12, see my comment at #556. [here](http://www.lihaoyi.com/Ammonite/#OlderScalaVersions) you can find the latest version for scala 2.11. it's should work fine.

**Comment by ErkiDerLoony** [comment]
Oh, thanks. I did not find that issue in my casual search. :)
