### ISSUE TITLE
Add scala-native crossbuild support for ammonite libs

### ISSUE THREAD

**Issue by bbarker** [lihaoyi/Ammonite#593]
For development of fast command line utilities, also good for distributing to non Scala users.

**Comment by lihaoyi** [comment]
Dependent on https://github.com/lihaoyi/Ammonite/issues/437. 

That would let us separate the compile-time logic and run-time execution of Ammonite scripts, which is a pre-requisite if we want the run-time execution to be under Scala Native while compile-time logic remains under Scala-JVM

**Comment by lihaoyi** [comment]
I'm going to close this for now since without #437 there's not much you can do here
