### ISSUE TITLE
suggestion to make value proposition of Ammonite much more explicit on website

### ISSUE THREAD

**Issue by jordanst3wart** [lihaoyi/Ammonite#598]
Hi Haoyi,

I think you can make the value proposition of Ammonite much more explicit on your website. I think this could make the adoption of Ammonite much more enticing. I think right now you are pushing "scala scripting", which relies on the user to know the value of scala. I think you should be pushing the advantages of "type interference (or type safety)", and how that can give a programmer more confidence in their code.

I think you talked about this in all of your videos, but it doesn't seem to translate onto the Ammonite webpage.

I think you should consider changing parts of the Ammonite website, like the first few lines:
```
Ammonite lets you use the Scala language for scripting purposes: in the REPL, as scripts, as a library to use in existing projects, or as a standalone systems shell.
```

To:
```
Ammonite lets your scripts have type safety by using the Scala language in a concise way. You can use Ammonite in the REPL, as scripts, as a library to use in existing projects, or as a standalone systems shell.
```

I think currently you mention things like "letting you seamlessly mix system operations with real code", "Rock solid shell scripting", and "avoid the overhead of working in multiple languages", which I don't think captures the value that Ammonite can add. Whereas the compelling things you mention in your videos of Ammonite don't seem to make much of an appearance.

I think you should also consider changing the video at the top of the website to this video, started around here: https://youtu.be/dP5tkmWAhjg?t=88
I think that shows the valued add better.

I'm happy to help you work on these changes, submit PRs for you to review, or talk about them more if you would like.

Jordan

**Comment by lihaoyi** [comment]
I'm actually happy with the way things are now. In particular, I think the current version better targets existing Scala programmers, rather than people new-to-Scala that your changed version targets.

**Comment by jordanst3wart** [comment]
Thanks for replying! I was actually trying to target "programmers", who have to do work with bash, or shell, rather than "Scala programmers". Maybe I didn't explain that well enough.

I don't really think Scala programmers, who are probably writing some REST API, actually need a concise file system library, whereas if you take the inverse, I think bash programmers would like a more reliable language.

In that way, I think Ammonite becomes more of a DSL, with specialized capabilities, trying to fix a problem, rather than a nice extension of the scala language.
