### ISSUE TITLE
no ammonite-core in maven repository

### ISSUE THREAD

**Issue by ezoerner** [lihaoyi/Ammonite#6]
I was trying to get this to work, but it seems there is an ammonite jar in maven, but no ammonite-core, and depending on the ammonite jar doesn't seem to work,

**Comment by lihaoyi** [comment]
Uhh try `  "com.lihaoyi" %% "ammonite" % "0.1.4",`? Clearly I botched the readme

**Comment by ezoerner** [comment]
When I saw that only "ammonite" was in maven and not "ammonite-core", I actually did try that, but had problems getting that to work. I didn't have the time to pursue it any further, but i will play around with it some more later and get back to you.

**Comment by ezoerner** [comment]
The problem now seems to be getting the example in the README file to compile, as it appears the imports are not complete.

The first problem is that processWorkingDir apparently needs `import ammonite.all.processWorkingDir`.

After that, several of the `|` type operators can't be found.
I haven't figured out yet what imports are missing for this.

    Error:(21, 18) value | is not a member of Seq[ammonite.ops.Path]
    ls! wd/'folder2 | mv{case r"$x.scala" => s"$x.java"}
                    ^
    Error:(21, 28) value r is not a member of StringContext
    ls! wd/'folder2 | mv{case r"$x.scala" => s"$x.java"}
                              ^
    Error:(21, 28) value r is not a member of StringContext
    ls! wd/'folder2 | mv{case r"$x.scala" => s"$x.java"}
                              ^
    Error:(27, 13) value |? is not a member of Seq[ammonite.ops.Path]
    ls.rec! wd |? (_.ext == "scala") | read.lines | (_.size) sum
               ^
    Error:(30, 9) value |? is not a member of Seq[ammonite.ops.Path]
    ls! wd |? (_.ext == "js") | read |> write! wd/'target/"bundle.js";}
           ^

It would be a good idea if you tested your sample code in the README file and tried to compile it using the published jar dependency. This will be the first impression for people trying out your library.

Let me know if you are unable reproduce these problems, and we can work together to figure out what is different about my environment.

**Comment by lihaoyi** [comment]
You need to add `import ammonite.all._`

Yeah it would be nice if readmes were always consistent. Too bad we don't live in candyland =P

**Comment by ezoerner** [comment]
I actually had already tried that as well, and ran into other compiler errors. It looks like if you remove `import ammonite.ops._` and *only* use `import ammonite.all._`, then that example does compile.

**Comment by lihaoyi** [comment]
Ok cool. I've fixed the readme. Sorry for the runaround!

**Comment by lihaoyi** [comment]
At some point I'll port the readme to http://lihaoyi.github.io/Scalatex/ to ensure it will always compile into the future.
