### ISSUE TITLE
Conflicting collector combinations in option list; built-in JAVA_OPTS

### ISSUE THREAD

**Issue by insdami** [lihaoyi/Ammonite#602]
Hi,

Could be possible make JAVA_OPTS externally configurable in such a way that your environment doesn't conflict with the built-in options?

I have `-XX:+UseConcMarkSweepGC` in my env which is conflicting with the ones in the wrapper and you get the following error when you try to start ammonite.

```shell
Conflicting collector combinations in option list; please refer to the release notes for the combinations allowed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by lihaoyi** [comment]
Use `java -jar $(which amm)` if you want to pass in your own JVM opts

**Comment by gmkmanoj** [comment]
comment duplicate GC JAVA_OPTION in setenv.sh
