### ISSUE TITLE
Resolution of local Maven artefacts does not work

### ISSUE THREAD

**Issue by mduerig** [lihaoyi/Ammonite#611]
Since the move to coursier in 0.9 resolving artefacts only published to the local Maven repository does not work anymore unless I add

`interp.repositories() ++= Seq(coursier.MavenRepository("file://" + java.lang.System.getProperties.get("user.home") +  "/.m2/repository/"))`

And even then I have to explicitly specify the version (e.g. `1.3-SNAPSHOT`) where before I could simply us `latest.integration`.

**Comment by lihaoyi** [comment]
@mduerig Feel free to add those artifacts to this listing https://github.com/lihaoyi/Ammonite/blob/7b18fcc2cb935c30a07c563e8d6dfd98dd6ec94e/amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala#L73-L76

**Comment by mduerig** [comment]
Not sure whether this is the right approach. It is rather a work around relying on a specific location of the local Maven cache.

**Comment by lihaoyi** [comment]
I don't know much about maven, but having a hard-coded list of "places jars are most likely to resolve from" seems like a reasonable thing to do. We already hardcode sonatype and ivyLocal, what's a few more? 😛 if the list starts getting large/unwieldy then can we can fix it, but if it's just 1 or 2 then it's probably fine

**Comment by mduerig** [comment]
Pull request for the suggested change: https://github.com/lihaoyi/Ammonite/pull/612

**Comment by lihaoyi** [comment]
Closing this, as discussed in https://github.com/lihaoyi/Ammonite/pull/612#issuecomment-303522406
