### ISSUE TITLE
browse() always shows ellipsis (...)

### ISSUE THREAD

**Issue by mduerig** [lihaoyi/Ammonite#613]
Since 0.9 e.g. `browse(List(1,2,3))` only shows `...`.

**Comment by lihaoyi** [comment]
Ahh yet another pprint regression.

[browse](https://github.com/lihaoyi/Ammonite/blob/88cbd8a9f04bf49e83010c82486a596d590008d5/amm/runtime/src/main/scala/ammonite/runtime/tools/Tools.scala#L232) should be changed to handle the default arguments the same way a [show](https://github.com/lihaoyi/Ammonite/blob/88cbd8a9f04bf49e83010c82486a596d590008d5/amm/repl/src/main/scala/ammonite/repl/ApiImpls.scala#L98-L114)

**Comment by piotrkwiecinski** [comment]
I can grab this one if you haven't started @mduerig

**Comment by lihaoyi** [comment]
@piotrkwiecinski I got a fix out already, I think, lemme push it and see if CI is green. `show` was borked too in a similar way

**Comment by lihaoyi** [comment]
If it's green i'll tag it as 0.9.3

**Comment by mduerig** [comment]
Thanks for fixing this so quickly!
