### ISSUE TITLE
Support for resolving latest.release of artifacts 

### ISSUE THREAD

**Issue by mduerig** [lihaoyi/Ammonite#614]
Before moving to Coursier for resolving dependencies it was possibly to e.g.

    import $ivy.`group-id:artifact-id:latest.integration`

to fetch the latest version. This has now gone. Please bring it back once https://github.com/coursier/coursier/issues/209 is resolved.

**Comment by mardukbp** [comment]
The issue you referred to has been solved. Ammonite 1.6.9 supports latest.integration and latest.release. This issue can be closed.
