### ISSUE TITLE
sbt run ammonite immediately exit

### ISSUE THREAD

**Issue by liaowang11** [lihaoyi/Ammonite#615]
Config sbt according [Doc](http://www.lihaoyi.com/Ammonite/#Ammonite-REPL)
``` scala
sourceGenerators in Test += Def.task {
  val file = (sourceManaged in Test).value / "amm.scala"
  IO.write(file, """object amm extends App { ammonite.Main().run() }""")
  Seq(file)
}.taskValue

libraryDependencies += "com.lihaoyi" %% "ammonite" % "0.9.3" % "test" cross CrossVersion.full
```
When run `sbt test:run-main amm` or `sbt test:run, ammonite starts up and immediately exit with _Bye!_.
``` shell
❯ sbt test:'run-main amm'                                                                                                                                                                             
[info] Loading global plugins from /home/wliao/.sbt/0.13/plugins
[info] Loading project definition from /home/wliao/Fiddle/scala-playground/project
[info] Set current project to scala-playground (in build file:/home/wliao/Fiddle/scala-playground/)
[info] Running amm 
[info] Welcome to the Ammonite Repl 0.9.3
[info] (Scala 2.12.2 Java 1.8.0_131)
[info] If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ Bye!
[success] Total time: 5 s, completed May 25, 2017 5:48:14 PM

```

**Comment by piotrkwiecinski** [comment]
@liaowang11 do you have fork in Test := true in your build.sbt try to use fork in (Test, run) := false? Similar thing was mentioned as workaround the other day on gitter.

**Comment by liaowang11** [comment]
Fixed by setting `fork` to `false`, thanks.

**Comment by simlei** [comment]
If you need fork set to true, you can additionally set
```
connectInput := true
outputStrategy := Some(StdoutOutput)
```
and it will work (forked JVMs by default have no inputstream and log to the sbt output pipes by default)
see [Forking](http://www.scala-sbt.org/1.x/docs/Forking.html#Configuring+output)

**Comment by fooblahblah** [comment]
@simlei Thanks that works great. The only limitation I've found is the colorized repl output is missing, which I can live without.
