### ISSUE TITLE
Ammonite parameter conventions out of alignment with common interpreters such as bash/Python/Ruby

### ISSUE THREAD

**Issue by timcharper** [lihaoyi/Ammonite#618]
In version 0.9.0, the argument passing behavior of Ammonite was changed in order to support script arguments directly following the script name. This particular functionality is compatible with other interpreters.

What is not expected, however, is:

- inability to provide ammonite parameters prior to the script in question
- the use of `--` is not consistent with other interpreters (script is the first argument following the `--`)

**Comment by timcharper** [comment]
After looking at the code, it appears that the file is expected to go first for args parsing.

This is problematic because it no longer enables us to specify `-s` in the shebang.

```
#!/usr/bin/env amm -s
```

**Comment by timcharper** [comment]
Also, the help screen here does not match the arg parsing behavior:

```
14:41 $ amm --help
Error: Unknown option --help
ammonite 0.9.5
Usage: ammonite [options] [<args>...]

  -p, --predef <value>     Any commands you want to execute at the start of the REPL session
  --no-default-predef      Disable the default predef and run Ammonite with the minimal predef possible
  --no-remote-logging      Disable remote logging of the number of times a REPL starts and runs commands
  -b, --banner <value>     Customize the welcome banner that gets shown when Ammonite starts
  -c, --code <value>       Pass in code to be run immediately in the REPL
  <args>...                Any arguments you want to pass to the Ammonite script file
  -h, --home <file>        The home directory of the REPL; where it looks for config and caches
  -f, --predef-file <value>
                           Lets you load your predef from a custom location
  -s, --silent             Make ivy logs go silent instead of printing though failures will still throw exception
  --repl-api               Lets you run a script with the `repl` object present; this is
normally not available in scripts and only provided in the
interactive REPL
```

**Comment by timcharper** [comment]
It appears as if ammonite args following a scala script are completely ignored.

**Comment by timcharper** [comment]
Pull request is here: https://github.com/lihaoyi/Ammonite/pull/619

**Comment by lihaoyi** [comment]
Fixed by https://github.com/lihaoyi/Ammonite/commit/24c424495d9ed012a065dd6adbc17538432a63d5
