### ISSUE TITLE
Use of Terminal.readLine in scripts

### ISSUE THREAD

**Issue by aquamatthias** [lihaoyi/Ammonite#625]
I would like to use `Terminal.readLine` in my scripts instead of `Console.in.readLine`.
My (stupid) simple approach with:
```scala
Terminal.readLine(prompt, new InputStreamReader(System.in), new OutputStreamWriter(System.out), BasicFilters.all )
``` 
works, but prints an extra space after each typed character.
Example entering `aaa`:
```
$> aaa<space><space><space><prompt>
```
which makes editing the input impossible.

What is the easiest/suggested way to use the Terminal?

**Comment by lihaoyi** [comment]
This isn't really an issue; questions should go to the gitter chat room.

If you'd like to get `Terminal.readLine` working, I suggest you start off with the test terminal https://github.com/lihaoyi/Ammonite/blob/master/terminal/src/test/scala/ammonite/terminal/TestMain.scala#L21, *outside* of an Ammonite script, and work from there.

I don't doubt you'll find something that doesn't work, but the test terminal (and of course the one inside Ammonite itself) *does* work, so hopefully if you start from there and hit and issue, you'll be able to pinpoint exactly what is causing you grief ^_^

**Comment by aquamatthias** [comment]
@lihaoyi Thanks for the fast response and the pointer. Will use gitter the next time.
