### ISSUE TITLE
Ammonite eagerly evaluates lazy list

### ISSUE THREAD

**Issue by chuwy** [lihaoyi/Ammonite#627]
Hello,

Just noticed all my Scala `Stream` evaluated eagerly in Ammonite, right after I build them:

```scala
Welcome to the Ammonite Repl 1.0.0-RC6
(Scala 2.12.2 Java 1.8.0_60)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ def unfold[A, B](start: B)(f: B => Option[Tuple2[A,B]]): Stream[A] = f(start) match {
    case Some((elem, next)) => elem #:: unfold(next)(f)
    case None => Stream.empty[A]
  }
defined function unfold
@ unfold(0) { (x: Int) => if (x < 10) Some((x + 1, x + 1)) else None  }
res1: Stream[Int] = Stream(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
```

Expected output:

```scala
Welcome to Scala 2.11.11 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions for evaluation. Or try :help.

scala> unfold(0) { b => if (b > 10) None else Some((b, b + 1)) }
res3: Stream[Int] = Stream(0, ?)
```

Bug also appears in `Ammonite Repl 0.9.3 (Scala 2.11.11 Java 1.8.0_60)`

**Comment by lihaoyi** [comment]
This is expected behaviour. Ammonite will evaluate enough elements to either print a single line, or to lay things out vertically and have it exceed the truncation height. If you want to customize this, you can override the `repl.pprinter()` with a custom `additionalHandlers` to special-case `Stream`

**Comment by chuwy** [comment]
Ah, thanks. I searched for "lazy" in documentation and couldn't find any clues if this is known behavior.

**Comment by lihaoyi** [comment]
Yeah it's bitten people before. It's a bit unusual, but I don't really think it's a common enough problem to have special casing in master, especially given that it's easy to special-case yourself if desired. For "many" cases where your `Stream`s are non-side-effecting and non-exception-throwing, it also shouldn't cause any change in behavior, and it's nice to nicely peek at them
