### ISSUE TITLE
Calling `Main.run` with at least one bind throws an exception

### ISSUE THREAD

**Issue by AleksanderBG** [lihaoyi/Ammonite#633]
When calling `Main.run` with some binds, exceptions like this are thrown:
```
ArgsPredef.sc:3: value replArgs is not a member of ammonite.repl.FullReplAPI
      ammonite.repl.ReplBridge.value.replArgs(0).value.asInstanceOf[brightit.Client]
                                     ^
ArgsPredef.sc:7: value replArgs is not a member of ammonite.repl.FullReplAPI
      ammonite.repl.ReplBridge.value.replArgs(1).value.asInstanceOf[Option[brightit.Client]]
                                     ^
ArgsPredef.sc:11: value replArgs is not a member of ammonite.repl.FullReplAPI
      ammonite.repl.ReplBridge.value.replArgs(2).value.asInstanceOf[brightit.Project]
                                     ^
ArgsPredef.sc:15: value replArgs is not a member of ammonite.repl.FullReplAPI
      ammonite.repl.ReplBridge.value.replArgs(3).value.asInstanceOf[brightit.Project]
```

The direct cause of this is the code created here:
https://github.com/lihaoyi/Ammonite/blob/master/amm/repl/src/main/scala/ammonite/repl/Repl.scala#L37-L42

The field was removed at this point:
https://github.com/lihaoyi/Ammonite/commit/0999b06adf0800fd1c4a533bef805118bd467576#diff-ad435cc92aca934fed60e4203c2eb422L121
https://github.com/lihaoyi/Ammonite/commit/0999b06adf0800fd1c4a533bef805118bd467576#diff-a83ee5713b2b60f196e087ed5bb36c49L185

**Comment by lihaoyi** [comment]
Should be fixed in 1.0.0-RC7, when that goes out automatically in an hour or so
