### ISSUE TITLE
Don't show internal code to users

### ISSUE THREAD

**Issue by sschaef** [lihaoyi/Ammonite#64]
`val res6`, what is this? Where does it come from? Also, it may be possible to show nice emoticons with parentheses, but my mind can't handle them right now.
```scala
@ val xs = Seq(1)
xs: Seq[Int] = List(1)
@ xs foreach p
Compilation Failed
Main.scala:26: not found: value p
          val res6 = (xs foreach p)
                                 ^
```

**Comment by lihaoyi** [comment]
This should be an easy fix

**Comment by lihaoyi** [comment]
Fixed in https://github.com/lihaoyi/Ammonite/commit/b428626af71ae0d6f98cff0f4b98081ede332aef
