### ISSUE TITLE
`amm -w` throws `OutOfMemoryError`

### ISSUE THREAD

**Issue by dsebban** [lihaoyi/Ammonite#647]
```bash
Watching for changes to 2 files... (Ctrl-C to exit)
Compiling /Users/danielsebban/Project/scala-scripts/script.sc

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "system-scheduler-1"
java.lang.OutOfMemoryError: Java heap space
Uncaught error from thread [system-scheduler-1] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[system]
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
```

**Comment by lihaoyi** [comment]
What script is this? If your script is taking up tons of memory there's nothing Ammonite can do

**Comment by dsebban** [comment]
It's a script I wrote that use akka-http , the point is it does not run, I call the script without arguments  
```bash
Need to specify a subcommand to call when running scripts.sc

Available subcommands:
 
```
well it works ~10 times and then it stops working, maybe the cleanup between each watch iteration

**Comment by lihaoyi** [comment]
Are you shutting off your webserver after each run? If not it'll keep running in the background. You need to do the cleanup yourself, e.g. using `interp.beforeExitHooks`

**Comment by dsebban** [comment]
ok will try that , thnks
