### ISSUE TITLE
NullPointerException in sshd remote repl

### ISSUE THREAD

**Issue by ubolonton** [lihaoyi/Ammonite#659]
I'm trying to embed Ammonite, but got the following error (note that it "works" correctly with bad inputs).

```
Password authentication
Password:
Welcome to the Ammonite Repl 1.0.0
(Scala 2.12.1 Java 1.8.0_131)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ 1
java.lang.NullPointerException


@ x
cmd1.sc:1: not found: value x
val res1 = x
           ^
Compilation Failed
@
```
There is nothing in the log except for a line about ssh client connecting.

Any pointer on how to debug this? I would be happy to dive in and diagnose it.

**Comment by lihaoyi** [comment]
> Any pointer on how to debug this? I would be happy to dive in and diagnose it.

Minimize the problem, build a local version of Ammonite as described in the readme file, and start adding `println`s everywhere to see where the failure is coming from.
