### ISSUE TITLE
 pure pom maven artifacts not imported

### ISSUE THREAD

**Issue by bblfish** [lihaoyi/Ammonite#664]
I wonder if there may be a bug for importing pure pom maven artifacts like the [apache-jena-libs](http://jena.apache.org/download/maven.html#specifying-jena-as-a-dependency). 

It is easy to reproduce:

```scala
@ import $ivy.`org.apache.jena:apache-jena-libs:3.1.1`
Failed to load source dependencies
  not found: https://repo1.maven.org/maven2/org/apache/jena/apache-jena-libs/3.1.1/apache-jena-libs-3.1.1-sources.jar
Failed to load dependencies
  not found: https://repo1.maven.org/maven2/org/apache/jena/apache-jena-libs/3.1.1/apache-jena-libs-3.1.1.jar
```

The directory https://repo1.maven.org/maven2/org/apache/jena/apache-jena-libs/3.1.1/ contains only poms so of course coursier won't find the jars there.
The Apache web site does say:

> This will transitively resolve all the dependencies for you: jena-core, jena-arq, jena-tdb and jena-iri and their dependencies. Note the use of `<type>pom</type>` . **This does not work in all tools.** 

```xml
<dependency>
    <groupId>org.apache.jena</groupId>
    <artifactId>apache-jena-libs</artifactId>
    <type>pom</type>
    <version>X.Y.Z</version>
  </dependency>
```

**Comment by antonkulaga** [comment]
I confirm, I have the same problem with latest ammonite

**Comment by skontopo** [comment]
So, how is this issue resolved? I keep getting the same error with Jena 3.14.0:
`import $ivy.`org.apache.jena::apache-jena-libs:3.14.0``
