### ISSUE TITLE
Watch shellout stream

### ISSUE THREAD

**Issue by NeQuissimus** [lihaoyi/Ammonite#665]
I would like to "watch" continuous output from a command, essentially something like the following:

```scala
import ammonite.ops._
import ammonite.ops.ImplicitWd._ 
%%("docker", "logs", "-f", "kafka").chunks.foreach(println)
```

However, `Shellout.executeStream` only passes back a result once the command has finished.
Is there currently an easy way for me to achieve what I am trying?

Thank you

**Comment by lihaoyi** [comment]
Basically subsumed by https://github.com/lihaoyi/Ammonite/pull/717
