### ISSUE TITLE
Release for 2.12.3

### ISSUE THREAD

**Issue by milessabin** [lihaoyi/Ammonite#671]

**Comment by piotrkwiecinski** [comment]
It's on test branch: https://github.com/lihaoyi/Ammonite/commit/1ea8ed9658bab9d6cd48956767c0d5769428ca36

**Comment by lihaoyi** [comment]
just woke up and pushed to master, if things are green i'll tag it as 1.0.1

**Comment by lihaoyi** [comment]
1.0.1 is out
