### ISSUE TITLE
amm throws NPE on OpenJDK 9

### ISSUE THREAD

**Issue by PaulAtBanno** [lihaoyi/Ammonite#675]
The amm runtime Classpath system attempts to get the "sun.boot.class.path" property, which doesn't exist in OpenJDK 9, throwing a NullPointerException. I'm not sure what the appropriate workaround is, sorry!

**Comment by lihaoyi** [comment]
lol I don't know what the solution is either. Hopefully someone who knows something about Java 9 can chime in and enlighten us...

**Comment by PaulAtBanno** [comment]
OK, so as you might expect, especially if you've ever worked with OSGi, this has to do with the module system. In JRE/JDK 9, there is a new file system provider, "jrtfs," that apparently provides access to the classes used by the JRE/JDK itself in a principled way. [This post](http://www.jroller.com/andyl/entry/say_hello_to_jep_220) has some further information and [this code](http://www195.pair.com/mik3hall/JRTLister.java) is an example of using the file system.

There is also a [backport of jrtfs to Java 7](https://github.com/forax/jigsaw-jrtfs), but I don't know how useful that would be to Ammonite.

Hope this helps!

**Comment by lihaoyi** [comment]
Still doesn't work on Java 9. On the other hand, I couldn't get SBT to work on Java 9 either, so I'll probably wait until at least that is supported so Ammonite can be built

**Comment by pshirshov** [comment]
sbt 1.0.3 / scala 2.12.4 are working fine on j9

**Comment by gabrieljones** [comment]
`System.getProperty("sun.boot.class.path")` @ [Classpath.scala#L29](https://github.com/lihaoyi/Ammonite/blob/1.0.3/amm/runtime/src/main/scala/ammonite/runtime/Classpath.scala#L29) returns null

**Comment by francisdb** [comment]
This can be widened to OracleJDK as shown in #739

**Comment by francisdb** [comment]
I guess this can be closed?
