### ISSUE TITLE
support for vi editing mode.

### ISSUE THREAD

**Issue by mario-grgic** [lihaoyi/Ammonite#685]
Would it be possible to add vi-editing mode to Ammonite? It's a really good REPL, but using pedestrian editing makes it really hard to quickly edit code.

**Comment by lihaoyi** [comment]
Possible but I doubt I'll ever work on it, as a non-pro vim user.

I would gladly take a PR that implements some of the vim functionality though. Take a look at the `ammonite-terminal` subproject and see how it implements Readline-like and GUI-like editing. The same techniques can be used to implement vim-style editing
