### ISSUE TITLE
rm! doesn't delete directory recursively

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#689]
I execute:

    rm! home/'myFolder

and nothing gets deleted.
No error is reported.
The folder belongs to the current user, and has write permissions.  It contains subfolders and files.
Tested with Ammonite 1.0.1.

**Comment by piotrkwiecinski** [comment]
I just tested it on 1.0.2 on Debian 9:

```
@ ls! home/'Documents 
res14: LsSeq = 
'ammrmtest

@ ls! home/'Documents/'ammrmtest 
res15: LsSeq = 
'test        'test1       "text1.txt"  "text2.txt"

@ rm! home/'Documents
@ ls! home/'Documents 
java.nio.file.NoSuchFileException: /home/piotr/Documents
```

**Comment by lihaoyi** [comment]
Closing this unless you have any further info to share; it works in CI and it works on my laptop...
