### ISSUE TITLE
Ammonite called from a Linux service

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#690]
I have a bash script that in `/etc/init.d/` called `myService` that calls an Ammonite script.

When running:

    /etc/init.d/myService stop

the Ammonite script gets compiled and it runs ok.

But when doing:

    service myService stop

the Ammonite script gets recompiled and it fails for unrecognized Unicode characters like "⇒".
Why does get recompiled.

After researching a little, I've seen that service calls:

    env -i PATH=/sbin:/usr/sbin:/bin:/usr/bin TERM=xterm-256color SYSTEMCTL_IGNORE_DEPENDENCIES= SYSTEMCTL_SKIP_REDIRECT= /etc/init.d/myService stop

If I run it from the command line, it also fails.

Short `env` documentation:

    env: run a program in a modified environment
    env [OPTION]... [-] [NAME=VALUE]... [COMMAND [ARG]...]

The `-i` option makes run with an empty environment.

Why is Ammonite so sensitive to environment variables?
Why does it try to recompile?
Why doesn't detect the UTF-8 encoding of my source file when called in this way?

**Comment by DavidPerezIngeniero** [comment]
Workaround:

Old shebang line:

    #!/bin/bash
        exec amm "$0" `dirname $0` "$@"
   !#

new shebang line:

   #!/bin/bash
       LANG=en_US.UTF-8 exec amm "$0" `dirname $0` "$@"
   !#

Ammonite needs the LANG environment variable in order to treat source files as UTF-8.
Using CentOS 7 64 bits as operating system.

**Comment by lihaoyi** [comment]
Seems like a Java thing rather than an Ammonite thing
