### ISSUE TITLE
How to use Ammonite programmatically in another project as a customized REPL 

### ISSUE THREAD

**Issue by haifengl** [lihaoyi/Ammonite#693]
Thanks a lot for the nice project first! We have a project called [Smile] (https://github.com/haifengl/smile) that is a machine learning engine. We provide a Shell based on standard Scala REPL (extends ILoop). Ammonite looks like a much better alternative, especially on package management. What should we do with Ammonite as an embedded REPL? Thanks!

**Comment by lihaoyi** [comment]
http://ammonite.io/#Embedding

**Comment by haifengl** [comment]
Thanks! Can we customize the prompt? For example "smile> " instead of default "[@ ".

**Comment by lihaoyi** [comment]
Please ask questions on the gitter channel, not the issue tracker
