### ISSUE TITLE
`toStraam` or `Stream.cons` fails to build lazy Stream

### ISSUE THREAD

**Issue by cuzfrog** [lihaoyi/Ammonite#694]
```scala
@ def constr = {println("construct complex");500+1}
defined function constr
@ Stream.cons(1,Stream.cons(constr,Stream.empty)) 
construct complex
res4: Stream.Cons[Int] = Stream(1, 501)
```

in plain REPL:
```scala
scala> Stream.cons(1,Stream.cons(constr,Stream.empty))
res0: Stream.Cons[Int] = Stream(1, ?)
scala> res0(1)
construct complex
res2: Int = 501
```

ammonite version is 1.0.0

**Comment by lihaoyi** [comment]
This is intentional; Ammonite's pretty-printer forces and prints out the contents of streams, as far as they can fit in your terminal window. A bit awkward but that's the way it is

**Comment by cuzfrog** [comment]
Is it all right to tell pretty-printter to spare `Stream`?

**Comment by lihaoyi** [comment]
You can do that yourself by updating `repl.pprinter()` with a new `additionalHandlers` that handles `Stream` by delegating to `toString`
