### ISSUE TITLE
Unable to download a Maven dependency

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#695]
I have a simple script that imports Sikuli:

    import $ivy.`com.sikulix:sikulixapi:1.1.0`

When compiling my script, it complains:

```
Failed to resolve ivy dependencies:
  jxgrabkey:jxgrabkey:1.0 
    not found: /home/dd/.ivy2/local/jxgrabkey/jxgrabkey/1.0/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/jxgrabkey/jxgrabkey/1.0/jxgrabkey-1.0.pom
```

Effectively, I cannot access https://repo1.maven.org/maven2/jxgrabkey/jxgrabkey/1.0/jxgrabkey-1.0.pom, (I receive HTTP 404 Not found) but the artifact does exist:

https://mvnrepository.com/artifact/jxgrabkey/jxgrabkey/1.0

with this coordinates in SBT format:

    "jxgrabkey" % "jxgrabkey" % "1.0"

**Comment by DavidPerezIngeniero** [comment]
Workaround is to download manually the file in ~/.ivy2/local in the right format.

**Comment by sake92** [comment]
If you go to [mvnrepository link](https://mvnrepository.com/artifact/jxgrabkey/jxgrabkey/1.0) you posted and click the "View All" button, you'll see it points to a non-standard Maven repository.  
In Ammonite's [Ivy section](http://ammonite.io/#import$ivy) you can find how to add a custom repository: 
```scala
import coursier.core.Authentication, coursier.MavenRepository
interp.repositories() ++= Seq(MavenRepository(
   "https://labs.consol.de/maven/repository"
))
```
Then it works.
