### ISSUE TITLE
Change config directory to XDG standards

### ISSUE THREAD

**Issue by Jendrik3** [lihaoyi/Ammonite#696]
There is a standard where applications whould store user specific config, data and cache. The motivation is to remove all the dotfiles from the users home folder. Instead, applications should use folders inside $XDG_DATA_HOME, $XDG_CONFIG_HOME and $XDG_CACHE_HOME.

What do you think how much work this is?

**Comment by lihaoyi** [comment]
I'd say just pass in the `--home` flag when starting ammonite; no need to bake this into ammonite itself

**Comment by itaranto** [comment]
> I'd say just pass in the `--home` flag when starting ammonite; no need to bake this into ammonite itself

This won't work nicely because you need to define shell aliases (like `alias amm=amm --home ...`) and that's hard to do system-wide.

An environment variable `AMMONITE_HOME` would be a better solution IMO.
