### ISSUE TITLE
"object ? is not a member of package cats" after import "cats._" on Windows

### ISSUE THREAD

**Issue by glmars** [lihaoyi/Ammonite#700]
I run Ammonite on Windows with cmder by this instruction: https://github.com/lihaoyi/Ammonite/issues/119#issuecomment-317468917

After I import "cats._" any of the following commands lead to "Compilation Failed" error.

```scala
Welcome to the Ammonite Repl 1.0.2
(Scala 2.12.3 Java 1.8.0_144)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`org.typelevel::cats-core:1.0.0-MF`
import $ivy.$

@ import cats._
import cats._

@ exit
cmd2.sc:63: object ? is not a member of package cats
import _root_.cats.{
       ^
Compilation Failed
```

**Comment by lihaoyi** [comment]
Could you post this on the https://github.com/lihaoyi/Ammonite/issues/119 issue? Let's keep all the windows related effort and issues in one place, and this does seem like a windows-only problem (it works fine on my mac)

**Comment by glmars** [comment]
Here you are: https://github.com/lihaoyi/Ammonite/issues/119#issuecomment-330241928
