### ISSUE TITLE
conda-forge package for ammonite

### ISSUE THREAD

**Issue by abhi18av** [lihaoyi/Ammonite#703]
Hi guys,

I've been working on the [`conda-forge`](https://conda-forge.org/) package for `ammonite-repl` in this [PR](https://github.com/conda-forge/staged-recipes/pull/4021#issuecomment-331417483) 

I'm running into issues, could you help me get ammonite into the conda management space?

**Comment by lihaoyi** [comment]
I don't know much about conda; if you can't figure it out starting from the "download executable and run it" way of doing things I won't be able to either

**Comment by abhi18av** [comment]
Yup, noted :)

I'll update when it's done.
