### ISSUE TITLE
Release Hash Changed

### ISSUE THREAD

**Issue by bpholt** [lihaoyi/Ammonite#711]
When I install Ammonite via Homebrew, the hashes don't match. Did the released file change?

```shellsession
$ brew install ammonite-repl
==> Downloading https://github.com/lihaoyi/Ammonite/releases/download/1.0.3/2.12-1.0.3
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/29178282/4940b24c-b862-11e7-8f1a-4b29686fe4e5?X-Amz-Algorithm=AWS4-HMAC-SHA
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 95672d12fab73938797df9eed99ad3a07fb4759c5a5dcd6140a74f5dbc03465d
Actual: 69ee90b067cb5546480c54887a3325f87e272464452fbeaaa0628379936bae3c
Archive: /Users/bholt/Library/Caches/Homebrew/ammonite-repl-1.0.3.3
To retry an incomplete download, remove the file above.
```

See https://github.com/Homebrew/homebrew-core/pull/19846 for more details.

**Comment by lihaoyi** [comment]
Oh yeah it did, I screwed up the original upload (forgot to do 2.12.4) and
accidentslly deleted everything in the process of fixing it, so i had to
re-assemble the three jars and re-upload

**Comment by bpholt** [comment]
No worries! I just wanted to confirm the change so we could merge the update into Homebrew. That's been merged, so I'm closing this issue. Thanks!
