### ISSUE TITLE
jitpack dependencies in 1.0.3

### ISSUE THREAD

**Issue by emanresusername** [lihaoyi/Ammonite#712]
slightly more self-contained/non-selfish than [my first mention](https://gitter.im/lihaoyi/Ammonite?at=59ed1529d6c36fca31839261) 😅 
wasn't totally sure how to do a proper bisection for this
so opened this as a possible alternative/repro/placeholder/etc

just doing `sbt run` in [this example repo before/after this commit](https://github.com/emanresusername/amm-jitpack-test/commit/aa0edfe4a629bd856bb6b52bf9432c4681a23614)  demonstrates the issue (...hopefully, either that or just demonstrates my machine is messed up 😨 )

the particular predef code of interest is 
```scala
interp.repositories() ++= Seq(
    coursier.maven.MavenRepository("https://jitpack.io")
)
@
interp.load.ivy(
"com.github.nullpunkt" % "excel-to-json" % "e5f3129"
)
@
import net.nullpunkt.exceljson.convert.ExcelToJsonConverter
```

doesn't seem to have these issues with non-jitpack dependencies 🤔

**Comment by emanresusername** [comment]
looks like something with the coursier RC10 update, [`sbt "test-only ammonite.session.ProjectTests"` works here with a jitpack test](https://github.com/emanresusername/Ammonite/commit/da238194f31a44d7a10bfbfcd9f7b578a9d91384) but fails if you upgrade past RC8 😕 
any ideas on what might trigger that in the RC9 release candidate? @alexarchambault

**Comment by alexarchambault** [comment]
@emanresusername You mean you're seeing an error like [this one](https://travis-ci.org/lihaoyi/Ammonite/jobs/294007836#L3702):
```
 ammonite.session.ProjectTests.jadb 892ms 
  utest.AssertionError: assert{
  error: String = Failed to resolve ivy dependencies:
    com.github.vidstige:jadb:v1.0.1 
      not found: /home/travis/.ivy2/local/com.github.vidstige/jadb/v1.0.1/ivys/ivy.xml
      not found: https://repo1.maven.org/maven2/com/github/vidstige/jadb/v1.0.1/jadb-v1.0.1.pom
      download error: Caught javax.net.ssl.SSLException: java.security.ProviderException: java.secur
  ity.InvalidKeyException: EC parameters error (java.security.ProviderException: java.security.Inval
  idKeyException: EC parameters error) while downloading https://jitpack.io/com/github/vidstige/jadb
  /v1.0.1/jadb-v1.0.1.pom
```

This looks like some kind of ~transient network error. This works fine for me locally (`coursier fetch -r jitpack com.github.vidstige:jadb:v1.0.1` does at least).

**Comment by emanresusername** [comment]
@alexarchambault haha, yeah... the travis tests don't seem to like me, it works on my machine i swear 😅 
when it breaks for me (with the RC10) commit the error is
```scala
ProjectTests
@ interp.repositories() ++= Seq(
@     coursier.maven.MavenRepository("https://jitpack.io")
@ )
@ import $ivy.`com.github.vidstige:jadb:v1.0.1`
@ import se.vidstige.jadb.JadbConnection
X ammonite.session.ProjectTests.jadb 5102ms
  utest.AssertionError: assert{
  error: String = cmd2.sc:1: object JadbConnection is not a member of package se.vidstige.jadb
  import se.vidstige.jadb.JadbConnection
         ^
  Compilation Failed

warning: String =
  out: String =
  res: String =
  info: String =
  expected: String = import se.vidstige.jadb.JadbConnection
    utest.asserts.Asserts$.assertImpl(Asserts.scala:114)
    ammonite.TestRepl.$anonfun$session$5(TestRepl.scala:210)
    ammonite.TestRepl.$anonfun$session$5$adapted(TestRepl.scala:134)
    scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
    scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
    scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
    scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
    scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
    ammonite.TestRepl.session(TestRepl.scala:134)
    ammonite.session.ProjectTests$.$anonfun$tests$19(ProjectTests.scala:333)
```

but yeah, i use coursier rc12 in a bunch of personal projects using jitpack (and even other projects depending on *those* projects through jitpack) with no problem... so i'm pretty baffled why it's happening in this context 😕

**Comment by emanresusername** [comment]
it does look like [something jitpack related happened in coursier in RC9](https://github.com/coursier/coursier/blob/master/notes/1.0.0-RC9.markdown#L5) which is exactly where this error pops up :thinking:

**Comment by emanresusername** [comment]
https://github.com/lihaoyi/Ammonite/pull/725#issuecomment-352404486
