### ISSUE TITLE
Input overwrites itself in sbt test:console invocation

### ISSUE THREAD

**Issue by fooblahblah** [lihaoyi/Ammonite#716]
This is going to be an annoyingly weird report, but I'll try and make it clear.

We've been using Ammonite for months and invoking it via a little snippet using initialCmds in test console.

```
initialCommands in (Test, console) := s"""ammonite.Main().run()"""
```

Then we would run `sbt test:console` and all was good.

At some point that stopped working whereby once an Ammonite session was established, any input seems to overwrite itself, maybe throwing out every other char next to the `@` prompt? So if you type `@ "hello"` it ends up getting displayed as `@ hlo` and you get an error on enter:

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Duser.timezone=UTC
[info] Loading global plugins from /home/jsimpson/.sbt/0.13/plugins
[info] Loading project definition from /home/jsimpson/workspace/homebay/project
[info] Set current project to homebay (in build file:/home/jsimpson/workspace/homebay/)
[info] Starting scala interpreter...
[info] 
Welcome to Scala 2.11.11 (OpenJDK 64-Bit Server VM, Java 1.8.0_152).
Type in expressions for evaluation. Or try :help.

scala> [init] Artima SuperSafe(TM) 1.1.2 activated (licensed to jeff simpson, expires on 21 Mar 2018). Copyright (C) 2015 Artima, Inc. All Rights Reserved.
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/replBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Compiling /home/jsimpson/.ammonite/predef.sc
Welcome to the Ammonite Repl 1.0.3
(Scala 2.11.11 Java 1.8.0_152)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ hlo 
cmd0.sc:1: not found: value hlo
val res0 = hlo
           ^
Compilation Failed
```

Currently we can work around this by just invoking `sbt test:console` (without any `initialCommands` defined) and then issue the input `ammonite.Main().run()`.

We're on Ammonite 1.0.3 (although 1.0.2 did it as well), sbt 0.13.16,  Scala 2.11.11 and OpenJDK 1.8.0_152. I run NixOS, but my colleagues all run OSX and it does the same thing. I've commented everything we had in `~/.ammonite/predefs.sc`, but that has no effect.

If I have time I'll create a simple sbt project and see if it still happens there.

**Comment by emanresusername** [comment]
sounds related to [this change](https://github.com/lihaoyi/Ammonite/pull/596)

try this:

https://github.com/lihaoyi/Ammonite/blob/954ba3383db55b18cad44cd5a235af241e1dce51/readme/Repl.scalatex#L56-L76

**Comment by fooblahblah** [comment]
Thanks @emanresusername. I tried the snippet:

```
sourceGenerators in Test += Def.task {
  val file = (sourceManaged in Test).value / "amm.scala"
  IO.write(file, """object amm extends App { ammonite.Main().run() }""")
  Seq(file)
}.taskValue
```

Then ran `sbt test:run`, but this doesn't seem to drop me into a REPL or it's a broken REPL. I can type commands, but the just get echo'd back to the screen.

```
[error] Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Duser.timezone=UTC
[error] Compiling (synthetic)/ammonite/predef/interpBridge.sc
[error] Compiling (synthetic)/ammonite/predef/replBridge.sc
[error] Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
[error] Compiling /home/jsimpson/.ammonite/predef.sc
[info] Welcome to the Ammonite Repl 1.0.3
[info] (Scala 2.11.11 Java 1.8.0_152)
[info] If you like Ammonite, please support our development at www.patreon.com/lihaoyi
[error] Bye!

hello

```

I haven't tried the second suggestion yet.

**Comment by emanresusername** [comment]
not totally sure, i'm on 2.12.3 and 1.0.2 pending [this issue](https://github.com/lihaoyi/Ammonite/pull/713)
the `--no-home-predef` flag can help eliminate variables 
which is exactly how i arrived at [this version](https://github.com/lihaoyi/Ammonite/pull/706#issue-261193757)

> ...came up in a random other project i was working on and wanted to use the --no-home-predef flag to eliminate some variables and saw that didn't work with the Main().run() version 😢...

**Comment by lihaoyi** [comment]
You probably need `connectInput := true` in SBT
