### ISSUE TITLE
External dependency issue in v1.0.2+

### ISSUE THREAD

**Issue by laughedelic** [lihaoyi/Ammonite#720]
Here is a simple script that adds a dependency on an [external library](https://github.com/ohnosequences/fastarious) published to an S3 maven repo:

```scala
interp.repositories() ++= Seq(
  coursier.MavenRepository("https://s3-eu-west-1.amazonaws.com/releases.era7.com/")
)
interp.load.ivy("ohnosequences" %% "fastarious" % "0.12.0")

@

import ohnosequences.fastarious.fasta._
// some code using it
```

It works fine in Ammonite 1.0.0, but fails in 1.0.2 and 1.0.3 (didn't have 1.0.1 installed locally to check):

```
$ amm test.sc
Compiling test.sc
Compiling test.sc #2
test.sc:8: not found: value ohnosequences
import ohnosequences.fastarious.fasta._
       ^
```

Note, that coursier resolves the dependency, but I still cannot import anything from it.

**Comment by emanresusername** [comment]
[Related?](https://github.com/lihaoyi/Ammonite/pull/713)

**Comment by laughedelic** [comment]
@emanresusername I don't really understand what's #713 about and how it is related. Could you clarify?

**Comment by alexarchambault** [comment]
@laughedelic https://github.com/lihaoyi/Ammonite/pull/713 fixes the issue here. It tweaks a bit which JARs are added to the classpath from Ammonite (some from repositories not having directory listings like Central in particular, like the one above)

**Comment by laughedelic** [comment]
@alexarchambault thanks! Are you going to release a new version with this fix?

**Comment by alexarchambault** [comment]
@lihaoyi should handle releases I think.

**Comment by lihaoyi** [comment]
@alexarchambault feel free to make a release, it's just pushing a tag and CI handles the rest. (and updating the changelog for recent changes, which you are probably more familiar with than I am at this point)
