### ISSUE TITLE
Issues with bash-script counterpart in ammonite shell

### ISSUE THREAD

**Issue by abhi18av** [lihaoyi/Ammonite#721]
Hi **Ammonite** team

I'm running into errors regarding the usage of `ammonite` repl in a non-interactive i.e. purely in a script oriented way.

For example, here's a minimal test script I 

```scala
#!/usr/bin/env amm

import ammonite.ops._



println(wd)

mkdir! pwd/"analysis"

cp.into(wd/"test.sc", wd/"analysis")

cd! pwd/"analysis"

ls!


```

This script works perfectly fine when used from the ammonite repl, however when I tried running it using 
```sh
> chmod +x test.sc
> ./test.sc
```
It raises the following errors

```scala
test.sc:7: not found: value wd
val res_1 = println(wd)
                    ^
test.sc:11: not found: value wd
val res_3 = cp.into(wd/"test.sc", wd/"analysis")
                    ^
test.sc:11: not found: value wd
val res_3 = cp.into(wd/"test.sc", wd/"analysis")
                                  ^
test.sc:13: not found: value cd
val res_4 = cd! pwd/"analysis"
            ^
test.sc:15: could not find implicit value for parameter arg: ammonite.ops.Path
val res_5 = ls!
              ^
Compilation Failed

```

I also tried using `amm --no-default-predef test.sc ` in case there's something wrong in my `predef.sc` 

Here's the content of my `predef.sc` 

```scala 
interp.load.ivy(
  "com.lihaoyi" %
  s"ammonite-shell_${scala.util.Properties.versionNumberString}" %
  ammonite.Constants.version
)
@
val shellSession = ammonite.shell.ShellSession()
import shellSession._
import ammonite.ops._
import ammonite.shell._
ammonite.shell.Configure(interp, repl, wd)


```

But the issue remains the same. I'm using this wonderful shell in a Genomic analysis pipeline - could you please guide me here :)

**Comment by piotrkwiecinski** [comment]
@abhi18av check: https://github.com/lihaoyi/Ammonite/issues/447#issuecomment-242858449

Ammonite in scripts doesn't expose ```wd```. 

In addition if you check docs there is note:
```
pwd: The current working directory of the process. This can't be changed in Java, so if you need another path to work with the convention is to define a wd variable.
```

In ammonite scripts you don't navigate through path the same was as in bash. So there are 2 ways to go about it. One is to use ```pwd``` everywhere if you just do stuff in sub directories:

``` 
#!/usr/bin/env amm

import ammonite.ops._
mkdir! pwd/"analysis"
cp.into(pwd/"test.sc", pwd/"analysis")
ls! pwd/"analysis"
```
Or you can declare wd by yourself:

```
#!/usr/bin/env amm
import ammonite.ops._

val wd = pwd
mkdir! pwd/"analysis"
cp.into(wd/"test.sc", wd/"analysis")
ls! pwd/"analysis"
```

**Comment by abhi18av** [comment]
Thanks @piotrkwiecinski and sorry for replying late.

You suggestion effectively solved the issues I was facing.
