### ISSUE TITLE
Bare minimum funtionality distribution (no third-party libraries in executable file)

### ISSUE THREAD

**Issue by lavrov** [lihaoyi/Ammonite#723]
There are libraries which are included into Ammonite executable file. To name a few those are `scalaj-http`, `upickle`. Moreover `upickle` is deprecated in favor of `play-json`. One can use ivy imports to pull any dependency he needs.

**Comment by piotrkwiecinski** [comment]
upickle is used internally for metadata related to classloader, cache, history and as far as I know @lihaoyi said he's going to resurrect the project. I wouldn't expect for upickle to disappear soon.

scalaj-http is used for remote logger, part of CI and as part of docs. @lihaoyi would have to be ok with dropping remote logger to remove scalaj-http from internals.

**Comment by lihaoyi** [comment]
What exactly is the use case or problem that this issue is solving?

**Comment by lavrov** [comment]
Keeping ammonite executable as small as possible. I guess it's not very valuable by itself, matter of taste. I don't know details, probably many dependencies are used internally and that explains why they are included. Let's close the issues then.
