### ISSUE TITLE
Unable to use Ammonite with Sun Java 9.0.1_11

### ISSUE THREAD

**Issue by gavinbaumanis** [lihaoyi/Ammonite#739]
Hi there,.
I have both Java 1.8 and 9.01 installed.
Ammonite runs fine with the version of Java set to 1.8_152
But fails when trying to run with Java 9.01_11

I realise there is already an issue for java 9 but it specifically mentions OPENJAVA.
The stacktrace is below.

`java.lang.ExceptionInInitializerError
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:458)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$9(Interpreter.scala:495)
  scala.Option$WithFilter.map(Option.scala:146)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:482)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:546)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:346)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:337)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:329)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:104)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:104)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
  scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  scala.collection.immutable.List.foldLeft(List.scala:86)
  ammonite.util.Res$.fold(Res.scala:29)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:106)
  ammonite.repl.Repl.initializePredef(Repl.scala:107)
  ammonite.Main.run(Main.scala:181)
  ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:363)
  ammonite.MainRunner.watchLoop(Main.scala:344)
  ammonite.MainRunner.runRepl(Main.scala:363)
  ammonite.Main$.main0(Main.scala:280)
  ammonite.Main$.main(Main.scala:244)
  ammonite.Main.main(Main.scala)
java.lang.NullPointerException
  ammonite.runtime.Classpath$.<init>(Classpath.scala:30)
  ammonite.runtime.Classpath$.<clinit>(Classpath.scala)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:458)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$9(Interpreter.scala:495)
  scala.Option$WithFilter.map(Option.scala:146)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:482)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:546)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:346)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:337)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:329)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:104)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:104)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
  scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  scala.collection.immutable.List.foldLeft(List.scala:86)
  ammonite.util.Res$.fold(Res.scala:29)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:106)
  ammonite.repl.Repl.initializePredef(Repl.scala:107)
  ammonite.Main.run(Main.scala:181)
  ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:363)
  ammonite.MainRunner.watchLoop(Main.scala:344)
  ammonite.MainRunner.runRepl(Main.scala:363)
  ammonite.Main$.main0(Main.scala:280)
  ammonite.Main$.main(Main.scala:244)
  ammonite.Main.main(Main.scala)`

**Comment by hepin1989** [comment]
```
Compiling (synthetic)/ammonite/predef/interpBridge.sc
java.lang.ExceptionInInitializerError
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:465)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:522)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:521)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:518)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:518)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:554)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:353)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:344)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:336)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:108)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:108)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
  scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  scala.collection.immutable.List.foldLeft(List.scala:86)
  ammonite.util.Res$.fold(Res.scala:29)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:110)
  ammonite.repl.Repl.initializePredef(Repl.scala:111)
  ammonite.Main.run(Main.scala:187)
  ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:369)
  ammonite.MainRunner.watchLoop(Main.scala:350)
  ammonite.MainRunner.runRepl(Main.scala:369)
  mill.Main$.main(Main.scala:74)
  mill.Main.main(Main.scala)
java.lang.NullPointerException
  ammonite.runtime.Classpath$.<init>(Classpath.scala:30)
  ammonite.runtime.Classpath$.<clinit>(Classpath.scala)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:75)
  ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:49)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:465)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:522)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:521)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:518)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:518)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:554)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:353)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:344)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:336)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:108)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:108)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
  scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  scala.collection.immutable.List.foldLeft(List.scala:86)
  ammonite.util.Res$.fold(Res.scala:29)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:110)
  ammonite.repl.Repl.initializePredef(Repl.scala:111)
  ammonite.Main.run(Main.scala:187)
  ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:369)
  ammonite.MainRunner.watchLoop(Main.scala:350)
  ammonite.MainRunner.runRepl(Main.scala:369)
  mill.Main$.main(Main.scala:74)
  mill.Main.main(Main.scala)
```

**Comment by lihaoyi** [comment]
Duplicate https://github.com/lihaoyi/Ammonite/issues/675
