### ISSUE TITLE
``import ammonite._`` shadows interp

### ISSUE THREAD

**Issue by schlichtanders** [lihaoyi/Ammonite#758]
I was suprised finding that I can use ``interp.load`` in a fresh ``amm`` shell, however as soon as I do ``import ammonite._`` this no longer works with the following error output
```
@ import ammonite.interp 
import ammonite.interp

@ interp.load 
cmd1.sc:1: object load is not a member of package ammonite.interp
val res1 = interp.load
                  ^
Compilation Failed
```

is this intended?

**Comment by lihaoyi** [comment]
This is probably unavoidable. There isn't any reason for you to be doing `import ammonite._` and name-shadowing is a fact of life in Scala
