### ISSUE TITLE
FeatureRequest: Please support true multiline input

### ISSUE THREAD

**Issue by schlichtanders** [lihaoyi/Ammonite#770]
**Current Situation:** When dealing with scala multiline code in scripting mode you still have to adapt the source code instead of just running it in the REPL (ammonite has by now the unwrapping support of code blocks { } so that multiline code can be rather easily adapted, but nevertheless you still have to adapt the code)
**FeatureRequest:** I would like to see ammonite have a true multiline support out-of-the-box without any need of code adaptations.

**Suggestion**:
As a reference I want to refer to ipython, which supports this style of multiline input by waiting for the first blank line (i.e. a line with only whitespace) and then executing the whole code chunk.
To be fair, python does not have leading dots, but only need this for method definitions and for loops which have a clear indicator (the colon ``:``) as the start for additional multiline support.

In scala the leading dot in need of multiline support can appear anywhere, so in addition to wait for the blank line, one would ideally skip it in the true output. I mean that if you just want to execute ``1 + 2`` then you have to enter an additional blank line after it (i.e. press Enter twice)
```scala
@ 1 + 2
  
```
(note the blank line in the end without any comments or else)
which should result in overall output
```
@ 1 + 2 
res0: Int = 3
```
where the additional blank line is skipped

**Comment by lihaoyi** [comment]
I'm gonna call this a wontfix. As you said, you can already trivially wrap things in `{}`s, and your description of ipython doesn't really match reality (we _already_ support exactly the same multi-line input that ipython supports)
