### ISSUE TITLE
drop or fix Java 7 build in travis-ci

### ISSUE THREAD

**Issue by xuwei-k** [lihaoyi/Ammonite#774]
travis-ci no longer support oraclejdk7.

https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879

but openjdk7 build fail 😕 https://github.com/lihaoyi/Ammonite/pull/740

**Comment by lihaoyi** [comment]
Build still seems to pass for now

**Comment by xuwei-k** [comment]
🤔 ???
master branch still use oraclejdk7 ( oraclejdk7 setting ignored. force use jdk8 by travis-ci) https://github.com/lihaoyi/Ammonite/blob/6c3552c1dd11b2b5e3e6070a95bef567e0c808d6/.travis.yml#L29
