### ISSUE TITLE
desugar

### ISSUE THREAD

**Issue by MasseGuillaume** [lihaoyi/Ammonite#78]
http://lihaoyi.github.io/Ammonite/#Builtins could also have desugar method

It's useful to scope down an implicit
load.ivy("org.scalaz" %% "scalaz-core" % "7.1.1")
load.ivy("org.scala-lang" % "scala-reflect" % "2.11.6")
import scala.reflect.runtime.{currentMirror ⇒ cm}
import scala.reflect.runtime.universe._
import scala.tools.reflect.ToolBox
val tb = cm.mkToolBox()
showCode(reify{1.just}.tree)
res25: String = "Scalaz.ToMaybeOps(1).just"

**Comment by lihaoyi** [comment]
I have no idea what you just said =/ perhaps discuss on the gitter channel?
