### ISSUE TITLE
[FEATURE REQUEST] Always have an ammonite shell in the background to avoid the startup overhead

### ISSUE THREAD

**Issue by NightMachinary** [lihaoyi/Ammonite#783]
Have you seen https://github.com/ninjudd/drip ? Using it directly or implementing something similar would virtually destroy the startup overhead of the shell. We can always have one Ammonite server process in the background that a new Ammonite shell can connect to.

**Comment by giftig** [comment]
Doesn't look good on the drip front: https://github.com/ninjudd/drip/issues/99

**Comment by lihaoyi** [comment]
Probably not going to happen any time soon
