### ISSUE TITLE
[FEATURE REQUEST] Support bash-like process calling

### ISSUE THREAD

**Issue by NightMachinary** [lihaoyi/Ammonite#784]
Currently my biggest gripe with using Ammonite as my default shell is it's lack of ease for common daily operations I do with zsh. I can't just call `git push -u origin master`, I need to use `%git("push", "-u", "origin", "master")` which is just not idiomatic. It also doesn't support aliases which I find excellent for simplifying my common workflow; E.g., I use `alias bi="brew install"` and then just do `bi ammonite-repl`. If these could be implemented in Scala ,for example like `sh{git init "jekyll is dead"}`, it'd constitute a serious improvement in usability and user-friendliness.
For aliases we can have `sh.createAlias("brew install ","bi")`. Note that this is a better form of alias than bash, since it doesn't automatically add a space to the end of the alias, which makes it more useful.

It would superawesome if Ammonite was modified to support first-class support via special syntax like this `sh git init "jekyll is dead"`, but this is probably impossible?

PS: Even an incomplete solution would be great.

**Comment by pharrington** [comment]
For you first concern, have you tried the scala.sys.process API[1]? If not, it provides implicit conversions from String to scala.sys.process.ProcessBuilder out of the box, so all you have to do is `import sys.process._` and then, for example, `"git push -u origin master"!`. A simple "alias" method follows trivially from this for your second concern. There's probably alot of subtleties I'm overlooking though, so definitely comment further if my suggestion is inadequate.

[1]http://www.scala-lang.org/api/current/scala/sys/process/index.html

**Comment by NightMachinary** [comment]
@pharrington Unfortunately this suffers from the bug of not using the current directory of the shell, but the directory it where the shell was started.

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/Ammonite/pull/717
