### ISSUE TITLE
`import Resovlers._` not working

### ISSUE THREAD

**Issue by rhoslug** [lihaoyi/Ammonite#788]
Hi,

I'm having some trouble getting Ammonite to work. Basically my script is as follows:
```
import ammonite._
import Resolvers._

@

@main
def main(args: String*): Unit = {
  println("Hello World!")
}
```
When I run the script with `amm MyScript.sc` it returns:
```
Compiling /Users/drew.okane/dev/miniblip/scripts/ammonite/MyScript.sc
MyScript.sc:2: not found: value Resolvers
import Resolvers._
       ^
Compilation Failed
```

I have tried the stable version of Ammonite as well as the bleeding edge and both are giving me this error. Any insight?

**Comment by rhoslug** [comment]
Unless something has changed I was trying to add a resolver for a Scala dependency, like here:
https://github.com/lihaoyi/Ammonite/issues/491

**Comment by NeQuissimus** [comment]
Interesting. I do that like so:

```
interp.repositories() ++= Seq(coursier.maven.MavenRepository("http://artifactory.internal/artifactory/mvn"))
```

**Comment by rhoslug** [comment]
@NeQuissimus interesting. That solves my issue. So going forward is that the recommended way for adding other repositories?

**Comment by NeQuissimus** [comment]
I don't think I can answer that but I have never done it differently :)
