### ISSUE TITLE
Code-completion fails with Scalaz imports

### ISSUE THREAD

**Issue by MasseGuillaume** [lihaoyi/Ammonite#79]
Just sharing what scalakata has for code completion. It's based on scala-ide code
https://github.com/MasseGuillaume/ScalaKata/blob/develop/Eval/compile/src/main/scala/com.scalakata.eval/Compiler.scala#L63

Ammonite fails to complete this:
```scala
load.ivy("org.scalaz" %% "scalaz-core" % "7.1.1")
import scalaz._, import Scalaz._
1.j<tab>
```

should have 1.just

You can try at scalakata.com (scalaz is preloaded)

**Comment by lihaoyi** [comment]
Cool, I'll see if I can use your stuff to improve it, thanks!

**Comment by lihaoyi** [comment]
@MasseGuillaume I tried using your code, integrated it into Ammonite, and it still does not code complete the Scalaz example =/ Other things (e.g. import completion) now work, so I'm pretty sure I did it correctly.

**Comment by MasseGuillaume** [comment]
Hum, I will take a look at this when I get back home. Two hypothesis:
* The compiler is not in the correct state (or missing something in the classpath)
* The compiler does not have the correct position. Try with a range of position and collect the result.

**Comment by lihaoyi** [comment]
Yeah I got import autocomplete and constructor autocomplete working great thanks to your code (thanks again!) but Scalaz `.just` is still no go

**Comment by MasseGuillaume** [comment]
1 I'm currious what was the issue
2 Are you interested in a lib to wrap the presentation compiler É

**Comment by lihaoyi** [comment]
Closing in favor of https://github.com/lihaoyi/Ammonite/issues/275
