### ISSUE TITLE
Security risk in Ammonite install method

### ISSUE THREAD

**Issue by benhutchison** [lihaoyi/Ammonite#799]
I have to note:

- ammonite.io is not https
- it includes instructions in the web page that say "just go copy and run this command as root" (eg `sudo curl -L -o /usr/local/bin/amm https://github.com/lihaoyi/Ammonite/releases/download/1.1.0/2.12-1.1.0 && sudo chmod +x /usr/local/bin/amm && amm`)

Is there is a small but non-trivial attack vector created by this combination?

**Comment by lihaoyi** [comment]
Maybe but you can always use `brew install`
