### ISSUE TITLE
Support artifact resolvers to load libraries not published to maven central

### ISSUE THREAD

**Issue by benhutchison** [lihaoyi/Ammonite#80]
Support artifact resolvers to load libraries that are not published to maven central.

There is one existing attempt to do so, by @alexarchambault https://github.com/lihaoyi/Ammonite/pull/66  However, Li Haoyi wasn't willing to accept with alot of unfocused/poorly understood code lifted out of SBT.

**Comment by lihaoyi** [comment]
Possible solution that doesn't involve taking on gobs of magic code: send a PR to 
hard code the handful you care about and be done with it ^_^

**Comment by hohonuuli** [comment]
Just a note that hard-coding support for the local maven repo at "~/.m2/repository" as a default resolver would be extremely useful.

**Comment by lihaoyi** [comment]
This should be a pretty trivial change https://github.com/lihaoyi/Ammonite/blob/master/repl/src/main/scala/ammonite/repl/IvyThing.scala#L54-L69 if anyone wants to hardcode anything; we could also lift `IvyThing` from a top-level-object into a class, have an instance belonging to each `Interpreter`, and have it expose a `Ref` through `ReplAPI` so people can modify it in the REPL
