### ISSUE TITLE
"value XXX is not a member of object ammonite.predef.XXX"

### ISSUE THREAD

**Issue by danielyli** [lihaoyi/Ammonite#801]
### Motivation

I’d like to split my predef file into multiple files, as suggested by the [Ammonite docs](http://ammonite.io/#import$exec).  Specifically, I’d like to put all Java-related imports in a file `~/.ammonite/java.sc` and call that file from `~/.ammonite/predef.sc`.

### How to reproduce

1.  Create a predef file in `~/.ammonite/java.sc` with the contents:

```scala
import java.util._
```

2.  Call this in the `predef.sc` file:

```scala
import $exec.java
```

3.  Start Ammonite.

```
Loading...
Compiling ~/.ammonite/java.sc
java.sc:1: value util is not a member of object ammonite.predef.java
import java.util._
            ^
Compilation Failed

```

### Expected behavior

The import should work.

**Comment by lihaoyi** [comment]
Your `java` script object is shadowing the `java` package; name your script something else

**Comment by danielyli** [comment]
Oh yes, I’m aware of _why_, mechanistically, this doesn’t work. That’s not the issue here.

I would argue this behavior violates the Principle of Least Surprise. Why? Predef files are Scala files (minus the `import $…` syntax), and so users expect them to behave like Scala files. Specifically, Scala files named `foo.sc` don’t silently create a package named `foo`. Even package object files explicitly declare `package object foo`. In short, users (understandably) don’t expect this behavior.

**Comment by danielyli** [comment]
Pinging again. What are your thoughts?

**Comment by siawyoung** [comment]
Funnily enough I encountered this same problem, although it took me a while to recognize that it was the same problem -- I had wanted to learn about Shapeless and thought of using Ammonite as a quick way to get a sandboxed environment up and running quickly. Silly me named the file `shapeless.sc`, and it took me a good half hour to figure out why I couldn't import anything from `import shapeless._`.

The more you know :shrug:
