### ISSUE TITLE
Parallel operations never terminate in script or repl

### ISSUE THREAD

**Issue by eptx** [lihaoyi/Ammonite#806]
create file test.sc with single line of code...
````(0 until 5).par.foreach { i => println(i.toString)}````
> amm test.sc

Execution hangs...

Note running this in the scala repl hangs as well unless launched with...
>scala -Yrepl-class-based 

See https://github.com/scala/scala-parallel-collections/issues/34

Note: This may be the issue I was having with #800

**Comment by lihaoyi** [comment]
duplicate https://github.com/lihaoyi/Ammonite/issues/556

**Comment by eptx** [comment]
work around...
```
object foo {
	def bar = (0 until 5).par.foreach { i => println(i.toString)}
}

foo.bar
```
