### ISSUE TITLE
Support pasting multiline expressions into the REPL

### ISSUE THREAD

**Issue by benhutchison** [lihaoyi/Ammonite#81]
Currently, when a multiline expression is pasted into ammonite repl, it is parsed line by line, which results in different behavior from the how the compiler would interpret it in a file.

Scala REPL in paste mode
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

Seq
 .apply(1)

// Exiting paste mode, now interpreting.

res1: Seq[Int] = List(1)
```

Ammonite
```
@ Seq
res11: scala.collection.Seq.type = scala.collection.Seq$@4f920ec4
@  .apply(1)
<console>:1: illegal start of definition
 .apply(1)
 ^
```

**Comment by lihaoyi** [comment]
This is interesting. I'm not willing to add a `:paste` special command, but I can provide a 
```scala
block{
   ...
}
```

syntax that should be equivalent

**Comment by lihaoyi** [comment]
Fixed by https://github.com/lihaoyi/Ammonite/commit/46fd86de9825558b920cebdbae91878b6cbeb576, which provides the following syntax

```scala
        @ {
            val x = 1
            val y = 2
            x + y
          }
        x: Int = 1
        y: Int = 2
        res0_2: Int = 3
```

**Comment by benhutchison** [comment]
Thanks :) My primary use case for paste mode is trying examples code off people's wikis, blogs etc and trying them out. So, will this allow the `@ {` to be entered, then the code pasted, then `}`, and then eval it all?

**Comment by lihaoyi** [comment]
Just `{`, the `@` is the prompt!

This is assuming the code is well formed, of course. It relies on the parse not-completing/completing to decide whether or not to wait for more.

**Comment by valtih1978** [comment]
[When the next char is available immediately after a tab,
the tab is taken raw instead of invoking completion](https://github.com/scala/scala/pull/5240).

**Comment by schlichtanders** [comment]
just curious: is there reason why ammonite does not implement multiline paste support like ipython by waiting for the first blank line until execution?
