### ISSUE TITLE
reference to show is ambiguous

### ISSUE THREAD

**Issue by danielyli** [lihaoyi/Ammonite#810]
```scala
@ object Foo { def show = ??? }
defined object Foo

@ {
    import Foo._
    show(3)
    show(4)
  }
cmd7.sc:2: reference to show is ambiguous;
it is imported twice in the same scope by
import Foo._
and import _root_.ammonite.$sess.cmd0.Foo.{notify, eq, synchronized, ne, getClass, $hash$hash, show, isInstanceOf, wait, $bang$eq, hashCode, $eq$eq, asInstanceOf, notifyAll, equals}
  val res7_1 = show(3)
               ^
cmd7.sc:3: reference to show is ambiguous;
it is imported twice in the same scope by
import Foo._
and import _root_.ammonite.$sess.cmd0.Foo.{notify, eq, synchronized, ne, getClass, $hash$hash, show, isInstanceOf, wait, $bang$eq, hashCode, $eq$eq, asInstanceOf, notifyAll, equals}
  val res7_2 = show(4)
               ^
Compilation Failed
```

**Comment by lihaoyi** [comment]
This is expected

**Comment by danielyli** [comment]
Are you saying that Ammonite simply can’t handle objects with a member named `show` and that this is acceptable?

**Comment by danielyli** [comment]
Bumping again. I’d like to use Ammonite as my default Scala REPL, but unexpected behavior such as this is concerning. I understand `show` is used in Ammonite for other things, but perhaps it can be shadowed when a user-defined symbol with the same name is imported?

Perhaps the bigger question is: Is replicating the compilation behavior of the standard Scala REPL a goal for Ammonite?

**Comment by jvican** [comment]
Shouldn't it be possible to use `locally` blocks to fix this kind of name conflict? @lihaoyi
