### ISSUE TITLE
Coursier unable to find Ammonite main class

### ISSUE THREAD

**Issue by vlovgr** [lihaoyi/Ammonite#814]
In Ammonite 1.1.0 (and earlier versions), Ammonite could be launched with coursier like this:

```bash
❯ coursier launch com.lihaoyi:ammonite_2.12.4:1.1.0
```

but as of 1.1.1 and 1.1.2, coursier is unable to detect the main class automatically.

```bash
❯ coursier launch com.lihaoyi:ammonite_2.12.6:1.1.1
Cannot find default main class. Specify one with -M or --main.

❯ coursier launch com.lihaoyi:ammonite_2.12.6:1.1.2
Cannot find default main class. Specify one with -M or --main.
```

The workaround is to specify it manually.

```bash
❯ coursier launch com.lihaoyi:ammonite_2.12.6:1.1.2 -M ammonite.Main
```

Looking at the Coursier [main class detection](https://github.com/coursier/coursier/blob/v1.0.3/cli/src/main/scala-2.12/coursier/cli/Helper.scala#L46-L48) (and the [changes](https://github.com/coursier/coursier/blob/master/cli/src/main/scala-2.12/coursier/cli/Helper.scala#L46-L48) -- from [#839](https://github.com/coursier/coursier/issues/839) -- in upcoming 1.1 release), some manifest attributes need to be set for the detection to work. It seems that in Ammonite 1.1.0 and earlier, these were included:

```
Manifest-Version: 1.0
Implementation-Title: ammonite
Implementation-Version: 1.1.0
Specification-Vendor: com.lihaoyi
Specification-Title: ammonite
Implementation-Vendor-Id: com.lihaoyi
Specification-Version: 1.1.0
Implementation-Vendor: com.lihaoyi
Main-Class: ammonite.Main
```

but as of 1.1.1 they are not.

```
Manifest-Version: 1.0
Created-By: Scala mill
Main-Class: ammonite.Main
```

I'm guessing this is because mill is not including them by default, whereas sbt is including them.

The question remains whether:
- the main class detection should be changed in coursier (@alexarchambault mentions [it could need tweaking](https://github.com/coursier/coursier/issues/839#issuecomment-379742328)),
- ammonite should include the manifest attributes currently required by coursier, or
- if mill should include these properties by default, similar to sbt.

**Comment by lihaoyi** [comment]
This appears to be a coursier issue?

**Comment by alexarchambault** [comment]
More a mill issue. It doesn't write a `Main-Class` entry in the manifest of the JARs it generates.

**Comment by mtk** [comment]
this situation still exists as of 12/12/21.  there *is* a `Main-Class` in the MANIFEST.MF file now (but none of the other attributes mentioned above).  manually specifying the main class named by the attribute via `-M ammonite.AmmoniteMain` makes the launch work correctly.

**Comment by mtk** [comment]
the ammonite.json file in the default channel (io.get-coursier.aps) has a mainClass attribute with the value 'ammonite.Main?' but the actual main class name is 'ammonite.AmmoniteMain'.  that seems like the error?

**Comment by mtk** [comment]
I just created a pull request to change the main class name in ammonite.json in coursier/apps.
