### ISSUE TITLE
Completion causes cursor misalignment

### ISSUE THREAD

**Issue by Glavo** [lihaoyi/Ammonite#817]
![image](https://user-images.githubusercontent.com/20694662/40439638-1820d2e0-5eee-11e8-9565-a0e3462a5045.png)
If you press TAB here, the cursor will move to the wrong position:
![image](https://user-images.githubusercontent.com/20694662/40439672-37577e70-5eee-11e8-8896-bddc039ae902.png)
![image](https://user-images.githubusercontent.com/20694662/40439681-3d73a9f0-5eee-11e8-8d21-4a383008af93.png)

**Comment by allanrenucci** [comment]
See jline/jline3#274

**Comment by sake92** [comment]
Some stuff regarding Ammonite/JLine3 that needs attention also: 
- Ctrl-C doesn't work (to kill subprocess)
- TAB insert only works on empty line (blanks). Problem?
- ENTER doesn't work when editing a line (it submits it),
  probably could be solved by checking if the cursor is at the end of input

**Comment by Glavo** [comment]
There are also problem with the completion of the jline 3 frontend:
```scala
@ identity[CharS
```
After pressing TAB here:
```scala
@ identity[CharSCharSequence
```
This problem does not exist when the jline 3 front end is not used.

**Comment by sake92** [comment]
@Glavo I found this comment: https://github.com/Microsoft/WSL/issues/1173#issuecomment-370665039
It seems to work, although I have no idea how. 😄  
You just open regedit and set/create "VirtualTerminalLevel"=dword:00000001 in [HKEY_CURRENT_USER\Console]
