### ISSUE TITLE
Import bundled ujson

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#826]
Theorically ujson is a bundled library like ammonite-ops.

From the REPL I can do this:
```
import ujson.Js
```
but from a script I can't.

ammonite-ops, can be used both from a script and from the REPL, withouth doing `import $ivy`.
The same can be said with:
```
import scalaj.http._
```
Why `ujson` doesn't work?

I'd like to run the same source file from Ammonite and SBT, so I'd like to avoid `import $ivy` constructs.

**Comment by lihaoyi** [comment]
No idea, seems to work for me

```scala
$ amm
Loading...
Welcome to the Ammonite Repl 1.1.2
(Scala 2.12.6 Java 10.0.1)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ Bye!

$ amm foo.sc
ujson.Js$@72eed547

$ cat foo.sc
import ujson.Js
println(Js)
```
