### ISSUE TITLE
Shapeless is not working when used in Ammonite scripts

### ISSUE THREAD

**Issue by lwalejko** [lihaoyi/Ammonite#858]
When I use following code in REPL, it works correctly:
```scala
import $ivy.`com.chuusai::shapeless:2.3.3`

import shapeless._

println(23 :: "foo" :: true :: HNil)
```

But when i save this code to file and run `amm shapeless.sc`, I get folllowing error:

```
shapeless.sc:5: not found: value HNil
val res_2 = println(23 :: "foo" :: true :: HNil)
                                           ^
Compilation Failed
```

**Comment by Jadeszek** [comment]
@lwalejko  
Rename file from `shapeless.sc` - there is probably some bug, but when I saved your code as `x.sc` all works fine. 
Trying to run `shapeless.sc` I'm also getting the error you mentioned.

**Comment by lwalejko** [comment]
@Jadeszek Indeed, renaming the file solves the problem
