### ISSUE TITLE
support interactive with --no-color

### ISSUE THREAD

**Issue by raould** [lihaoyi/Ammonite#860]
I want to use ammonite in interactive emacs buffers e.g. shell, but the coloring does not play well with emacs. So I want a "--no-color" option pretty please.

**Comment by bbarker** [comment]
Fancy seeing you here!

Also, I seem to run it in emacs ansi-term bash without issue, if that helps
at all.

**Comment by Glavo** [comment]
You can start Ammonite repl with the `amm --color false` command
