### ISSUE TITLE
Not working on Cygwin

### ISSUE THREAD

**Issue by ColOfAbRiX** [lihaoyi/Ammonite#862]
Hi,

I'm trying to run Ammonite under Cygwin but it complains and it doesn't work.

This is my setup:
* Ammonite 1.2.1 for Scala 2.12
* Latest updates of Cygwin
* Windows 10 (no, I don't want to use the Windows Subsystem for Linux for several reasons)
* Scala 2.12.6
```
$ scala -version
Scala code runner version 2.12.6 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
```
* Java 1.8.0
```
$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
On first installation:
```
$ sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/1.2.1/2.12-1.2.1) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm' && amm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    884      0 --:--:-- --:--:-- --:--:--   884
100 26.4M  100 26.4M    0     0   948k      0  0:00:28  0:00:28 --:--:-- 1920k
Error: Could not find or load main class ammonite.Main
```
When running on the command line:
```
$ amm
Error: Could not find or load main class ammonite.Main
```

I spent a whole day trying to fix the issue, googling around and experimenting, but no luck.

Can you help, please?

**Comment by sake92** [comment]
Why don't you try using it as `amm.bat`? There are some issues, but most of the stuff regarding Scala works.

**Comment by ColOfAbRiX** [comment]
@sake92 because the documentation is not clear about how to install and run Ammonite. `amm.bat` is mentioned once in the "unstable version" section and right before it I found how to make it work for Cygwin (http://ammonite.io/#UnstableVersions)
I think documentation should be improved with a good "Installation" section

**Comment by ColOfAbRiX** [comment]
This is now fixed, documentation issue.
