### ISSUE TITLE
Cannot download with homebrew !

### ISSUE THREAD

**Issue by MrMic** [lihaoyi/Ammonite#890]
Hi,

Here is the issue:
----- 8< -------------------------->8------------

brew install  ammonite-repl
==> Downloading https://github.com/lihaoyi/Ammonite/releases/download/1.3.2/2.12-1.3.2
######################################################################## 100.0%
curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "ammonite-repl"
Download failed: https://github.com/lihaoyi/Ammonite/releases/download/1.3.2/2.12-1.3.2

------ 8< ---------------------- >8 ---

**Comment by MrMic** [comment]
I also try with the GitHub release: 2.12-1.3.2 and it seems that there 
also is an issue here too !!!
Can't download!

**Comment by sadhen** [comment]
```
$ brew install ammonite-repl
$ amm
Loading...
Welcome to the Ammonite Repl 1.3.3
(Scala 2.12.7 Java 1.8.0_92)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
```

Works fine for me.

**Comment by lihaoyi** [comment]
works for me too
