### ISSUE TITLE
Cannot load some Maven libraries through import $ivy

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#899]
I've created a detailed report in stackoverflow:
https://stackoverflow.com/questions/53170922/import-ivy-in-ammonite

I think this is an Ammonite bug.

**Comment by alexarchambault** [comment]
@DavidPerezIngeniero I answered there, closing this issue.

**Comment by DavidPerezIngeniero** [comment]
Thanks, solved!
