### ISSUE TITLE
Broken compatibilty in Ammonite 1.4.0

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#900]
`cwd` in Ammonite 1.4.0 isn't recognized when doing:

    import ammonite.ops._

but version 1.3.2 does recognize it as valid.
This can broken some existing scripts.

**Comment by lihaoyi** [comment]
`cwd` has been deprecated for years

**Comment by DavidPerezIngeniero** [comment]
OK, I didn't know.  I wrote the script long ago.
