### ISSUE TITLE
Is Ammonite right for me?

### ISSUE THREAD

**Issue by lare96** [lihaoyi/Ammonite#904]
I want to use Ammonite in a dynamic scripting environment for a game. I'm already using the Scala JSR-223 ScriptEngine implementation but I find it to be quite inadequate for what I need. If I were to replace it with Ammonite (assuming that's possible) in order to inherit its features (most notably magic imports and predefs) would it be able to function similarly to how it was before?

**Comment by lihaoyi** [comment]
Good question! Try asking in the gitter channel
