### ISSUE TITLE
ShelloutTests.chained fails on branches other than master

### ISSUE THREAD

**Issue by laci37** [lihaoyi/Ammonite#91]
It fails like this: https://travis-ci.org/laci37/Ammonite/jobs/64836991
It only happens on Travis CI, so probably Travis only pulls the branch that is tested. What other command could we change this to?

**Comment by lihaoyi** [comment]
How about

```
haoyi-mbp:server haoyi$ git init
Reinitialized existing Git repository in /Users/haoyi/src/server/.git/
```

We could not match the whole thing, and instead just look for the substring `"Reinitialized"` or something to make sure the command worked

**Comment by lihaoyi** [comment]
I've done this in master
