### ISSUE TITLE
Can't run ammonite on Mac, NoSuchFileException during installation

### ISSUE THREAD

**Issue by Stedelie** [lihaoyi/Ammonite#915]
Hello there, my system runs Mac os 10.14.2. I install ammonite-repl through the command shown on the website: 

`
$ sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/1.6.0/2.12-1.6.0) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm' && amm`

but during the installation I get an error:

```
➜  ~ sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/1.6.0/2.12-1.6.0) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm' && amm

Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    265      0 --:--:--  0:00:02 --:--:--   265
100 27.5M  100 27.5M    0     0   517k      0  0:00:54  0:00:54 --:--:--  493k
Loading...
Exception in thread "main" java.nio.file.NoSuchFileException: /Users/my_user/.ammonite/session
```

What am I missing?

**Comment by lihaoyi** [comment]
Fixed in master; should be out in 1.6.1 which I just kicked off the build for
