### ISSUE TITLE
Deploy script => convert ammonite script to executable fat JAR

### ISSUE THREAD

**Issue by david-bouyssie** [lihaoyi/Ammonite#919]
I don't know if it would be possible but I would love to have an ammonite command line allowing to convert a .sc script into a JAR that could be executed. Or even better a native executable for a specific target platform.

Is it something that is already possible to do using Mill?

**Comment by lihaoyi-databricks** [comment]
yep use mill

**Comment by david-bouyssie** [comment]
Ok but what would be a typical Mill command line to build from an Ammonite script?

**Comment by david-bouyssie** [comment]
Since my post is one year old, I wanted to make an update.
Still very interested in such a feature, I wish this could happen.
