### ISSUE TITLE
Ctrl-C is broken

### ISSUE THREAD

**Issue by lihaoyi-databricks** [lihaoyi/Ammonite#920]
It no longer seems to interrupt runaway while loops. @alexarchambault could it have been one of your changes that broke it?

**Comment by alexarchambault** [comment]
Possibly https://github.com/lihaoyi/Ammonite/commit/84d48542654285a9268964e4571fe0a91ef335d8 (seems it broke between `1.2.0` and `1.2.1`). Looking at it…

**Comment by alexarchambault** [comment]
And as I don't rely on that in almond, interrupts work fine there…
