### ISSUE TITLE
can I specify downloading directory ?

### ISSUE THREAD

**Issue by balanx** [lihaoyi/Ammonite#924]
os: windows 10 / cygwin-64 / java 1.8.151 / scala 2.12.8

home directory,
C:\Users\Administrator\.ammonite

all .jar file downloaded in the position,
C:\Users\Administrator\AppData\Local\Coursier\cache

can I put the downloading dir to other place specified by command option ?
I've tried '--home', it didn't work.

thanks very much.

**Comment by lihaoyi** [comment]
questions go in the gitter channel
