### ISSUE TITLE
How do you write a script using Cats Effect IOApp or Scalaz zio App?

### ISSUE THREAD

**Issue by mcanlas** [lihaoyi/Ammonite#937]
Both of these libraries "take over" the `main` method of the outer object.

What would be the way of writing this in Ammonite? Is it possible?

Edit: I asked this question assuming that either of the libraries do something special that could not be replicated manually. I'm still not totally sure of their inner workings.

If their `App` traits are nothing special, it is possible to just build the IOs and run them yourself, as below.

```scala
object CatsEffectMain {
  def main(args: Array[String]): Unit = {
    val io =
      IO {
        println("Hello, world!")
      }.as(ExitCode.Success)

    io.unsafeRunSync()
  }
}

object ScalazZioMain {
  def main(args: Array[String]): Unit = {
    val runtime = new scalaz.zio.DefaultRuntime {}
    val io = putStrLn("Hello World!")

    runtime.unsafeRun(io)
  }
}
```

**Comment by lihaoyi** [comment]
Seems like you already found your answer???

**Comment by mcanlas** [comment]
Maybe. Just wasn't sure if that was "the right" thing to do.
