### ISSUE TITLE
IndexOutOfBoundsException when giving initial commands to Repl.run

### ISSUE THREAD

**Issue by jrduncans** [lihaoyi/Ammonite#94]
Trying to set up ammonite-repl in sbt to include imports, but it’s throwing an error.  Here is my setup code:

`initialCommands in console := s"""ammonite.repl.Repl.run("import org.joda.time._")”""`

Error is: 

`Loading Ammonite Repl... import org.joda.time._java.lang.IndexOutOfBoundsException: Index: -1, Size: 0 at java.util.LinkedList.checkElementIndex(LinkedList.java:555) at java.util.LinkedList.get(LinkedList.java:476) at jline.console.history.MemoryHistory.get(MemoryHistory.java:96) at ammonite.repl.frontend.JLineFrontend$$anon$1.update(JLineFrontend.scala:110)`

**Comment by lihaoyi** [comment]
I'm 99% sure I've seen this before and it was a result of a corrupted `~/.amm` history file. https://github.com/lihaoyi/Ammonite/issues/101 should fix this so the file won't get corrupted so easily

**Comment by jrduncans** [comment]
This happened on the first run on a new machine, with no ~/.amm history file.

**Comment by lihaoyi** [comment]
This has been totally revamped, want to give it another shot?

**Comment by lihaoyi** [comment]
Closing for now, feel free to re-open

**Comment by jrduncans** [comment]
Test with 0.4.5, and it works now!

**Comment by lihaoyi** [comment]
Yay =)
