### ISSUE TITLE
Cache script loading for performance

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#95]
A common usecase for scripts is that they're run over and over. If they don't change, then we shouldn't need to re-compile them.

As discussed with @laci37, this would look something like

- Caching will be persistent somehow
- We'll cache the compilation blocks of loaded scripts separately under top-level cache-tags each
- The cache tags be a hash of classpath, previous commands (in-same-script), and the block-code
- Loaded scripts would not have access to loading environment, for encapsulation and ease-of-caching
- We'd implement this by limiting the imports provided inside load.file, and replace the auto-increment wrapper-names with cache-tag-names for uniqueness
- This will mean scripts will be cached more often as we can be 100% sure that non-classpath-changing commands (e.g. 2+2) run before the script will not affect its compilation

**Comment by lihaoyi** [comment]
@laci37 here's another question for you: we've already agreed that scripts will not be able to grab things from the caller's dynamic scope. What about the inverse? If I perform an import in a script, will it be visible to the loader after I finish loading it?

The downside of doing this is that it allows more leakage. The downside of *not* is that without this, there's basically no way to abstract over imports; a lot of people will probably want to load a "predef" script that imports all the stuff they care about.

A possible compromise could be to only allow definitions and imports from the *last* CompilationUnit of a script to be visible to the outside world. That would allow the end-user to customize encapsulation/exporting, and only export the things he wants to export.

What if you don't want to export *everything* in the last compilation unit? Well there's always labelling things `private`. That doesn't work now but could work with some minor tweaks to the parser which would make it do exactly what you'd expect

**Comment by laci37** [comment]
This would be simple to do. However I'd prefer making all compilation blocks behave the same way and do not export anything by default. I have to think about how to do this.

**Comment by lihaoyi** [comment]
Yeah one problem is that Scala doesn't currently have an idea of exports; everything is implicitly public unless turned private =/ If it did the same thing as C# and made public-ness opt-in then we could just use that.

Also, annotations don't work because you can't annotate imports =(

**Comment by lihaoyi** [comment]
Removing this from 0.4.0, since this will probably take some time to land, it's been a while since the last release, and I don't want to delay it. It can get on the next train

**Comment by lihaoyi** [comment]
Actually it seems reasonably soon, so I'll wait

**Comment by lihaoyi** [comment]
Closed by #115
