### ISSUE TITLE
Suggest to mvnrepository.com that ammonite syntax should be supported

### ISSUE THREAD

**Issue by mslinn** [lihaoyi/Ammonite#960]
MvnRepository.com is a valuable resource for discovering Java and Scala libraries. It supports Maven-compatible build systems such as SBT and Gradle. It currently does not offer incantations for Ammonite.

[<img src="https://courseassets.scalacourses.com/1/html/ScalaCore/assets/images/mvnrepo.jpg">]( https://mvnrepository.com/artifact/com.lihaoyi/ammonite-repl_2.12.8/1.6.6-7-5e5461b)

Seems like it would be no problem for them to provide Ammonite support.
Someone should ask them!

Their contact email is shown as: info@mvnrepository.com

**Comment by lihaoyi** [comment]
sure, feel free to send them an email

**Comment by mslinn** [comment]
I sent the following email, which markdown butchered because of backquotes. The email was not butchered:

Subject: Please consider supporting Ammonite syntax

MvnRepository.com is a valuable resource for discovering Java and Scala libraries. As you of course well know, the site supports Maven-compatible build systems such as SBT and Gradle. We would like to suggest that MvnRepository also support incantations for Ammonite. The syntax is documented here.

In case the Ammonite documentation seems confusing, because the examples show more than is required for MvnRepository users, the following examples show all that would need to be provided to MvnRepository users:


The Ammonite incantation to declare scalaz-core 7.2.27 as a dependency is:

import $ivy.`org.scalaz::scalaz-core:7.2.27`


The Ammonite incantation to declare Google Guava 18.0 is:

import $ivy.`com.google.guava:guava:18.0`

Thank you,
Mike
