### ISSUE TITLE
part of the folder after "." goes to "ext" instead of "basename"

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/Ammonite#962]
I noticed that in the latest ammonite a controversial decision to split path.name into baseName and ext was made. The main problem here is that if I have a folder with "." as part of the name, like "part.one.two" the baseName becomes "part.one" while ext becomes "two". I think that extension is File-specific thing and baseName should be "part.one.two" for the folder. Of course some people can have another opinion, the problem is that whenever name does not exist baseName / ext separation for folders will always lead to a big confusion.

**Comment by lihaoyi** [comment]
This could be argued either way
