### ISSUE TITLE
Can't use maven dependency path without scala version

### ISSUE THREAD

**Issue by eantono** [lihaoyi/Ammonite#966]
I'm trying to resolve dependencies in a local maven repository where the scala version isn't appended onto the module name, and I can't determine a way to do this.

When I run `import $ivy.`org.path::module-name:1.0.0`
gives me the following exception:
`java.net.MalformedURLException: No protocol found in URL /path/to/.m2/repository/org/path/module-name_2.12/1.0.0/module-name_2.12-1.0.0.pom`

The intended path for this library is 
`/path/to/.m2/repository/org/path/module-name/1.0.0/module-name-1.0.0.pom`

Is there a way to get the desired behavior?

**Comment by lihaoyi** [comment]
see http://ammonite.io/#import$ivy
