### ISSUE TITLE
Vi Key Bindings for Ammonite Shell :)

### ISSUE THREAD

**Issue by chengpohi** [lihaoyi/Ammonite#969]
After a long time, I decide to try **Ammonite Shell** again, so upgrade [Vi mode](https://github.com/chengpohi/ammonite-vi) plugin to support **Ammonite Shell** **1.6** version. Hope it's helpful 😃

Install and usage:

```
interp.load.ivy("com.github.chengpohi" %% "ammonite-vi" % "1.6.1")

@

val shellSession = ammonite.shell.ShellSession()
import shellSession._
repl.frontEnd() match {
  case ammoniteFrontEnd: ammonite.repl.AmmoniteFrontEnd => {
    println("VI Mode Enabled")
    com.github.chengpohi.VIMode(repl, wd)
  }
  case _ =>
}
```

![2019-05-26 17 04 16](https://user-images.githubusercontent.com/5118048/58379610-56f3ea00-7fd8-11e9-8c3f-e5a69270aa5a.gif)

**Comment by lihaoyi** [comment]
Great! If you wish, you can add it to the readme so people can find it
