### ISSUE TITLE
Under OpenJDK 11, Ammonite requires >3500Mbyte to start up

### ISSUE THREAD

**Issue by TJC** [lihaoyi/Ammonite#970]
Under the older OpenJDK 8, Ammonite only needs a few hundred megabytes to start up, but with OpenJDK 11, around 3500 to 4000 mbyte is required.  
(This is when operating with Docker or Kubernetes memory limits applied.)

This is a major regression from JDK 8 -- do you have any idea what is going on?

It's worth noting that the basic Scala REPL runs fine on JDK11 with just a few hundred MB RAM limit.

## Reproducing issue on JDK11

To reproduce, create `Dockerfile` from this:
```
FROM openjdk:11
RUN curl -Lo /amm https://github.com/lihaoyi/Ammonite/releases/download/1.6.7/2.12-1.6.7
CMD ["java", "-Xmx500M", "-cp", "/amm", "ammonite.Main"]
# or CMD ["sh", "/amm"]
```

Then run:

`docker build -t memtest .`

Then finally, run ammonite instead the container with a 1000mbyte memory limit:

`docker run -ti --rm --memory 1000M memtest`

It will be killed with an out of memory error.

Repeat the `docker run` with a 4000M memory limit, and it succeeds.

## Checking how it performs on JDK8

If you go back to JDK8, everything works fine.

Dockerfile for JDK8:
```
FROM openjdk:8
RUN curl -Lo /amm https://github.com/lihaoyi/Ammonite/releases/download/1.6.7/2.12-1.6.7
CMD ["java", "-Xmx500M", "-cp", "/amm", "ammonite.Main"]
```

Build and run that, and it'll run fine -- even if you drop the memory limit right down.

**Comment by quelgar** [comment]
Weirdly, I'm finding that Java 15 doesn't have this problem.

**Comment by TJC** [comment]
I've just retested this on updated versions of both OpenJDK 11, and Ammonite.
- OpenJDK 11.0.9.1
- Ammonite Repl 2.3.8

These seem to work fine. Hurrah!
I will close the ticket.
