### ISSUE TITLE
expected end-of-input

### ISSUE THREAD

**Issue by balanx** [lihaoyi/Ammonite#998]
scala-2.12.9
Java 1.8.0_40
Ammonite 2.12-1.6.9

I got the error as below.
=========================
$ ./amm examples/hello.scala
hello.scala:2:1 expected end-of-input
package examples
^
=========================

https://github.com/balanx/chisel-make/blob/master/examples/hello.scala

**Comment by balanx** [comment]
May you give some explainations for the error. I did the same command successfully at the old version of amm. thanks very much.

**Comment by eefresher** [comment]
hello,sorry to disturb you ,while i run the code inthe jupyter ,I got the same problem ,have you fix it?
